export { PlatformProvider } from "./platform-context";
export { usePlatform, useOptionalPlatform } from "./use-platform";
export {
  PathSelectionInProgressError,
  type LocationActionsCapability,
  type DesktopUpdateCapability,
  type DiagnosticLogsCapability,
  type DesktopUpdateStatus,
  type MarketplaceAutoSyncEvent,
  type PluginInstallProgress,
  type PluginMarketplaceCapability,
  type ManualUpdateReason,
  type LocationTarget,
  type PathSelectionKind,
  type PlatformAdapter,
  type SaveTextFileOptions,
  type SelectPathOptions,
  type SelectSavePathOptions,
  type SurfaceBounds,
  type SurfaceCapability,
  type SurfaceOpenTarget,
  type SurfaceKind,
  type DownloadAction,
  type ResolveDownloadOutcome,
  type SurfaceEvent,
  type SurfaceRecord,
  type SurfaceState,
  type SurfaceTarget,
  type WindowControlsCapability,
  type WindowManagerOs,
  type WorktreeStorageCapability,
} from "./types";
