//! Endpoint declarations for the fileSystem generated-client namespace.

use crate::frontend::{FrontendEndpoint, FrontendResponseMode};

const NAMESPACE: &str = "fileSystem";

pub(super) const ENDPOINTS: &[FrontendEndpoint] = &[
    FrontendEndpoint {
        operation_name: "listWorkspaceDirectory",
        namespace: NAMESPACE,
        member_name: "listWorkspaceDirectory",

        request_type: "ListWorkspaceDirectoryRequest",
        response_type: "ListWorkspaceDirectoryResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "readWorkspaceFile",
        namespace: NAMESPACE,
        member_name: "readWorkspaceFile",
        request_type: "ReadWorkspaceFileRequest",
        response_type: "ReadWorkspaceFileResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "searchWorkspace",
        namespace: NAMESPACE,
        member_name: "searchWorkspace",
        request_type: "SearchWorkspaceRequest",
        response_type: "SearchWorkspaceResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "watchWorkspace",
        namespace: NAMESPACE,
        member_name: "watchWorkspace",
        request_type: "WatchWorkspaceRequest",
        response_type: "WorkspaceFileEventBatch",
        response_mode: FrontendResponseMode::Stream,
    },
    FrontendEndpoint {
        operation_name: "listProjectDirectory",
        namespace: NAMESPACE,
        member_name: "listProjectDirectory",
        request_type: "ListProjectDirectoryRequest",
        response_type: "ListWorkspaceDirectoryResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "readProjectFile",
        namespace: NAMESPACE,
        member_name: "readProjectFile",
        request_type: "ReadProjectFileRequest",
        response_type: "ReadWorkspaceFileResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "searchProject",
        namespace: NAMESPACE,
        member_name: "searchProject",
        request_type: "SearchProjectRequest",
        response_type: "SearchWorkspaceResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "watchProject",
        namespace: NAMESPACE,
        member_name: "watchProject",
        request_type: "WatchProjectRequest",
        response_type: "WorkspaceFileEventBatch",
        response_mode: FrontendResponseMode::Stream,
    },
    FrontendEndpoint {
        operation_name: "createWorkspaceEntry",
        namespace: NAMESPACE,
        member_name: "createWorkspaceEntry",
        request_type: "CreateWorkspaceEntryRequest",
        response_type: "WorkspaceEntry",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "createProjectEntry",
        namespace: NAMESPACE,
        member_name: "createProjectEntry",
        request_type: "CreateProjectEntryRequest",
        response_type: "WorkspaceEntry",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "copyWorkspaceEntry",
        namespace: NAMESPACE,
        member_name: "copyWorkspaceEntry",
        request_type: "CopyWorkspaceEntryRequest",
        response_type: "WorkspaceEntry",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "copyProjectEntry",
        namespace: NAMESPACE,
        member_name: "copyProjectEntry",
        request_type: "CopyProjectEntryRequest",
        response_type: "WorkspaceEntry",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "moveWorkspaceEntry",
        namespace: NAMESPACE,
        member_name: "moveWorkspaceEntry",
        request_type: "MoveWorkspaceEntryRequest",
        response_type: "WorkspaceEntry",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "moveProjectEntry",
        namespace: NAMESPACE,
        member_name: "moveProjectEntry",
        request_type: "MoveProjectEntryRequest",
        response_type: "WorkspaceEntry",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "deleteWorkspaceEntry",
        namespace: NAMESPACE,
        member_name: "deleteWorkspaceEntry",
        request_type: "DeleteWorkspaceEntryRequest",
        response_type: "DeleteFileSystemEntryResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "deleteProjectEntry",
        namespace: NAMESPACE,
        member_name: "deleteProjectEntry",
        request_type: "DeleteProjectEntryRequest",
        response_type: "DeleteFileSystemEntryResponse",
        response_mode: FrontendResponseMode::Unary,
    },
];
