//! Endpoint declarations for the session generated-client namespace.

use crate::frontend::{FrontendEndpoint, FrontendHttpMethod, NO_PATH_PARAMS, SESSION_PATH_PARAMS};
use ora_contracts::{
    SESSION_ATTACH_PATH, SESSION_CONFIG_PATH, SESSION_LOAD_PATH, SESSION_PATH,
    SESSION_PERMISSION_RESPONSE_PATH, SESSION_PROMPT_PATH, SESSION_RESUME_HISTORY_PATH,
    SESSION_STOP_PATH, SESSION_SWITCH_AGENT_PATH, SESSION_WARM_PATH, SESSIONS_PATH,
};

const NAMESPACE: &str = "session";

pub(super) const ENDPOINTS: &[FrontendEndpoint] = &[
    FrontendEndpoint {
        operation_name: "warmSession",
        namespace: NAMESPACE,
        member_name: "warm",
        method: FrontendHttpMethod::Post,
        path_template: SESSION_WARM_PATH,
        request_type: "WarmSessionRequest",
        response_type: "WarmSessionResponse",
        path_params: NO_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "setSessionConfig",
        namespace: NAMESPACE,
        member_name: "setConfig",
        method: FrontendHttpMethod::Post,
        path_template: SESSION_CONFIG_PATH,
        request_type: "SetSessionConfigRequest",
        response_type: "SetSessionConfigResponse",
        path_params: SESSION_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "attachSession",
        namespace: NAMESPACE,
        member_name: "attach",
        method: FrontendHttpMethod::Post,
        path_template: SESSION_ATTACH_PATH,
        request_type: "AttachSessionRequest",
        response_type: "AttachSessionResponse",
        path_params: SESSION_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "getSession",
        namespace: NAMESPACE,
        member_name: "get",
        method: FrontendHttpMethod::Get,
        path_template: SESSION_PATH,
        request_type: "GetSessionRequest",
        response_type: "GetSessionResponse",
        path_params: SESSION_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "listSessions",
        namespace: NAMESPACE,
        member_name: "list",
        method: FrontendHttpMethod::Get,
        path_template: SESSIONS_PATH,
        request_type: "ListSessionsRequest",
        response_type: "ListSessionsResponse",
        path_params: NO_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "loadSession",
        namespace: NAMESPACE,
        member_name: "load",
        method: FrontendHttpMethod::Post,
        path_template: SESSION_LOAD_PATH,
        request_type: "LoadSessionRequest",
        response_type: "LoadSessionEvent",
        path_params: SESSION_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "promptSession",
        namespace: NAMESPACE,
        member_name: "prompt",
        method: FrontendHttpMethod::Post,
        path_template: SESSION_PROMPT_PATH,
        request_type: "PromptSessionRequest",
        response_type: "PromptSessionEvent",
        path_params: SESSION_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "respondToSessionPermission",
        namespace: NAMESPACE,
        member_name: "respondToPermission",
        method: FrontendHttpMethod::Post,
        path_template: SESSION_PERMISSION_RESPONSE_PATH,
        request_type: "RespondToPermissionRequest",
        response_type: "RespondToPermissionResponse",
        path_params: SESSION_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "stopSession",
        namespace: NAMESPACE,
        member_name: "stop",
        method: FrontendHttpMethod::Post,
        path_template: SESSION_STOP_PATH,
        request_type: "StopSessionRequest",
        response_type: "StopSessionResponse",
        path_params: SESSION_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "switchSessionAgent",
        namespace: NAMESPACE,
        member_name: "switchAgent",
        method: FrontendHttpMethod::Post,
        path_template: SESSION_SWITCH_AGENT_PATH,
        request_type: "SwitchSessionAgentRequest",
        response_type: "SwitchSessionAgentResponse",
        path_params: SESSION_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "resumeSessionHistory",
        namespace: NAMESPACE,
        member_name: "resumeHistory",
        method: FrontendHttpMethod::Post,
        path_template: SESSION_RESUME_HISTORY_PATH,
        request_type: "ResumeSessionHistoryRequest",
        response_type: "ResumeSessionHistoryResponse",
        path_params: SESSION_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "deleteSession",
        namespace: NAMESPACE,
        member_name: "delete",
        method: FrontendHttpMethod::Delete,
        path_template: SESSION_PATH,
        request_type: "DeleteSessionRequest",
        response_type: "DeleteSessionResponse",
        path_params: SESSION_PATH_PARAMS,
        has_json_body: false,
    },
];
