//! Endpoint declarations for the task generated-client namespace.

use crate::frontend::{
    FrontendEndpoint, FrontendHttpMethod, NO_PATH_PARAMS, TASK_COMMENT_PATH_PARAMS,
    TASK_PATH_PARAMS,
};
use ora_contracts::{
    TASK_COMMIT_PATH, TASK_DIFF_COMMENT_REPLIES_PATH, TASK_DIFF_COMMENT_STATUS_PATH,
    TASK_DIFF_COMMENTS_PATH, TASK_DIFF_PATH, TASK_PATH, TASK_PUSH_PATH, TASK_WORKSPACE_PATH,
    TASKS_PATH,
};

const NAMESPACE: &str = "task";

pub(super) const ENDPOINTS: &[FrontendEndpoint] = &[
    FrontendEndpoint {
        operation_name: "createTask",
        namespace: NAMESPACE,
        member_name: "create",
        method: FrontendHttpMethod::Post,
        path_template: TASKS_PATH,
        request_type: "CreateTaskRequest",
        response_type: "CreateTaskResponse",
        path_params: NO_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "getTask",
        namespace: NAMESPACE,
        member_name: "get",
        method: FrontendHttpMethod::Get,
        path_template: TASK_PATH,
        request_type: "GetTaskRequest",
        response_type: "GetTaskResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "listTasks",
        namespace: NAMESPACE,
        member_name: "list",
        method: FrontendHttpMethod::Get,
        path_template: TASKS_PATH,
        request_type: "ListTasksRequest",
        response_type: "ListTasksResponse",
        path_params: NO_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "updateTask",
        namespace: NAMESPACE,
        member_name: "update",
        method: FrontendHttpMethod::Put,
        path_template: TASK_PATH,
        request_type: "UpdateTaskRequest",
        response_type: "UpdateTaskResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "deleteTask",
        namespace: NAMESPACE,
        member_name: "delete",
        method: FrontendHttpMethod::Delete,
        path_template: TASK_PATH,
        request_type: "DeleteTaskRequest",
        response_type: "DeleteTaskResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "getTaskWorkspace",
        namespace: NAMESPACE,
        member_name: "getWorkspace",
        method: FrontendHttpMethod::Get,
        path_template: TASK_WORKSPACE_PATH,
        request_type: "GetTaskWorkspaceRequest",
        response_type: "GetTaskWorkspaceResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "getTaskDiff",
        namespace: NAMESPACE,
        member_name: "getDiff",
        method: FrontendHttpMethod::Get,
        path_template: TASK_DIFF_PATH,
        request_type: "GetTaskDiffRequest",
        response_type: "GetTaskDiffResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "commitTaskChanges",
        namespace: NAMESPACE,
        member_name: "commitChanges",
        method: FrontendHttpMethod::Post,
        path_template: TASK_COMMIT_PATH,
        request_type: "CommitTaskChangesRequest",
        response_type: "CommitTaskChangesResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "pushTaskBranch",
        namespace: NAMESPACE,
        member_name: "pushBranch",
        method: FrontendHttpMethod::Post,
        path_template: TASK_PUSH_PATH,
        request_type: "PushTaskBranchRequest",
        response_type: "PushTaskBranchResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "listTaskDiffComments",
        namespace: NAMESPACE,
        member_name: "listDiffComments",
        method: FrontendHttpMethod::Get,
        path_template: TASK_DIFF_COMMENTS_PATH,
        request_type: "ListTaskDiffCommentsRequest",
        response_type: "ListTaskDiffCommentsResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "createTaskDiffComment",
        namespace: NAMESPACE,
        member_name: "createDiffComment",
        method: FrontendHttpMethod::Post,
        path_template: TASK_DIFF_COMMENTS_PATH,
        request_type: "CreateTaskDiffCommentRequest",
        response_type: "CreateTaskDiffCommentResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "replyTaskDiffComment",
        namespace: NAMESPACE,
        member_name: "replyDiffComment",
        method: FrontendHttpMethod::Post,
        path_template: TASK_DIFF_COMMENT_REPLIES_PATH,
        request_type: "ReplyTaskDiffCommentRequest",
        response_type: "ReplyTaskDiffCommentResponse",
        path_params: TASK_COMMENT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "setTaskDiffCommentStatus",
        namespace: NAMESPACE,
        member_name: "setDiffCommentStatus",
        method: FrontendHttpMethod::Put,
        path_template: TASK_DIFF_COMMENT_STATUS_PATH,
        request_type: "SetTaskDiffCommentStatusRequest",
        response_type: "SetTaskDiffCommentStatusResponse",
        path_params: TASK_COMMENT_PATH_PARAMS,
        has_json_body: true,
    },
];
