//! Endpoint declarations for the workflow generated-client namespace.

use crate::frontend::{
    FrontendEndpoint, FrontendHttpMethod, NO_PATH_PARAMS, WORKFLOW_PATH_PARAMS,
    WORKFLOW_SNAPSHOT_PATH_PARAMS, WORKFLOW_VERSION_PATH_PARAMS,
};
use ora_contracts::{
    WORKFLOW_ACTIVATE_PATH, WORKFLOW_DRAFT_PATH, WORKFLOW_PATH, WORKFLOW_PUBLISH_PATH,
    WORKFLOW_ROLLBACK_PATH, WORKFLOW_SNAPSHOT_PATH, WORKFLOW_VERSION_PATH, WORKFLOW_VERSIONS_PATH,
    WORKFLOWS_PATH,
};

const NAMESPACE: &str = "workflow";

pub(super) const ENDPOINTS: &[FrontendEndpoint] = &[
    FrontendEndpoint {
        operation_name: "createWorkflow",
        namespace: NAMESPACE,
        member_name: "create",
        method: FrontendHttpMethod::Post,
        path_template: WORKFLOWS_PATH,
        request_type: "CreateWorkflowRequest",
        response_type: "CreateWorkflowResponse",
        path_params: NO_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "getWorkflow",
        namespace: NAMESPACE,
        member_name: "get",
        method: FrontendHttpMethod::Get,
        path_template: WORKFLOW_PATH,
        request_type: "GetWorkflowRequest",
        response_type: "GetWorkflowResponse",
        path_params: WORKFLOW_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "listWorkflows",
        namespace: NAMESPACE,
        member_name: "list",
        method: FrontendHttpMethod::Get,
        path_template: WORKFLOWS_PATH,
        request_type: "ListWorkflowsRequest",
        response_type: "ListWorkflowsResponse",
        path_params: NO_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "updateWorkflow",
        namespace: NAMESPACE,
        member_name: "update",
        method: FrontendHttpMethod::Put,
        path_template: WORKFLOW_PATH,
        request_type: "UpdateWorkflowRequest",
        response_type: "UpdateWorkflowResponse",
        path_params: WORKFLOW_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "deleteWorkflow",
        namespace: NAMESPACE,
        member_name: "delete",
        method: FrontendHttpMethod::Delete,
        path_template: WORKFLOW_PATH,
        request_type: "DeleteWorkflowRequest",
        response_type: "DeleteWorkflowResponse",
        path_params: WORKFLOW_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "getDraft",
        namespace: NAMESPACE,
        member_name: "getDraft",
        method: FrontendHttpMethod::Get,
        path_template: WORKFLOW_DRAFT_PATH,
        request_type: "GetDraftRequest",
        response_type: "GetDraftResponse",
        path_params: WORKFLOW_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "updateDraft",
        namespace: NAMESPACE,
        member_name: "updateDraft",
        method: FrontendHttpMethod::Put,
        path_template: WORKFLOW_DRAFT_PATH,
        request_type: "UpdateDraftRequest",
        response_type: "UpdateDraftResponse",
        path_params: WORKFLOW_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "publishWorkflow",
        namespace: NAMESPACE,
        member_name: "publish",
        method: FrontendHttpMethod::Post,
        path_template: WORKFLOW_PUBLISH_PATH,
        request_type: "PublishWorkflowRequest",
        response_type: "PublishWorkflowResponse",
        path_params: WORKFLOW_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "rollbackWorkflow",
        namespace: NAMESPACE,
        member_name: "rollback",
        method: FrontendHttpMethod::Post,
        path_template: WORKFLOW_ROLLBACK_PATH,
        request_type: "RollbackWorkflowRequest",
        response_type: "RollbackWorkflowResponse",
        path_params: WORKFLOW_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "activateWorkflow",
        namespace: NAMESPACE,
        member_name: "activate",
        method: FrontendHttpMethod::Post,
        path_template: WORKFLOW_ACTIVATE_PATH,
        request_type: "ActivateWorkflowRequest",
        response_type: "ActivateWorkflowResponse",
        path_params: WORKFLOW_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "listVersions",
        namespace: NAMESPACE,
        member_name: "listVersions",
        method: FrontendHttpMethod::Get,
        path_template: WORKFLOW_VERSIONS_PATH,
        request_type: "ListVersionsRequest",
        response_type: "ListVersionsResponse",
        path_params: WORKFLOW_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "getVersion",
        namespace: NAMESPACE,
        member_name: "getVersion",
        method: FrontendHttpMethod::Get,
        path_template: WORKFLOW_VERSION_PATH,
        request_type: "GetVersionRequest",
        response_type: "GetVersionResponse",
        path_params: WORKFLOW_VERSION_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "deleteSnapshot",
        namespace: NAMESPACE,
        member_name: "deleteSnapshot",
        method: FrontendHttpMethod::Delete,
        path_template: WORKFLOW_VERSION_PATH,
        request_type: "DeleteSnapshotRequest",
        response_type: "DeleteSnapshotResponse",
        path_params: WORKFLOW_VERSION_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "getWorkflowSnapshot",
        namespace: NAMESPACE,
        member_name: "getSnapshot",
        method: FrontendHttpMethod::Get,
        path_template: WORKFLOW_SNAPSHOT_PATH,
        request_type: "GetWorkflowSnapshotRequest",
        response_type: "GetWorkflowSnapshotResponse",
        path_params: WORKFLOW_SNAPSHOT_PATH_PARAMS,
        has_json_body: false,
    },
];
