[package]
name = "ora-scheduler"
version.workspace = true
edition.workspace = true

[lib]
name = "ora_scheduler"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
ora-logging = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
cron = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "test-util", "time"] }
