// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent } from "./agent.js";

export type AgentImportCandidate = {
  name: string;
  description: string;
  status: AgentImportCandidateStatus;
  existingAgent: AgentImportConflictInfo | null;
};

export type AgentImportCandidateStatus = "ready" | "conflict";

export type AgentImportConflictInfo = {
  agentId: string;
  updatedAt: number;
  description: string;
};

export type AgentImportDecision = "skip" | "overwrite";

export type AgentImportResultStatus =
  | "imported"
  | "overwritten"
  | "skipped"
  | "stale_conflict";

export type CommitAgentImportRequest = {
  content: string;
  decision: AgentImportDecision | null;
  expectedAgentId: string | null;
  expectedUpdatedAt: number | null;
};

export type CommitAgentImportResponse = {
  status: AgentImportResultStatus;
  agent: Agent | null;
};

export type PrepareAgentImportRequest = { content: string };

export type PrepareAgentImportResponse = { candidate: AgentImportCandidate };
