// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes an application-level invalidation or stream lifecycle event.
 */
export type AppEvent = { "type": "ready" } | {
  "type": "session_title_updated";
  session_id: string;
};

/**
 * Opens the application event stream without filtering or ownership metadata.
 */
export type WatchAppEventsRequest = Record<symbol, never>;
