// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the authoritative shared developer-mode preference.
 */
export type DeveloperModeResponse = { enabled: boolean };

/**
 * Requests the shared developer-mode preference without additional parameters.
 */
export type GetDeveloperModeRequest = Record<symbol, never>;

/**
 * Requests a new shared developer-mode preference.
 */
export type SetDeveloperModeRequest = { enabled: boolean };
