// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import type { CreateAgentRequest, CreateAgentResponse, DeleteAgentRequest, DeleteAgentResponse, GetAgentRequest, GetAgentResponse, ListAgentsRequest, ListAgentsResponse, UpdateAgentRequest, UpdateAgentResponse } from "./agent.js";
import type { CommitAgentImportRequest, CommitAgentImportResponse, PrepareAgentImportRequest, PrepareAgentImportResponse } from "./agent-import.js";
import type { AppEvent, WatchAppEventsRequest } from "./app_event.js";
import type { DeveloperModeResponse, GetDeveloperModeRequest, SetDeveloperModeRequest } from "./developerMode.js";
import type { ListWorkspaceDirectoryRequest, ListWorkspaceDirectoryResponse, ReadWorkspaceFileRequest, ReadWorkspaceFileResponse, SearchWorkspaceRequest, SearchWorkspaceResponse, WatchWorkspaceRequest, WorkspaceFileEventBatch } from "./file-system.js";
import type { GetGitIdentityRequest, GitIdentityResponse } from "./git.js";
import type { ListInstalledPluginsRequest, ListInstalledPluginsResponse } from "./plugin.js";
import type { CreateProjectRequest, CreateProjectResponse, DeleteProjectRequest, DeleteProjectResponse, GetProjectRequest, GetProjectResponse, ListProjectBranchesRequest, ListProjectBranchesResponse, ListProjectsRequest, ListProjectsResponse, UpdateProjectRequest, UpdateProjectResponse } from "./project.js";
import type { GetRuntimeLogLevelRequest, RuntimeLogLevelStateResponse, SetRuntimeLogLevelRequest } from "./runtimeLogLevel.js";
import type { AttachSessionRequest, AttachSessionResponse, DeleteSessionRequest, DeleteSessionResponse, GetAgentRuntimeStatusRequest, GetAgentRuntimeStatusResponse, GetSessionRequest, GetSessionResponse, ListSessionsRequest, ListSessionsResponse, LoadSessionEvent, LoadSessionRequest, PromptSessionEvent, PromptSessionRequest, RenameSessionRequest, RenameSessionResponse, RespondToPermissionRequest, RespondToPermissionResponse, ResumeSessionHistoryRequest, ResumeSessionHistoryResponse, SetSessionConfigRequest, SetSessionConfigResponse, StopSessionRequest, StopSessionResponse, SwitchSessionAgentRequest, SwitchSessionAgentResponse, WarmSessionRequest, WarmSessionResponse } from "./session.js";
import type { CreateSkillRequest, CreateSkillResponse, DeleteSkillRequest, DeleteSkillResponse, GetSkillRequest, GetSkillResponse, ListSkillsRequest, ListSkillsResponse, UpdateSkillRequest, UpdateSkillResponse } from "./skill.js";
import type { CancelSkillImportRequest, CancelSkillImportResponse, CommitSkillImportRequest, CommitSkillImportResponse, GetSkillImportSessionRequest, GetSkillImportSessionResponse, PrepareSkillImportRequest, PrepareSkillImportResponse } from "./skill-import.js";
import type { GetSpecCatalogRequest, ReadSpecRequest, ReadSpecResponse, SpecCatalogResponse, WatchSpecsRequest } from "./spec.js";
import type { CreateTaskRequest, CreateTaskResponse, DeleteTaskRequest, DeleteTaskResponse, GetTaskRequest, GetTaskResponse, GetTaskWorkspaceRequest, GetTaskWorkspaceResponse, ListTasksRequest, ListTasksResponse, UpdateTaskRequest, UpdateTaskResponse } from "./task.js";
import type { CommitTaskChangesRequest, CommitTaskChangesResponse, CreateTaskDiffCommentRequest, CreateTaskDiffCommentResponse, GetTaskDiffRequest, GetTaskDiffResponse, ListTaskDiffCommentsRequest, ListTaskDiffCommentsResponse, PushTaskBranchRequest, PushTaskBranchResponse, ReplyTaskDiffCommentRequest, ReplyTaskDiffCommentResponse, SetTaskDiffCommentStatusRequest, SetTaskDiffCommentStatusResponse } from "./task_diff.js";
import type { ActivateWorkflowRequest, ActivateWorkflowResponse, CreateWorkflowRequest, CreateWorkflowResponse, DeleteSnapshotRequest, DeleteSnapshotResponse, DeleteWorkflowRequest, DeleteWorkflowResponse, GetDraftRequest, GetDraftResponse, GetVersionRequest, GetVersionResponse, GetWorkflowRequest, GetWorkflowResponse, GetWorkflowSnapshotRequest, GetWorkflowSnapshotResponse, ListVersionsRequest, ListVersionsResponse, ListWorkflowsRequest, ListWorkflowsResponse, PublishWorkflowRequest, PublishWorkflowResponse, RollbackWorkflowRequest, RollbackWorkflowResponse, UpdateDraftRequest, UpdateDraftResponse, UpdateWorkflowRequest, UpdateWorkflowResponse } from "./workflow.js";
import type { CancelWorkflowRunRequest, CancelWorkflowRunResponse, CreateWorkflowRunRequest, CreateWorkflowRunResponse, DeleteWorkflowRunRequest, DeleteWorkflowRunResponse, GetWorkflowRunRequest, GetWorkflowRunResponse, ListWorkflowNodeRunsRequest, ListWorkflowNodeRunsResponse, ListWorkflowRunsByWorkflowRequest, ListWorkflowRunsByWorkflowResponse, ListWorkflowRunsRequest, ListWorkflowRunsResponse, RestartWorkflowRunRequest, RestartWorkflowRunResponse, StartWorkflowRunRequest, StartWorkflowRunResponse, UpdateWorkflowRunInputRequest, UpdateWorkflowRunInputResponse } from "./workflowRun.js";
export type FrontendEndpointDefinition = {
  operationName: string;
  namespace: string;
  memberName: string;
  requestType: string;
  responseType: string;
  responseMode: "unary" | "stream";
};

export type RequestByOperation = {
  createProject: CreateProjectRequest;
  getProject: GetProjectRequest;
  listProjects: ListProjectsRequest;
  listProjectBranches: ListProjectBranchesRequest;
  updateProject: UpdateProjectRequest;
  deleteProject: DeleteProjectRequest;
  getDeveloperMode: GetDeveloperModeRequest;
  setDeveloperMode: SetDeveloperModeRequest;
  getRuntimeLogLevel: GetRuntimeLogLevelRequest;
  setRuntimeLogLevel: SetRuntimeLogLevelRequest;
  createTask: CreateTaskRequest;
  getTask: GetTaskRequest;
  listTasks: ListTasksRequest;
  updateTask: UpdateTaskRequest;
  deleteTask: DeleteTaskRequest;
  getTaskWorkspace: GetTaskWorkspaceRequest;
  getTaskDiff: GetTaskDiffRequest;
  commitTaskChanges: CommitTaskChangesRequest;
  pushTaskBranch: PushTaskBranchRequest;
  listTaskDiffComments: ListTaskDiffCommentsRequest;
  createTaskDiffComment: CreateTaskDiffCommentRequest;
  replyTaskDiffComment: ReplyTaskDiffCommentRequest;
  setTaskDiffCommentStatus: SetTaskDiffCommentStatusRequest;
  warmSession: WarmSessionRequest;
  setSessionConfig: SetSessionConfigRequest;
  attachSession: AttachSessionRequest;
  getSession: GetSessionRequest;
  listSessions: ListSessionsRequest;
  loadSession: LoadSessionRequest;
  promptSession: PromptSessionRequest;
  respondToSessionPermission: RespondToPermissionRequest;
  stopSession: StopSessionRequest;
  switchSessionAgent: SwitchSessionAgentRequest;
  resumeSessionHistory: ResumeSessionHistoryRequest;
  deleteSession: DeleteSessionRequest;
  renameSession: RenameSessionRequest;
  getAgentRuntimeStatus: GetAgentRuntimeStatusRequest;
  watchAppEvents: WatchAppEventsRequest;
  createSkill: CreateSkillRequest;
  getSkill: GetSkillRequest;
  listSkills: ListSkillsRequest;
  updateSkill: UpdateSkillRequest;
  deleteSkill: DeleteSkillRequest;
  prepareSkillImport: PrepareSkillImportRequest;
  getSkillImport: GetSkillImportSessionRequest;
  commitSkillImport: CommitSkillImportRequest;
  cancelSkillImport: CancelSkillImportRequest;
  createAgent: CreateAgentRequest;
  getAgent: GetAgentRequest;
  listAgents: ListAgentsRequest;
  updateAgent: UpdateAgentRequest;
  deleteAgent: DeleteAgentRequest;
  prepareAgentImport: PrepareAgentImportRequest;
  commitAgentImport: CommitAgentImportRequest;
  listInstalledPlugins: ListInstalledPluginsRequest;
  listWorkspaceDirectory: ListWorkspaceDirectoryRequest;
  readWorkspaceFile: ReadWorkspaceFileRequest;
  searchWorkspace: SearchWorkspaceRequest;
  watchWorkspace: WatchWorkspaceRequest;
  getGitIdentity: GetGitIdentityRequest;
  getSpecCatalog: GetSpecCatalogRequest;
  readSpec: ReadSpecRequest;
  watchSpecs: WatchSpecsRequest;
  createWorkflow: CreateWorkflowRequest;
  getWorkflow: GetWorkflowRequest;
  listWorkflows: ListWorkflowsRequest;
  updateWorkflow: UpdateWorkflowRequest;
  deleteWorkflow: DeleteWorkflowRequest;
  getDraft: GetDraftRequest;
  updateDraft: UpdateDraftRequest;
  publishWorkflow: PublishWorkflowRequest;
  rollbackWorkflow: RollbackWorkflowRequest;
  activateWorkflow: ActivateWorkflowRequest;
  listVersions: ListVersionsRequest;
  getVersion: GetVersionRequest;
  deleteSnapshot: DeleteSnapshotRequest;
  getWorkflowSnapshot: GetWorkflowSnapshotRequest;
  createWorkflowRun: CreateWorkflowRunRequest;
  getWorkflowRun: GetWorkflowRunRequest;
  listWorkflowRuns: ListWorkflowRunsRequest;
  listWorkflowRunsByWorkflow: ListWorkflowRunsByWorkflowRequest;
  listWorkflowNodeRuns: ListWorkflowNodeRunsRequest;
  deleteWorkflowRun: DeleteWorkflowRunRequest;
  startWorkflowRun: StartWorkflowRunRequest;
  cancelWorkflowRun: CancelWorkflowRunRequest;
  restartWorkflowRun: RestartWorkflowRunRequest;
  updateWorkflowRunInput: UpdateWorkflowRunInputRequest;
};

export type ResponseByOperation = {
  createProject: CreateProjectResponse;
  getProject: GetProjectResponse;
  listProjects: ListProjectsResponse;
  listProjectBranches: ListProjectBranchesResponse;
  updateProject: UpdateProjectResponse;
  deleteProject: DeleteProjectResponse;
  getDeveloperMode: DeveloperModeResponse;
  setDeveloperMode: DeveloperModeResponse;
  getRuntimeLogLevel: RuntimeLogLevelStateResponse;
  setRuntimeLogLevel: RuntimeLogLevelStateResponse;
  createTask: CreateTaskResponse;
  getTask: GetTaskResponse;
  listTasks: ListTasksResponse;
  updateTask: UpdateTaskResponse;
  deleteTask: DeleteTaskResponse;
  getTaskWorkspace: GetTaskWorkspaceResponse;
  getTaskDiff: GetTaskDiffResponse;
  commitTaskChanges: CommitTaskChangesResponse;
  pushTaskBranch: PushTaskBranchResponse;
  listTaskDiffComments: ListTaskDiffCommentsResponse;
  createTaskDiffComment: CreateTaskDiffCommentResponse;
  replyTaskDiffComment: ReplyTaskDiffCommentResponse;
  setTaskDiffCommentStatus: SetTaskDiffCommentStatusResponse;
  warmSession: WarmSessionResponse;
  setSessionConfig: SetSessionConfigResponse;
  attachSession: AttachSessionResponse;
  getSession: GetSessionResponse;
  listSessions: ListSessionsResponse;
  loadSession: LoadSessionEvent;
  promptSession: PromptSessionEvent;
  respondToSessionPermission: RespondToPermissionResponse;
  stopSession: StopSessionResponse;
  switchSessionAgent: SwitchSessionAgentResponse;
  resumeSessionHistory: ResumeSessionHistoryResponse;
  deleteSession: DeleteSessionResponse;
  renameSession: RenameSessionResponse;
  getAgentRuntimeStatus: GetAgentRuntimeStatusResponse;
  watchAppEvents: AppEvent;
  createSkill: CreateSkillResponse;
  getSkill: GetSkillResponse;
  listSkills: ListSkillsResponse;
  updateSkill: UpdateSkillResponse;
  deleteSkill: DeleteSkillResponse;
  prepareSkillImport: PrepareSkillImportResponse;
  getSkillImport: GetSkillImportSessionResponse;
  commitSkillImport: CommitSkillImportResponse;
  cancelSkillImport: CancelSkillImportResponse;
  createAgent: CreateAgentResponse;
  getAgent: GetAgentResponse;
  listAgents: ListAgentsResponse;
  updateAgent: UpdateAgentResponse;
  deleteAgent: DeleteAgentResponse;
  prepareAgentImport: PrepareAgentImportResponse;
  commitAgentImport: CommitAgentImportResponse;
  listInstalledPlugins: ListInstalledPluginsResponse;
  listWorkspaceDirectory: ListWorkspaceDirectoryResponse;
  readWorkspaceFile: ReadWorkspaceFileResponse;
  searchWorkspace: SearchWorkspaceResponse;
  watchWorkspace: WorkspaceFileEventBatch;
  getGitIdentity: GitIdentityResponse;
  getSpecCatalog: SpecCatalogResponse;
  readSpec: ReadSpecResponse;
  watchSpecs: WorkspaceFileEventBatch;
  createWorkflow: CreateWorkflowResponse;
  getWorkflow: GetWorkflowResponse;
  listWorkflows: ListWorkflowsResponse;
  updateWorkflow: UpdateWorkflowResponse;
  deleteWorkflow: DeleteWorkflowResponse;
  getDraft: GetDraftResponse;
  updateDraft: UpdateDraftResponse;
  publishWorkflow: PublishWorkflowResponse;
  rollbackWorkflow: RollbackWorkflowResponse;
  activateWorkflow: ActivateWorkflowResponse;
  listVersions: ListVersionsResponse;
  getVersion: GetVersionResponse;
  deleteSnapshot: DeleteSnapshotResponse;
  getWorkflowSnapshot: GetWorkflowSnapshotResponse;
  createWorkflowRun: CreateWorkflowRunResponse;
  getWorkflowRun: GetWorkflowRunResponse;
  listWorkflowRuns: ListWorkflowRunsResponse;
  listWorkflowRunsByWorkflow: ListWorkflowRunsByWorkflowResponse;
  listWorkflowNodeRuns: ListWorkflowNodeRunsResponse;
  deleteWorkflowRun: DeleteWorkflowRunResponse;
  startWorkflowRun: StartWorkflowRunResponse;
  cancelWorkflowRun: CancelWorkflowRunResponse;
  restartWorkflowRun: RestartWorkflowRunResponse;
  updateWorkflowRunInput: UpdateWorkflowRunInputResponse;
};

export type EndpointOperation = keyof RequestByOperation;

export const endpoints = {
  createProject: {
    operationName: "createProject",
    namespace: "project",
    memberName: "create",
    requestType: "CreateProjectRequest",
    responseType: "CreateProjectResponse",
    responseMode: "unary",
  },
  getProject: {
    operationName: "getProject",
    namespace: "project",
    memberName: "get",
    requestType: "GetProjectRequest",
    responseType: "GetProjectResponse",
    responseMode: "unary",
  },
  listProjects: {
    operationName: "listProjects",
    namespace: "project",
    memberName: "list",
    requestType: "ListProjectsRequest",
    responseType: "ListProjectsResponse",
    responseMode: "unary",
  },
  listProjectBranches: {
    operationName: "listProjectBranches",
    namespace: "project",
    memberName: "listBranches",
    requestType: "ListProjectBranchesRequest",
    responseType: "ListProjectBranchesResponse",
    responseMode: "unary",
  },
  updateProject: {
    operationName: "updateProject",
    namespace: "project",
    memberName: "update",
    requestType: "UpdateProjectRequest",
    responseType: "UpdateProjectResponse",
    responseMode: "unary",
  },
  deleteProject: {
    operationName: "deleteProject",
    namespace: "project",
    memberName: "delete",
    requestType: "DeleteProjectRequest",
    responseType: "DeleteProjectResponse",
    responseMode: "unary",
  },
  getDeveloperMode: {
    operationName: "getDeveloperMode",
    namespace: "developerMode",
    memberName: "get",
    requestType: "GetDeveloperModeRequest",
    responseType: "DeveloperModeResponse",
    responseMode: "unary",
  },
  setDeveloperMode: {
    operationName: "setDeveloperMode",
    namespace: "developerMode",
    memberName: "set",
    requestType: "SetDeveloperModeRequest",
    responseType: "DeveloperModeResponse",
    responseMode: "unary",
  },
  getRuntimeLogLevel: {
    operationName: "getRuntimeLogLevel",
    namespace: "runtimeLogLevel",
    memberName: "get",
    requestType: "GetRuntimeLogLevelRequest",
    responseType: "RuntimeLogLevelStateResponse",
    responseMode: "unary",
  },
  setRuntimeLogLevel: {
    operationName: "setRuntimeLogLevel",
    namespace: "runtimeLogLevel",
    memberName: "set",
    requestType: "SetRuntimeLogLevelRequest",
    responseType: "RuntimeLogLevelStateResponse",
    responseMode: "unary",
  },
  createTask: {
    operationName: "createTask",
    namespace: "task",
    memberName: "create",
    requestType: "CreateTaskRequest",
    responseType: "CreateTaskResponse",
    responseMode: "unary",
  },
  getTask: {
    operationName: "getTask",
    namespace: "task",
    memberName: "get",
    requestType: "GetTaskRequest",
    responseType: "GetTaskResponse",
    responseMode: "unary",
  },
  listTasks: {
    operationName: "listTasks",
    namespace: "task",
    memberName: "list",
    requestType: "ListTasksRequest",
    responseType: "ListTasksResponse",
    responseMode: "unary",
  },
  updateTask: {
    operationName: "updateTask",
    namespace: "task",
    memberName: "update",
    requestType: "UpdateTaskRequest",
    responseType: "UpdateTaskResponse",
    responseMode: "unary",
  },
  deleteTask: {
    operationName: "deleteTask",
    namespace: "task",
    memberName: "delete",
    requestType: "DeleteTaskRequest",
    responseType: "DeleteTaskResponse",
    responseMode: "unary",
  },
  getTaskWorkspace: {
    operationName: "getTaskWorkspace",
    namespace: "task",
    memberName: "getWorkspace",
    requestType: "GetTaskWorkspaceRequest",
    responseType: "GetTaskWorkspaceResponse",
    responseMode: "unary",
  },
  getTaskDiff: {
    operationName: "getTaskDiff",
    namespace: "task",
    memberName: "getDiff",
    requestType: "GetTaskDiffRequest",
    responseType: "GetTaskDiffResponse",
    responseMode: "unary",
  },
  commitTaskChanges: {
    operationName: "commitTaskChanges",
    namespace: "task",
    memberName: "commitChanges",
    requestType: "CommitTaskChangesRequest",
    responseType: "CommitTaskChangesResponse",
    responseMode: "unary",
  },
  pushTaskBranch: {
    operationName: "pushTaskBranch",
    namespace: "task",
    memberName: "pushBranch",
    requestType: "PushTaskBranchRequest",
    responseType: "PushTaskBranchResponse",
    responseMode: "unary",
  },
  listTaskDiffComments: {
    operationName: "listTaskDiffComments",
    namespace: "task",
    memberName: "listDiffComments",
    requestType: "ListTaskDiffCommentsRequest",
    responseType: "ListTaskDiffCommentsResponse",
    responseMode: "unary",
  },
  createTaskDiffComment: {
    operationName: "createTaskDiffComment",
    namespace: "task",
    memberName: "createDiffComment",
    requestType: "CreateTaskDiffCommentRequest",
    responseType: "CreateTaskDiffCommentResponse",
    responseMode: "unary",
  },
  replyTaskDiffComment: {
    operationName: "replyTaskDiffComment",
    namespace: "task",
    memberName: "replyDiffComment",
    requestType: "ReplyTaskDiffCommentRequest",
    responseType: "ReplyTaskDiffCommentResponse",
    responseMode: "unary",
  },
  setTaskDiffCommentStatus: {
    operationName: "setTaskDiffCommentStatus",
    namespace: "task",
    memberName: "setDiffCommentStatus",
    requestType: "SetTaskDiffCommentStatusRequest",
    responseType: "SetTaskDiffCommentStatusResponse",
    responseMode: "unary",
  },
  warmSession: {
    operationName: "warmSession",
    namespace: "session",
    memberName: "warm",
    requestType: "WarmSessionRequest",
    responseType: "WarmSessionResponse",
    responseMode: "unary",
  },
  setSessionConfig: {
    operationName: "setSessionConfig",
    namespace: "session",
    memberName: "setConfig",
    requestType: "SetSessionConfigRequest",
    responseType: "SetSessionConfigResponse",
    responseMode: "unary",
  },
  attachSession: {
    operationName: "attachSession",
    namespace: "session",
    memberName: "attach",
    requestType: "AttachSessionRequest",
    responseType: "AttachSessionResponse",
    responseMode: "unary",
  },
  getSession: {
    operationName: "getSession",
    namespace: "session",
    memberName: "get",
    requestType: "GetSessionRequest",
    responseType: "GetSessionResponse",
    responseMode: "unary",
  },
  listSessions: {
    operationName: "listSessions",
    namespace: "session",
    memberName: "list",
    requestType: "ListSessionsRequest",
    responseType: "ListSessionsResponse",
    responseMode: "unary",
  },
  loadSession: {
    operationName: "loadSession",
    namespace: "session",
    memberName: "load",
    requestType: "LoadSessionRequest",
    responseType: "LoadSessionEvent",
    responseMode: "stream",
  },
  promptSession: {
    operationName: "promptSession",
    namespace: "session",
    memberName: "prompt",
    requestType: "PromptSessionRequest",
    responseType: "PromptSessionEvent",
    responseMode: "stream",
  },
  respondToSessionPermission: {
    operationName: "respondToSessionPermission",
    namespace: "session",
    memberName: "respondToPermission",
    requestType: "RespondToPermissionRequest",
    responseType: "RespondToPermissionResponse",
    responseMode: "unary",
  },
  stopSession: {
    operationName: "stopSession",
    namespace: "session",
    memberName: "stop",
    requestType: "StopSessionRequest",
    responseType: "StopSessionResponse",
    responseMode: "unary",
  },
  switchSessionAgent: {
    operationName: "switchSessionAgent",
    namespace: "session",
    memberName: "switchAgent",
    requestType: "SwitchSessionAgentRequest",
    responseType: "SwitchSessionAgentResponse",
    responseMode: "unary",
  },
  resumeSessionHistory: {
    operationName: "resumeSessionHistory",
    namespace: "session",
    memberName: "resumeHistory",
    requestType: "ResumeSessionHistoryRequest",
    responseType: "ResumeSessionHistoryResponse",
    responseMode: "unary",
  },
  deleteSession: {
    operationName: "deleteSession",
    namespace: "session",
    memberName: "delete",
    requestType: "DeleteSessionRequest",
    responseType: "DeleteSessionResponse",
    responseMode: "unary",
  },
  renameSession: {
    operationName: "renameSession",
    namespace: "session",
    memberName: "rename",
    requestType: "RenameSessionRequest",
    responseType: "RenameSessionResponse",
    responseMode: "unary",
  },
  getAgentRuntimeStatus: {
    operationName: "getAgentRuntimeStatus",
    namespace: "agentRuntime",
    memberName: "getStatus",
    requestType: "GetAgentRuntimeStatusRequest",
    responseType: "GetAgentRuntimeStatusResponse",
    responseMode: "unary",
  },
  watchAppEvents: {
    operationName: "watchAppEvents",
    namespace: "appEvents",
    memberName: "watch",
    requestType: "WatchAppEventsRequest",
    responseType: "AppEvent",
    responseMode: "stream",
  },
  createSkill: {
    operationName: "createSkill",
    namespace: "skill",
    memberName: "create",
    requestType: "CreateSkillRequest",
    responseType: "CreateSkillResponse",
    responseMode: "unary",
  },
  getSkill: {
    operationName: "getSkill",
    namespace: "skill",
    memberName: "get",
    requestType: "GetSkillRequest",
    responseType: "GetSkillResponse",
    responseMode: "unary",
  },
  listSkills: {
    operationName: "listSkills",
    namespace: "skill",
    memberName: "list",
    requestType: "ListSkillsRequest",
    responseType: "ListSkillsResponse",
    responseMode: "unary",
  },
  updateSkill: {
    operationName: "updateSkill",
    namespace: "skill",
    memberName: "update",
    requestType: "UpdateSkillRequest",
    responseType: "UpdateSkillResponse",
    responseMode: "unary",
  },
  deleteSkill: {
    operationName: "deleteSkill",
    namespace: "skill",
    memberName: "delete",
    requestType: "DeleteSkillRequest",
    responseType: "DeleteSkillResponse",
    responseMode: "unary",
  },
  prepareSkillImport: {
    operationName: "prepareSkillImport",
    namespace: "skillImport",
    memberName: "prepare",
    requestType: "PrepareSkillImportRequest",
    responseType: "PrepareSkillImportResponse",
    responseMode: "unary",
  },
  getSkillImport: {
    operationName: "getSkillImport",
    namespace: "skillImport",
    memberName: "get",
    requestType: "GetSkillImportSessionRequest",
    responseType: "GetSkillImportSessionResponse",
    responseMode: "unary",
  },
  commitSkillImport: {
    operationName: "commitSkillImport",
    namespace: "skillImport",
    memberName: "commit",
    requestType: "CommitSkillImportRequest",
    responseType: "CommitSkillImportResponse",
    responseMode: "unary",
  },
  cancelSkillImport: {
    operationName: "cancelSkillImport",
    namespace: "skillImport",
    memberName: "cancel",
    requestType: "CancelSkillImportRequest",
    responseType: "CancelSkillImportResponse",
    responseMode: "unary",
  },
  createAgent: {
    operationName: "createAgent",
    namespace: "agent",
    memberName: "create",
    requestType: "CreateAgentRequest",
    responseType: "CreateAgentResponse",
    responseMode: "unary",
  },
  getAgent: {
    operationName: "getAgent",
    namespace: "agent",
    memberName: "get",
    requestType: "GetAgentRequest",
    responseType: "GetAgentResponse",
    responseMode: "unary",
  },
  listAgents: {
    operationName: "listAgents",
    namespace: "agent",
    memberName: "list",
    requestType: "ListAgentsRequest",
    responseType: "ListAgentsResponse",
    responseMode: "unary",
  },
  updateAgent: {
    operationName: "updateAgent",
    namespace: "agent",
    memberName: "update",
    requestType: "UpdateAgentRequest",
    responseType: "UpdateAgentResponse",
    responseMode: "unary",
  },
  deleteAgent: {
    operationName: "deleteAgent",
    namespace: "agent",
    memberName: "delete",
    requestType: "DeleteAgentRequest",
    responseType: "DeleteAgentResponse",
    responseMode: "unary",
  },
  prepareAgentImport: {
    operationName: "prepareAgentImport",
    namespace: "agentImport",
    memberName: "prepare",
    requestType: "PrepareAgentImportRequest",
    responseType: "PrepareAgentImportResponse",
    responseMode: "unary",
  },
  commitAgentImport: {
    operationName: "commitAgentImport",
    namespace: "agentImport",
    memberName: "commit",
    requestType: "CommitAgentImportRequest",
    responseType: "CommitAgentImportResponse",
    responseMode: "unary",
  },
  listInstalledPlugins: {
    operationName: "listInstalledPlugins",
    namespace: "plugin",
    memberName: "listInstalled",
    requestType: "ListInstalledPluginsRequest",
    responseType: "ListInstalledPluginsResponse",
    responseMode: "unary",
  },
  listWorkspaceDirectory: {
    operationName: "listWorkspaceDirectory",
    namespace: "fileSystem",
    memberName: "listWorkspaceDirectory",
    requestType: "ListWorkspaceDirectoryRequest",
    responseType: "ListWorkspaceDirectoryResponse",
    responseMode: "unary",
  },
  readWorkspaceFile: {
    operationName: "readWorkspaceFile",
    namespace: "fileSystem",
    memberName: "readWorkspaceFile",
    requestType: "ReadWorkspaceFileRequest",
    responseType: "ReadWorkspaceFileResponse",
    responseMode: "unary",
  },
  searchWorkspace: {
    operationName: "searchWorkspace",
    namespace: "fileSystem",
    memberName: "searchWorkspace",
    requestType: "SearchWorkspaceRequest",
    responseType: "SearchWorkspaceResponse",
    responseMode: "unary",
  },
  watchWorkspace: {
    operationName: "watchWorkspace",
    namespace: "fileSystem",
    memberName: "watchWorkspace",
    requestType: "WatchWorkspaceRequest",
    responseType: "WorkspaceFileEventBatch",
    responseMode: "stream",
  },
  getGitIdentity: {
    operationName: "getGitIdentity",
    namespace: "gitIdentity",
    memberName: "get",
    requestType: "GetGitIdentityRequest",
    responseType: "GitIdentityResponse",
    responseMode: "unary",
  },
  getSpecCatalog: {
    operationName: "getSpecCatalog",
    namespace: "spec",
    memberName: "catalog",
    requestType: "GetSpecCatalogRequest",
    responseType: "SpecCatalogResponse",
    responseMode: "unary",
  },
  readSpec: {
    operationName: "readSpec",
    namespace: "spec",
    memberName: "read",
    requestType: "ReadSpecRequest",
    responseType: "ReadSpecResponse",
    responseMode: "unary",
  },
  watchSpecs: {
    operationName: "watchSpecs",
    namespace: "spec",
    memberName: "watch",
    requestType: "WatchSpecsRequest",
    responseType: "WorkspaceFileEventBatch",
    responseMode: "stream",
  },
  createWorkflow: {
    operationName: "createWorkflow",
    namespace: "workflow",
    memberName: "create",
    requestType: "CreateWorkflowRequest",
    responseType: "CreateWorkflowResponse",
    responseMode: "unary",
  },
  getWorkflow: {
    operationName: "getWorkflow",
    namespace: "workflow",
    memberName: "get",
    requestType: "GetWorkflowRequest",
    responseType: "GetWorkflowResponse",
    responseMode: "unary",
  },
  listWorkflows: {
    operationName: "listWorkflows",
    namespace: "workflow",
    memberName: "list",
    requestType: "ListWorkflowsRequest",
    responseType: "ListWorkflowsResponse",
    responseMode: "unary",
  },
  updateWorkflow: {
    operationName: "updateWorkflow",
    namespace: "workflow",
    memberName: "update",
    requestType: "UpdateWorkflowRequest",
    responseType: "UpdateWorkflowResponse",
    responseMode: "unary",
  },
  deleteWorkflow: {
    operationName: "deleteWorkflow",
    namespace: "workflow",
    memberName: "delete",
    requestType: "DeleteWorkflowRequest",
    responseType: "DeleteWorkflowResponse",
    responseMode: "unary",
  },
  getDraft: {
    operationName: "getDraft",
    namespace: "workflow",
    memberName: "getDraft",
    requestType: "GetDraftRequest",
    responseType: "GetDraftResponse",
    responseMode: "unary",
  },
  updateDraft: {
    operationName: "updateDraft",
    namespace: "workflow",
    memberName: "updateDraft",
    requestType: "UpdateDraftRequest",
    responseType: "UpdateDraftResponse",
    responseMode: "unary",
  },
  publishWorkflow: {
    operationName: "publishWorkflow",
    namespace: "workflow",
    memberName: "publish",
    requestType: "PublishWorkflowRequest",
    responseType: "PublishWorkflowResponse",
    responseMode: "unary",
  },
  rollbackWorkflow: {
    operationName: "rollbackWorkflow",
    namespace: "workflow",
    memberName: "rollback",
    requestType: "RollbackWorkflowRequest",
    responseType: "RollbackWorkflowResponse",
    responseMode: "unary",
  },
  activateWorkflow: {
    operationName: "activateWorkflow",
    namespace: "workflow",
    memberName: "activate",
    requestType: "ActivateWorkflowRequest",
    responseType: "ActivateWorkflowResponse",
    responseMode: "unary",
  },
  listVersions: {
    operationName: "listVersions",
    namespace: "workflow",
    memberName: "listVersions",
    requestType: "ListVersionsRequest",
    responseType: "ListVersionsResponse",
    responseMode: "unary",
  },
  getVersion: {
    operationName: "getVersion",
    namespace: "workflow",
    memberName: "getVersion",
    requestType: "GetVersionRequest",
    responseType: "GetVersionResponse",
    responseMode: "unary",
  },
  deleteSnapshot: {
    operationName: "deleteSnapshot",
    namespace: "workflow",
    memberName: "deleteSnapshot",
    requestType: "DeleteSnapshotRequest",
    responseType: "DeleteSnapshotResponse",
    responseMode: "unary",
  },
  getWorkflowSnapshot: {
    operationName: "getWorkflowSnapshot",
    namespace: "workflow",
    memberName: "getSnapshot",
    requestType: "GetWorkflowSnapshotRequest",
    responseType: "GetWorkflowSnapshotResponse",
    responseMode: "unary",
  },
  createWorkflowRun: {
    operationName: "createWorkflowRun",
    namespace: "workflowRun",
    memberName: "create",
    requestType: "CreateWorkflowRunRequest",
    responseType: "CreateWorkflowRunResponse",
    responseMode: "unary",
  },
  getWorkflowRun: {
    operationName: "getWorkflowRun",
    namespace: "workflowRun",
    memberName: "get",
    requestType: "GetWorkflowRunRequest",
    responseType: "GetWorkflowRunResponse",
    responseMode: "unary",
  },
  listWorkflowRuns: {
    operationName: "listWorkflowRuns",
    namespace: "workflowRun",
    memberName: "list",
    requestType: "ListWorkflowRunsRequest",
    responseType: "ListWorkflowRunsResponse",
    responseMode: "unary",
  },
  listWorkflowRunsByWorkflow: {
    operationName: "listWorkflowRunsByWorkflow",
    namespace: "workflowRun",
    memberName: "listByWorkflow",
    requestType: "ListWorkflowRunsByWorkflowRequest",
    responseType: "ListWorkflowRunsByWorkflowResponse",
    responseMode: "unary",
  },
  listWorkflowNodeRuns: {
    operationName: "listWorkflowNodeRuns",
    namespace: "workflowRun",
    memberName: "listNodeRuns",
    requestType: "ListWorkflowNodeRunsRequest",
    responseType: "ListWorkflowNodeRunsResponse",
    responseMode: "unary",
  },
  deleteWorkflowRun: {
    operationName: "deleteWorkflowRun",
    namespace: "workflowRun",
    memberName: "delete",
    requestType: "DeleteWorkflowRunRequest",
    responseType: "DeleteWorkflowRunResponse",
    responseMode: "unary",
  },
  startWorkflowRun: {
    operationName: "startWorkflowRun",
    namespace: "workflowRun",
    memberName: "start",
    requestType: "StartWorkflowRunRequest",
    responseType: "StartWorkflowRunResponse",
    responseMode: "unary",
  },
  cancelWorkflowRun: {
    operationName: "cancelWorkflowRun",
    namespace: "workflowRun",
    memberName: "cancel",
    requestType: "CancelWorkflowRunRequest",
    responseType: "CancelWorkflowRunResponse",
    responseMode: "unary",
  },
  restartWorkflowRun: {
    operationName: "restartWorkflowRun",
    namespace: "workflowRun",
    memberName: "restart",
    requestType: "RestartWorkflowRunRequest",
    responseType: "RestartWorkflowRunResponse",
    responseMode: "unary",
  },
  updateWorkflowRunInput: {
    operationName: "updateWorkflowRunInput",
    namespace: "workflowRun",
    memberName: "updateInput",
    requestType: "UpdateWorkflowRunInputRequest",
    responseType: "UpdateWorkflowRunInputResponse",
    responseMode: "unary",
  },
} as const satisfies Record<EndpointOperation, FrontendEndpointDefinition>;
