// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import type { CreateAgentRequest, CreateAgentResponse, DeleteAgentRequest, DeleteAgentResponse, GetAgentRequest, GetAgentResponse, ListAgentsRequest, ListAgentsResponse, UpdateAgentRequest, UpdateAgentResponse } from "./agent.js";
import type { ListDirectoryRequest, ListDirectoryResponse, ListWorkspaceDirectoryRequest, ListWorkspaceDirectoryResponse, ReadWorkspaceFileRequest, ReadWorkspaceFileResponse, SearchWorkspaceRequest, SearchWorkspaceResponse, WatchWorkspaceRequest, WorkspaceFileEventBatch } from "./file-system.js";
import type { GetGitIdentityRequest, GitIdentityResponse } from "./git.js";
import type { CreateProjectRequest, CreateProjectResponse, DeleteProjectRequest, DeleteProjectResponse, GetProjectRequest, GetProjectResponse, ListProjectBranchesRequest, ListProjectBranchesResponse, ListProjectsRequest, ListProjectsResponse, UpdateProjectRequest, UpdateProjectResponse } from "./project.js";
import type { OpenProjectWorkContextRequest, OpenProjectWorkContextResponse, RenewProjectWorkContextRequest, RenewProjectWorkContextResponse } from "./project-work-context.js";
import type { CreateSessionRequest, CreateSessionResponse, DeleteSessionRequest, DeleteSessionResponse, GetSessionRequest, GetSessionResponse, ListAgentModelsRequest, ListAgentModelsResponse, ListSessionsRequest, ListSessionsResponse, LoadSessionEvent, LoadSessionRequest, PromptSessionEvent, PromptSessionRequest, RespondToPermissionRequest, RespondToPermissionResponse, ResumeSessionHistoryRequest, ResumeSessionHistoryResponse, StopSessionRequest, StopSessionResponse, SwitchSessionAgentRequest, SwitchSessionAgentResponse } from "./session.js";
import type { CreateSkillRequest, CreateSkillResponse, DeleteSkillRequest, DeleteSkillResponse, GetSkillRequest, GetSkillResponse, ListSkillsRequest, ListSkillsResponse, UpdateSkillRequest, UpdateSkillResponse } from "./skill.js";
import type { CancelSkillImportRequest, CancelSkillImportResponse, CommitSkillImportRequest, CommitSkillImportResponse, GetSkillImportSessionRequest, GetSkillImportSessionResponse, PrepareSkillImportRequest, PrepareSkillImportResponse } from "./skill-import.js";
import type { GetSpecCatalogRequest, ReadSpecRequest, ReadSpecResponse, ResolveSpecSourceRequest, ResolveSpecSourceResponse, SpecCatalogResponse, UpdateProjectSpecSourcesRequest, UpdateProjectSpecSourcesResponse, WatchSpecsRequest } from "./spec.js";
import type { CreateTaskRequest, CreateTaskResponse, DeleteTaskRequest, DeleteTaskResponse, GetTaskRequest, GetTaskResponse, GetTaskWorkspaceRequest, GetTaskWorkspaceResponse, ListTasksRequest, ListTasksResponse, UpdateTaskRequest, UpdateTaskResponse } from "./task.js";
import type { CommitTaskChangesRequest, CommitTaskChangesResponse, CreateTaskDiffCommentRequest, CreateTaskDiffCommentResponse, GetTaskDiffRequest, GetTaskDiffResponse, ListTaskDiffCommentsRequest, ListTaskDiffCommentsResponse, PushTaskBranchRequest, PushTaskBranchResponse, ReplyTaskDiffCommentRequest, ReplyTaskDiffCommentResponse, SetTaskDiffCommentStatusRequest, SetTaskDiffCommentStatusResponse } from "./task_diff.js";
import type { HttpMethod } from "./transport.js";

export type EndpointPathParam = {
  rustFieldName: string;
  wireName: string;
};

export type EndpointQueryParam = {
  rustFieldName: string;
  wireName: string;
};

export type FrontendEndpointDefinition = {
  operationName: string;
  namespace: string;
  memberName: string;
  method: HttpMethod;
  pathTemplate: string;
  requestType: string;
  responseType: string;
  responseMode: "unary" | "stream";
  pathParams: readonly EndpointPathParam[];
  queryParams: readonly EndpointQueryParam[];
  hasJsonBody: boolean;
};

export type RequestByOperation = {
  createProject: CreateProjectRequest;
  getProject: GetProjectRequest;
  listProjects: ListProjectsRequest;
  listProjectBranches: ListProjectBranchesRequest;
  updateProject: UpdateProjectRequest;
  deleteProject: DeleteProjectRequest;
  openProjectWorkContext: OpenProjectWorkContextRequest;
  renewProjectWorkContext: RenewProjectWorkContextRequest;
  createTask: CreateTaskRequest;
  getTask: GetTaskRequest;
  listTasks: ListTasksRequest;
  updateTask: UpdateTaskRequest;
  deleteTask: DeleteTaskRequest;
  getTaskWorkspace: GetTaskWorkspaceRequest;
  getTaskDiff: GetTaskDiffRequest;
  commitTaskChanges: CommitTaskChangesRequest;
  pushTaskBranch: PushTaskBranchRequest;
  listTaskDiffComments: ListTaskDiffCommentsRequest;
  createTaskDiffComment: CreateTaskDiffCommentRequest;
  replyTaskDiffComment: ReplyTaskDiffCommentRequest;
  setTaskDiffCommentStatus: SetTaskDiffCommentStatusRequest;
  createSession: CreateSessionRequest;
  getSession: GetSessionRequest;
  listSessions: ListSessionsRequest;
  loadSession: LoadSessionRequest;
  promptSession: PromptSessionRequest;
  respondToSessionPermission: RespondToPermissionRequest;
  stopSession: StopSessionRequest;
  switchSessionAgent: SwitchSessionAgentRequest;
  resumeSessionHistory: ResumeSessionHistoryRequest;
  deleteSession: DeleteSessionRequest;
  listAgentModels: ListAgentModelsRequest;
  createSkill: CreateSkillRequest;
  getSkill: GetSkillRequest;
  listSkills: ListSkillsRequest;
  updateSkill: UpdateSkillRequest;
  deleteSkill: DeleteSkillRequest;
  prepareSkillImport: PrepareSkillImportRequest;
  getSkillImport: GetSkillImportSessionRequest;
  commitSkillImport: CommitSkillImportRequest;
  cancelSkillImport: CancelSkillImportRequest;
  createAgent: CreateAgentRequest;
  getAgent: GetAgentRequest;
  listAgents: ListAgentsRequest;
  updateAgent: UpdateAgentRequest;
  deleteAgent: DeleteAgentRequest;
  listDirectory: ListDirectoryRequest;
  listWorkspaceDirectory: ListWorkspaceDirectoryRequest;
  readWorkspaceFile: ReadWorkspaceFileRequest;
  searchWorkspace: SearchWorkspaceRequest;
  watchWorkspace: WatchWorkspaceRequest;
  getGitIdentity: GetGitIdentityRequest;
  getSpecCatalog: GetSpecCatalogRequest;
  readSpec: ReadSpecRequest;
  resolveSpecSource: ResolveSpecSourceRequest;
  updateProjectSpecSources: UpdateProjectSpecSourcesRequest;
  watchSpecs: WatchSpecsRequest;
};

export type ResponseByOperation = {
  createProject: CreateProjectResponse;
  getProject: GetProjectResponse;
  listProjects: ListProjectsResponse;
  listProjectBranches: ListProjectBranchesResponse;
  updateProject: UpdateProjectResponse;
  deleteProject: DeleteProjectResponse;
  openProjectWorkContext: OpenProjectWorkContextResponse;
  renewProjectWorkContext: RenewProjectWorkContextResponse;
  createTask: CreateTaskResponse;
  getTask: GetTaskResponse;
  listTasks: ListTasksResponse;
  updateTask: UpdateTaskResponse;
  deleteTask: DeleteTaskResponse;
  getTaskWorkspace: GetTaskWorkspaceResponse;
  getTaskDiff: GetTaskDiffResponse;
  commitTaskChanges: CommitTaskChangesResponse;
  pushTaskBranch: PushTaskBranchResponse;
  listTaskDiffComments: ListTaskDiffCommentsResponse;
  createTaskDiffComment: CreateTaskDiffCommentResponse;
  replyTaskDiffComment: ReplyTaskDiffCommentResponse;
  setTaskDiffCommentStatus: SetTaskDiffCommentStatusResponse;
  createSession: CreateSessionResponse;
  getSession: GetSessionResponse;
  listSessions: ListSessionsResponse;
  loadSession: LoadSessionEvent;
  promptSession: PromptSessionEvent;
  respondToSessionPermission: RespondToPermissionResponse;
  stopSession: StopSessionResponse;
  switchSessionAgent: SwitchSessionAgentResponse;
  resumeSessionHistory: ResumeSessionHistoryResponse;
  deleteSession: DeleteSessionResponse;
  listAgentModels: ListAgentModelsResponse;
  createSkill: CreateSkillResponse;
  getSkill: GetSkillResponse;
  listSkills: ListSkillsResponse;
  updateSkill: UpdateSkillResponse;
  deleteSkill: DeleteSkillResponse;
  prepareSkillImport: PrepareSkillImportResponse;
  getSkillImport: GetSkillImportSessionResponse;
  commitSkillImport: CommitSkillImportResponse;
  cancelSkillImport: CancelSkillImportResponse;
  createAgent: CreateAgentResponse;
  getAgent: GetAgentResponse;
  listAgents: ListAgentsResponse;
  updateAgent: UpdateAgentResponse;
  deleteAgent: DeleteAgentResponse;
  listDirectory: ListDirectoryResponse;
  listWorkspaceDirectory: ListWorkspaceDirectoryResponse;
  readWorkspaceFile: ReadWorkspaceFileResponse;
  searchWorkspace: SearchWorkspaceResponse;
  watchWorkspace: WorkspaceFileEventBatch;
  getGitIdentity: GitIdentityResponse;
  getSpecCatalog: SpecCatalogResponse;
  readSpec: ReadSpecResponse;
  resolveSpecSource: ResolveSpecSourceResponse;
  updateProjectSpecSources: UpdateProjectSpecSourcesResponse;
  watchSpecs: WorkspaceFileEventBatch;
};

export type EndpointOperation = keyof RequestByOperation;

export const endpoints = {
  createProject: {
    operationName: "createProject",
    namespace: "project",
    memberName: "create",
    method: "POST",
    pathTemplate: "/api/projects",
    requestType: "CreateProjectRequest",
    responseType: "CreateProjectResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  getProject: {
    operationName: "getProject",
    namespace: "project",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/projects/{projectId}",
    requestType: "GetProjectRequest",
    responseType: "GetProjectResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  listProjects: {
    operationName: "listProjects",
    namespace: "project",
    memberName: "list",
    method: "GET",
    pathTemplate: "/api/projects",
    requestType: "ListProjectsRequest",
    responseType: "ListProjectsResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: false,
  },
  listProjectBranches: {
    operationName: "listProjectBranches",
    namespace: "project",
    memberName: "listBranches",
    method: "GET",
    pathTemplate: "/api/projects/{projectId}/branches",
    requestType: "ListProjectBranchesRequest",
    responseType: "ListProjectBranchesResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  updateProject: {
    operationName: "updateProject",
    namespace: "project",
    memberName: "update",
    method: "PUT",
    pathTemplate: "/api/projects/{projectId}",
    requestType: "UpdateProjectRequest",
    responseType: "UpdateProjectResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  deleteProject: {
    operationName: "deleteProject",
    namespace: "project",
    memberName: "delete",
    method: "DELETE",
    pathTemplate: "/api/projects/{projectId}",
    requestType: "DeleteProjectRequest",
    responseType: "DeleteProjectResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  openProjectWorkContext: {
    operationName: "openProjectWorkContext",
    namespace: "projectWorkContext",
    memberName: "open",
    method: "POST",
    pathTemplate: "/api/project-work-contexts/open",
    requestType: "OpenProjectWorkContextRequest",
    responseType: "OpenProjectWorkContextResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  renewProjectWorkContext: {
    operationName: "renewProjectWorkContext",
    namespace: "projectWorkContext",
    memberName: "renew",
    method: "POST",
    pathTemplate: "/api/project-work-contexts/renew",
    requestType: "RenewProjectWorkContextRequest",
    responseType: "RenewProjectWorkContextResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  createTask: {
    operationName: "createTask",
    namespace: "task",
    memberName: "create",
    method: "POST",
    pathTemplate: "/api/tasks",
    requestType: "CreateTaskRequest",
    responseType: "CreateTaskResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  getTask: {
    operationName: "getTask",
    namespace: "task",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/tasks/{taskId}",
    requestType: "GetTaskRequest",
    responseType: "GetTaskResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  listTasks: {
    operationName: "listTasks",
    namespace: "task",
    memberName: "list",
    method: "GET",
    pathTemplate: "/api/tasks",
    requestType: "ListTasksRequest",
    responseType: "ListTasksResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: false,
  },
  updateTask: {
    operationName: "updateTask",
    namespace: "task",
    memberName: "update",
    method: "PUT",
    pathTemplate: "/api/tasks/{taskId}",
    requestType: "UpdateTaskRequest",
    responseType: "UpdateTaskResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  deleteTask: {
    operationName: "deleteTask",
    namespace: "task",
    memberName: "delete",
    method: "DELETE",
    pathTemplate: "/api/tasks/{taskId}",
    requestType: "DeleteTaskRequest",
    responseType: "DeleteTaskResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  getTaskWorkspace: {
    operationName: "getTaskWorkspace",
    namespace: "task",
    memberName: "getWorkspace",
    method: "GET",
    pathTemplate: "/api/tasks/{taskId}/workspace",
    requestType: "GetTaskWorkspaceRequest",
    responseType: "GetTaskWorkspaceResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  getTaskDiff: {
    operationName: "getTaskDiff",
    namespace: "task",
    memberName: "getDiff",
    method: "GET",
    pathTemplate: "/api/tasks/{taskId}/diff",
    requestType: "GetTaskDiffRequest",
    responseType: "GetTaskDiffResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [{ rustFieldName: "scope", wireName: "scope" }],
    hasJsonBody: false,
  },
  commitTaskChanges: {
    operationName: "commitTaskChanges",
    namespace: "task",
    memberName: "commitChanges",
    method: "POST",
    pathTemplate: "/api/tasks/{taskId}/git/commit",
    requestType: "CommitTaskChangesRequest",
    responseType: "CommitTaskChangesResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  pushTaskBranch: {
    operationName: "pushTaskBranch",
    namespace: "task",
    memberName: "pushBranch",
    method: "POST",
    pathTemplate: "/api/tasks/{taskId}/git/push",
    requestType: "PushTaskBranchRequest",
    responseType: "PushTaskBranchResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  listTaskDiffComments: {
    operationName: "listTaskDiffComments",
    namespace: "task",
    memberName: "listDiffComments",
    method: "GET",
    pathTemplate: "/api/tasks/{taskId}/diff/comments",
    requestType: "ListTaskDiffCommentsRequest",
    responseType: "ListTaskDiffCommentsResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  createTaskDiffComment: {
    operationName: "createTaskDiffComment",
    namespace: "task",
    memberName: "createDiffComment",
    method: "POST",
    pathTemplate: "/api/tasks/{taskId}/diff/comments",
    requestType: "CreateTaskDiffCommentRequest",
    responseType: "CreateTaskDiffCommentResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  replyTaskDiffComment: {
    operationName: "replyTaskDiffComment",
    namespace: "task",
    memberName: "replyDiffComment",
    method: "POST",
    pathTemplate: "/api/tasks/{taskId}/diff/comments/{commentId}/replies",
    requestType: "ReplyTaskDiffCommentRequest",
    responseType: "ReplyTaskDiffCommentResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }, { rustFieldName: "comment_id", wireName: "commentId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  setTaskDiffCommentStatus: {
    operationName: "setTaskDiffCommentStatus",
    namespace: "task",
    memberName: "setDiffCommentStatus",
    method: "PUT",
    pathTemplate: "/api/tasks/{taskId}/diff/comments/{commentId}/status",
    requestType: "SetTaskDiffCommentStatusRequest",
    responseType: "SetTaskDiffCommentStatusResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }, { rustFieldName: "comment_id", wireName: "commentId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  createSession: {
    operationName: "createSession",
    namespace: "session",
    memberName: "create",
    method: "POST",
    pathTemplate: "/api/sessions",
    requestType: "CreateSessionRequest",
    responseType: "CreateSessionResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  getSession: {
    operationName: "getSession",
    namespace: "session",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/sessions/{sessionId}",
    requestType: "GetSessionRequest",
    responseType: "GetSessionResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  listSessions: {
    operationName: "listSessions",
    namespace: "session",
    memberName: "list",
    method: "GET",
    pathTemplate: "/api/sessions",
    requestType: "ListSessionsRequest",
    responseType: "ListSessionsResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: false,
  },
  loadSession: {
    operationName: "loadSession",
    namespace: "session",
    memberName: "load",
    method: "POST",
    pathTemplate: "/api/sessions/{sessionId}/load",
    requestType: "LoadSessionRequest",
    responseType: "LoadSessionEvent",
    responseMode: "stream",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  promptSession: {
    operationName: "promptSession",
    namespace: "session",
    memberName: "prompt",
    method: "POST",
    pathTemplate: "/api/sessions/{sessionId}/prompt",
    requestType: "PromptSessionRequest",
    responseType: "PromptSessionEvent",
    responseMode: "stream",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  respondToSessionPermission: {
    operationName: "respondToSessionPermission",
    namespace: "session",
    memberName: "respondToPermission",
    method: "POST",
    pathTemplate: "/api/sessions/{sessionId}/permissions/respond",
    requestType: "RespondToPermissionRequest",
    responseType: "RespondToPermissionResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  stopSession: {
    operationName: "stopSession",
    namespace: "session",
    memberName: "stop",
    method: "POST",
    pathTemplate: "/api/sessions/{sessionId}/stop",
    requestType: "StopSessionRequest",
    responseType: "StopSessionResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  switchSessionAgent: {
    operationName: "switchSessionAgent",
    namespace: "session",
    memberName: "switchAgent",
    method: "POST",
    pathTemplate: "/api/sessions/{sessionId}/agent",
    requestType: "SwitchSessionAgentRequest",
    responseType: "SwitchSessionAgentResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  resumeSessionHistory: {
    operationName: "resumeSessionHistory",
    namespace: "session",
    memberName: "resumeHistory",
    method: "POST",
    pathTemplate: "/api/sessions/{sessionId}/history/resume",
    requestType: "ResumeSessionHistoryRequest",
    responseType: "ResumeSessionHistoryResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  deleteSession: {
    operationName: "deleteSession",
    namespace: "session",
    memberName: "delete",
    method: "DELETE",
    pathTemplate: "/api/sessions/{sessionId}",
    requestType: "DeleteSessionRequest",
    responseType: "DeleteSessionResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  listAgentModels: {
    operationName: "listAgentModels",
    namespace: "agentRuntime",
    memberName: "listModels",
    method: "GET",
    pathTemplate: "/api/agent-models",
    requestType: "ListAgentModelsRequest",
    responseType: "ListAgentModelsResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: false,
  },
  createSkill: {
    operationName: "createSkill",
    namespace: "skill",
    memberName: "create",
    method: "POST",
    pathTemplate: "/api/skills",
    requestType: "CreateSkillRequest",
    responseType: "CreateSkillResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  getSkill: {
    operationName: "getSkill",
    namespace: "skill",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/skills/{skillId}",
    requestType: "GetSkillRequest",
    responseType: "GetSkillResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "skill_id", wireName: "skillId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  listSkills: {
    operationName: "listSkills",
    namespace: "skill",
    memberName: "list",
    method: "GET",
    pathTemplate: "/api/skills",
    requestType: "ListSkillsRequest",
    responseType: "ListSkillsResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: false,
  },
  updateSkill: {
    operationName: "updateSkill",
    namespace: "skill",
    memberName: "update",
    method: "PUT",
    pathTemplate: "/api/skills/{skillId}",
    requestType: "UpdateSkillRequest",
    responseType: "UpdateSkillResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "skill_id", wireName: "skillId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  deleteSkill: {
    operationName: "deleteSkill",
    namespace: "skill",
    memberName: "delete",
    method: "DELETE",
    pathTemplate: "/api/skills/{skillId}",
    requestType: "DeleteSkillRequest",
    responseType: "DeleteSkillResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "skill_id", wireName: "skillId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  prepareSkillImport: {
    operationName: "prepareSkillImport",
    namespace: "skillImport",
    memberName: "prepare",
    method: "POST",
    pathTemplate: "/api/skill-imports",
    requestType: "PrepareSkillImportRequest",
    responseType: "PrepareSkillImportResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: false,
  },
  getSkillImport: {
    operationName: "getSkillImport",
    namespace: "skillImport",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/skill-imports/{sessionId}",
    requestType: "GetSkillImportSessionRequest",
    responseType: "GetSkillImportSessionResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  commitSkillImport: {
    operationName: "commitSkillImport",
    namespace: "skillImport",
    memberName: "commit",
    method: "POST",
    pathTemplate: "/api/skill-imports/{sessionId}/commit",
    requestType: "CommitSkillImportRequest",
    responseType: "CommitSkillImportResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  cancelSkillImport: {
    operationName: "cancelSkillImport",
    namespace: "skillImport",
    memberName: "cancel",
    method: "DELETE",
    pathTemplate: "/api/skill-imports/{sessionId}",
    requestType: "CancelSkillImportRequest",
    responseType: "CancelSkillImportResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  createAgent: {
    operationName: "createAgent",
    namespace: "agent",
    memberName: "create",
    method: "POST",
    pathTemplate: "/api/agents",
    requestType: "CreateAgentRequest",
    responseType: "CreateAgentResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  getAgent: {
    operationName: "getAgent",
    namespace: "agent",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/agents/{agentId}",
    requestType: "GetAgentRequest",
    responseType: "GetAgentResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "agent_id", wireName: "agentId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  listAgents: {
    operationName: "listAgents",
    namespace: "agent",
    memberName: "list",
    method: "GET",
    pathTemplate: "/api/agents",
    requestType: "ListAgentsRequest",
    responseType: "ListAgentsResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: false,
  },
  updateAgent: {
    operationName: "updateAgent",
    namespace: "agent",
    memberName: "update",
    method: "PUT",
    pathTemplate: "/api/agents/{agentId}",
    requestType: "UpdateAgentRequest",
    responseType: "UpdateAgentResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "agent_id", wireName: "agentId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  deleteAgent: {
    operationName: "deleteAgent",
    namespace: "agent",
    memberName: "delete",
    method: "DELETE",
    pathTemplate: "/api/agents/{agentId}",
    requestType: "DeleteAgentRequest",
    responseType: "DeleteAgentResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "agent_id", wireName: "agentId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  listDirectory: {
    operationName: "listDirectory",
    namespace: "fileSystem",
    memberName: "listDirectory",
    method: "GET",
    pathTemplate: "/api/file-system/directory",
    requestType: "ListDirectoryRequest",
    responseType: "ListDirectoryResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [{ rustFieldName: "path", wireName: "path" }],
    hasJsonBody: false,
  },
  listWorkspaceDirectory: {
    operationName: "listWorkspaceDirectory",
    namespace: "fileSystem",
    memberName: "listWorkspaceDirectory",
    method: "POST",
    pathTemplate: "/api/tasks/{taskId}/files/list",
    requestType: "ListWorkspaceDirectoryRequest",
    responseType: "ListWorkspaceDirectoryResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  readWorkspaceFile: {
    operationName: "readWorkspaceFile",
    namespace: "fileSystem",
    memberName: "readWorkspaceFile",
    method: "POST",
    pathTemplate: "/api/tasks/{taskId}/files/read",
    requestType: "ReadWorkspaceFileRequest",
    responseType: "ReadWorkspaceFileResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  searchWorkspace: {
    operationName: "searchWorkspace",
    namespace: "fileSystem",
    memberName: "searchWorkspace",
    method: "POST",
    pathTemplate: "/api/tasks/{taskId}/files/search",
    requestType: "SearchWorkspaceRequest",
    responseType: "SearchWorkspaceResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  watchWorkspace: {
    operationName: "watchWorkspace",
    namespace: "fileSystem",
    memberName: "watchWorkspace",
    method: "GET",
    pathTemplate: "/api/tasks/{taskId}/files/watch",
    requestType: "WatchWorkspaceRequest",
    responseType: "WorkspaceFileEventBatch",
    responseMode: "stream",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    queryParams: [],
    hasJsonBody: false,
  },
  getGitIdentity: {
    operationName: "getGitIdentity",
    namespace: "gitIdentity",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/git/identity",
    requestType: "GetGitIdentityRequest",
    responseType: "GitIdentityResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: false,
  },
  getSpecCatalog: {
    operationName: "getSpecCatalog",
    namespace: "spec",
    memberName: "catalog",
    method: "POST",
    pathTemplate: "/api/specs/catalog",
    requestType: "GetSpecCatalogRequest",
    responseType: "SpecCatalogResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  readSpec: {
    operationName: "readSpec",
    namespace: "spec",
    memberName: "read",
    method: "POST",
    pathTemplate: "/api/specs/read",
    requestType: "ReadSpecRequest",
    responseType: "ReadSpecResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  resolveSpecSource: {
    operationName: "resolveSpecSource",
    namespace: "spec",
    memberName: "resolveSource",
    method: "POST",
    pathTemplate: "/api/specs/resolve-source",
    requestType: "ResolveSpecSourceRequest",
    responseType: "ResolveSpecSourceResponse",
    responseMode: "unary",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  updateProjectSpecSources: {
    operationName: "updateProjectSpecSources",
    namespace: "spec",
    memberName: "updateProjectSources",
    method: "PUT",
    pathTemplate: "/api/projects/{projectId}/spec-sources",
    requestType: "UpdateProjectSpecSourcesRequest",
    responseType: "UpdateProjectSpecSourcesResponse",
    responseMode: "unary",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    queryParams: [],
    hasJsonBody: true,
  },
  watchSpecs: {
    operationName: "watchSpecs",
    namespace: "spec",
    memberName: "watch",
    method: "POST",
    pathTemplate: "/api/specs/watch",
    requestType: "WatchSpecsRequest",
    responseType: "WorkspaceFileEventBatch",
    responseMode: "stream",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
} as const satisfies Record<EndpointOperation, FrontendEndpointDefinition>;
