// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries one validated public error and the request identifier used in runtime logs.
 */
export type ContractError =
  & { requestId: RequestId }
  & (
    | { "code": "internal_error"; "params": EmptyErrorParams }
    | { "code": "invalid_request"; "params": EmptyErrorParams }
    | { "code": "skill_name_blank"; "params": EmptyErrorParams }
    | { "code": "skill_not_found"; "params": EmptyErrorParams }
    | { "code": "agent_name_blank"; "params": EmptyErrorParams }
    | { "code": "agent_not_found"; "params": EmptyErrorParams }
    | { "code": "project_not_found"; "params": EmptyErrorParams }
    | { "code": "project_occupied"; "params": EmptyErrorParams }
    | { "code": "project_work_context_not_found"; "params": EmptyErrorParams }
    | { "code": "task_not_found"; "params": EmptyErrorParams }
    | { "code": "resource_in_use"; "params": EmptyErrorParams }
    | { "code": "worktree_requires_git_repository"; "params": EmptyErrorParams }
    | { "code": "worktree_not_found"; "params": EmptyErrorParams }
    | { "code": "session_not_found"; "params": EmptyErrorParams }
    | { "code": "agent_cli_not_found"; "params": EmptyErrorParams }
    | { "code": "agent_runtime_unavailable"; "params": EmptyErrorParams }
    | { "code": "session_busy"; "params": EmptyErrorParams }
    | { "code": "session_stopped"; "params": EmptyErrorParams }
    | { "code": "session_load_unsupported"; "params": EmptyErrorParams }
    | { "code": "permission_request_not_pending"; "params": EmptyErrorParams }
    | { "code": "permission_option_invalid"; "params": EmptyErrorParams }
    | { "code": "prompt_empty"; "params": EmptyErrorParams }
    | { "code": "prompt_too_large"; "params": EmptyErrorParams }
    | { "code": "task_worktree_unavailable"; "params": EmptyErrorParams }
    | { "code": "task_project_root_unavailable"; "params": EmptyErrorParams }
    | { "code": "file_system_path_not_absolute"; "params": EmptyErrorParams }
    | { "code": "file_system_path_not_directory"; "params": EmptyErrorParams }
    | { "code": "file_system_path_not_found"; "params": EmptyErrorParams }
    | {
      "code": "file_system_path_permission_denied";
      "params": EmptyErrorParams;
    }
    | { "code": "worktree_root_not_absolute"; "params": EmptyErrorParams }
    | { "code": "worktree_root_not_directory"; "params": EmptyErrorParams }
    | { "code": "open_location_failed"; "params": OpenLocationFailedParams }
    | { "code": "skill_upload_empty"; "params": EmptyErrorParams }
    | {
      "code": "skill_upload_too_many_files";
      "params": SkillUploadTooManyFilesParams;
    }
    | { "code": "skill_upload_path_invalid"; "params": EmptyErrorParams }
    | { "code": "skill_upload_path_duplicate"; "params": EmptyErrorParams }
    | { "code": "skill_manifest_missing"; "params": EmptyErrorParams }
    | { "code": "skill_manifest_invalid"; "params": EmptyErrorParams }
    | { "code": "skill_manifest_name_blank"; "params": EmptyErrorParams }
    | { "code": "skill_manifest_description_blank"; "params": EmptyErrorParams }
    | { "code": "skill_manifest_name_invalid"; "params": EmptyErrorParams }
    | { "code": "skill_folder_conflict"; "params": SkillFolderConflictParams }
    | { "code": "spec_workspace_unavailable"; "params": EmptyErrorParams }
    | { "code": "spec_not_found"; "params": EmptyErrorParams }
  );

/**
 * Represents the deliberately empty parameters used by errors with no safe interpolation data.
 */
export type EmptyErrorParams = { [key: string]: never };

/**
 * Carries the safe target name for an open-location failure.
 */
export type OpenLocationFailedParams = { target: OpenLocationTarget };

/**
 * Lists the finite Desktop targets that can fail to open.
 */
export type OpenLocationTarget = "explorer" | "terminal" | "vscode";

/**
 * Enumerates every user-visible Ora failure and its exact interpolation parameters.
 */
export type PublicError =
  | { "code": "internal_error"; "params": EmptyErrorParams }
  | { "code": "invalid_request"; "params": EmptyErrorParams }
  | { "code": "skill_name_blank"; "params": EmptyErrorParams }
  | { "code": "skill_not_found"; "params": EmptyErrorParams }
  | { "code": "agent_name_blank"; "params": EmptyErrorParams }
  | { "code": "agent_not_found"; "params": EmptyErrorParams }
  | { "code": "project_not_found"; "params": EmptyErrorParams }
  | { "code": "project_occupied"; "params": EmptyErrorParams }
  | { "code": "project_work_context_not_found"; "params": EmptyErrorParams }
  | { "code": "task_not_found"; "params": EmptyErrorParams }
  | { "code": "resource_in_use"; "params": EmptyErrorParams }
  | { "code": "worktree_requires_git_repository"; "params": EmptyErrorParams }
  | { "code": "worktree_not_found"; "params": EmptyErrorParams }
  | { "code": "session_not_found"; "params": EmptyErrorParams }
  | { "code": "agent_cli_not_found"; "params": EmptyErrorParams }
  | { "code": "agent_runtime_unavailable"; "params": EmptyErrorParams }
  | { "code": "session_busy"; "params": EmptyErrorParams }
  | { "code": "session_stopped"; "params": EmptyErrorParams }
  | { "code": "session_load_unsupported"; "params": EmptyErrorParams }
  | { "code": "permission_request_not_pending"; "params": EmptyErrorParams }
  | { "code": "permission_option_invalid"; "params": EmptyErrorParams }
  | { "code": "prompt_empty"; "params": EmptyErrorParams }
  | { "code": "prompt_too_large"; "params": EmptyErrorParams }
  | { "code": "task_worktree_unavailable"; "params": EmptyErrorParams }
  | { "code": "task_project_root_unavailable"; "params": EmptyErrorParams }
  | { "code": "file_system_path_not_absolute"; "params": EmptyErrorParams }
  | { "code": "file_system_path_not_directory"; "params": EmptyErrorParams }
  | { "code": "file_system_path_not_found"; "params": EmptyErrorParams }
  | { "code": "file_system_path_permission_denied"; "params": EmptyErrorParams }
  | { "code": "worktree_root_not_absolute"; "params": EmptyErrorParams }
  | { "code": "worktree_root_not_directory"; "params": EmptyErrorParams }
  | { "code": "open_location_failed"; "params": OpenLocationFailedParams }
  | { "code": "skill_upload_empty"; "params": EmptyErrorParams }
  | {
    "code": "skill_upload_too_many_files";
    "params": SkillUploadTooManyFilesParams;
  }
  | { "code": "skill_upload_path_invalid"; "params": EmptyErrorParams }
  | { "code": "skill_upload_path_duplicate"; "params": EmptyErrorParams }
  | { "code": "skill_manifest_missing"; "params": EmptyErrorParams }
  | { "code": "skill_manifest_invalid"; "params": EmptyErrorParams }
  | { "code": "skill_manifest_name_blank"; "params": EmptyErrorParams }
  | { "code": "skill_manifest_description_blank"; "params": EmptyErrorParams }
  | { "code": "skill_manifest_name_invalid"; "params": EmptyErrorParams }
  | { "code": "skill_folder_conflict"; "params": SkillFolderConflictParams }
  | { "code": "spec_workspace_unavailable"; "params": EmptyErrorParams }
  | { "code": "spec_not_found"; "params": EmptyErrorParams };

/**
 * Identifies one Ora request across adapters, spans, responses, and completion events.
 */
export type RequestId = string;

/**
 * Carries a validated skill name when its destination folder already exists.
 */
export type SkillFolderConflictParams = { name: string };

/**
 * Carries the configured upload limit without exposing uploaded file names.
 */
export type SkillUploadTooManyFilesParams = { maxFiles: number };
