// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests the global Git identity; carries no fields because the scope is fixed to `--global`.
 */
export type GetGitIdentityRequest = Record<symbol, never>;

/**
 * Returns the global Git identity, with each field absent when its config key is unset.
 */
export type GitIdentityResponse = { name: string | null; email: string | null };
