// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests process activation for one enabled plugin.
 */
export type ActivatePluginRequest = { pluginId: string };

/**
 * Returns the immediate starting or already-running plugin snapshot.
 */
export type ActivatePluginResponse = { plugin: InstalledPlugin };

/**
 * Describes one marketplace plugin listed by the cached registry index.
 */
export type AvailablePlugin = {
  id: string;
  name: string;
  namespace: string;
  version: string;
  description: string;
  /**
   * Security-validated SVG source for the marketplace icon, absent when none is published.
   */
  logo: string | null;
};

/**
 * Requests persistent ineligibility for one installed plugin.
 */
export type DisablePluginRequest = { pluginId: string };

/**
 * Returns the stopped and disabled plugin snapshot after persistence succeeds.
 */
export type DisablePluginResponse = { plugin: InstalledPlugin };

/**
 * Requests durable eligibility for one installed plugin without starting its process.
 */
export type EnablePluginRequest = { pluginId: string };

/**
 * Returns the enabled plugin snapshot observed after persistence succeeds.
 */
export type EnablePluginResponse = { plugin: InstalledPlugin };

/**
 * Requests importing one local `.orax` release archive into the installed plugins tree.
 */
export type ImportPluginRequest = {
  /**
   * Absolute path to the local `.orax` archive.
   */
  path: string;
};

/**
 * Confirms the identifier imported after the archive is verified, extracted, and enabled.
 */
export type ImportPluginResponse = { pluginId: string };

/**
 * Requests installation of one marketplace plugin by its registry identifier.
 */
export type InstallPluginRequest = { pluginId: string };

/**
 * Confirms the identifier installed after download, verification, and extraction complete.
 */
export type InstallPluginResponse = { pluginId: string };

/**
 * Describes one installed plugin discovered from its `orax.toml` manifest.
 *
 * `id` is the canonical `<namespace>/<name>` spelling and is what every plugin request carries
 * back; `namespace` and `name` repeat the two segments so the frontend never has to split it.
 */
export type InstalledPlugin =
  & {
    id: string;
    namespace: string;
    name: string;
    displayName: string;
    version: string;
    description: string;
    homepage: string | null;
    license: string | null;
    enabled: boolean;
    /**
     * Security-validated SVG source for the package icon, absent when the package ships none.
     *
     * The icon travels as inline source instead of a filesystem path because the webview cannot
     * read the plugin directory; surfaces render it from a `data:` URL and fall back to a
     * generic mark when it is absent.
     */
    logo: string | null;
  }
  & (
    | { "kind": "agent"; agentDisplayName: string }
    | { "kind": "workbench"; title: string }
    | { "kind": "webview"; title: string; startUrl: string }
    | { "kind": "skill" }
  )
  & ({ "runtime": "stopped" } | { "runtime": "starting" } | {
    "runtime": "running";
  } | { "runtime": "failed"; failureReason: string });

/**
 * Describes the kind-specific contribution of one installed plugin, discriminated by `kind`.
 *
 * The agent variant names its display name `agentDisplayName` because the contribution is
 * flattened into [`InstalledPlugin`], which already owns the top-level `displayName`. The two
 * surface kinds expose only what the launcher needs to render an entry: the frontend never
 * learns asset paths, origin allow lists, or download rules, which is what keeps those host
 * policies non-negotiable from the page side.
 */
export type InstalledPluginContribution =
  | { "kind": "agent"; agentDisplayName: string }
  | { "kind": "workbench"; title: string }
  | { "kind": "webview"; title: string; startUrl: string }
  | { "kind": "skill" };

/**
 * Requests the cached marketplace registry index used to populate the plugin catalog.
 */
export type ListAvailablePluginsRequest = Record<symbol, never>;

/**
 * Returns the marketplace plugins cached in the registry index.
 */
export type ListAvailablePluginsResponse = {
  updatedAt: bigint;
  plugins: Array<AvailablePlugin>;
};

/**
 * Requests the immutable startup snapshot of installed plugin packages.
 */
export type ListInstalledPluginsRequest = Record<symbol, never>;

/**
 * Returns every valid installed plugin in stable identifier order.
 */
export type ListInstalledPluginsResponse = { plugins: Array<InstalledPlugin> };

/**
 * Represents the process-scoped lifecycle of one installed plugin.
 */
export type PluginRuntimeStatus =
  | { "runtime": "stopped" }
  | { "runtime": "starting" }
  | { "runtime": "running" }
  | { "runtime": "failed"; failureReason: string };

/**
 * Requests explicit filesystem discovery and state reconciliation.
 */
export type ScanPluginsRequest = Record<symbol, never>;

/**
 * Returns the refreshed installed-plugin snapshot produced by an explicit scan.
 */
export type ScanPluginsResponse = { plugins: Array<InstalledPlugin> };

/**
 * Requests process shutdown for one plugin without changing durable eligibility.
 */
export type StopPluginRequest = { pluginId: string };

/**
 * Returns the stopped plugin snapshot after process exit is confirmed.
 */
export type StopPluginResponse = { plugin: InstalledPlugin };

/**
 * Requests a marketplace source sync followed by an atomic registry-index rebuild.
 */
export type SyncAvailablePluginsRequest = Record<symbol, never>;

/**
 * Returns the registry index rebuilt immediately after a marketplace sync succeeds.
 */
export type SyncAvailablePluginsResponse = {
  updatedAt: bigint;
  plugins: Array<AvailablePlugin>;
};

/**
 * Requests complete removal of one plugin package and its durable lifecycle state.
 */
export type UninstallPluginRequest = { pluginId: string };

/**
 * Confirms the identifier removed after process shutdown and package deletion complete.
 */
export type UninstallPluginResponse = { pluginId: string };
