// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one installed plugin discovered from its package manifest.
 */
export type InstalledPlugin = {
  id: string;
  packageName: string;
  displayName: string;
  version: string;
  kind: string;
  main: string;
  agents: Array<InstalledPluginAgent>;
};

/**
 * Describes one agent contribution from an installed plugin package.
 */
export type InstalledPluginAgent = {
  id: string;
  displayName: string;
  contractVersion: number;
};

/**
 * Requests the immutable startup snapshot of installed plugin packages.
 */
export type ListInstalledPluginsRequest = Record<symbol, never>;

/**
 * Returns every valid installed plugin in stable identifier order.
 */
export type ListInstalledPluginsResponse = { plugins: Array<InstalledPlugin> };
