// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the app-facing payload for project creation requests.
 */
export type CreateProjectRequest = { name: string; rootPath: string };

/**
 * Returns the created project after a successful create request.
 */
export type CreateProjectResponse = { project: Project };

/**
 * Identifies which project to delete.
 */
export type DeleteProjectRequest = { projectId: string };

/**
 * Returns the deleted project identifier after a successful delete request.
 */
export type DeleteProjectResponse = { projectId: string };

/**
 * Identifies which project to fetch.
 */
export type GetProjectRequest = { projectId: string };

/**
 * Returns one project payload after a successful fetch.
 */
export type GetProjectResponse = { project: Project };

/**
 * Identifies which project's local Git branches should be listed.
 */
export type ListProjectBranchesRequest = { projectId: string };

/**
 * Returns local branches that can seed a new worktree.
 */
export type ListProjectBranchesResponse = { branches: Array<ProjectBranch> };

/**
 * Requests the full visible project list.
 */
export type ListProjectsRequest = Record<symbol, never>;

/**
 * Returns the visible project list.
 */
export type ListProjectsResponse = { projects: Array<Project> };

/**
 * Describes the public project payload shared across adapter responses.
 */
export type Project = { id: string; name: string; rootPath: string };

/**
 * Separates the logical branch name, resolvable ref, and label shown to users.
 */
export type ProjectBranch = {
  name: string;
  refName: string;
  displayName: string;
};

/**
 * Carries the mutable project name while the repository root remains immutable.
 */
export type UpdateProjectRequest = { projectId: string; name: string };

/**
 * Returns the updated project after a successful update request.
 */
export type UpdateProjectResponse = { project: Project };
