// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests the configured network proxy without additional parameters.
 */
export type GetProxySettingsRequest = Record<symbol, never>;

/**
 * Returns the configured network proxy.
 */
export type GetProxySettingsResponse = { settings: ProxySettings | null };

/**
 * Describes an optional host-level network proxy used by marketplace traffic.
 */
export type ProxySettings = {
  /**
   * Proxy hostname or address without a scheme.
   */
  host: string;
  /**
   * Proxy TCP port.
   */
  port: number;
  /**
   * Optional HTTP Basic username for the proxy.
   */
  username: string | null;
  /**
   * Optional HTTP Basic password for the proxy.
   */
  password: string | null;
};

/**
 * Requests replacing the configured network proxy.
 */
export type SetProxySettingsRequest = { settings: ProxySettings };

/**
 * Returns the authoritative network proxy after a save.
 */
export type SetProxySettingsResponse = { settings: ProxySettings | null };
