// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests the process-wide runtime log-level state without additional parameters.
 */
export type GetRuntimeLogLevelRequest = Record<symbol, never>;

/**
 * Enumerates the only log-level values accepted across runtime transport boundaries.
 */
export type RuntimeLogLevel = "trace" | "debug" | "info" | "warn" | "error";

/**
 * Returns the runtime-authoritative preference, live filter, and startup explanation.
 */
export type RuntimeLogLevelStateResponse = {
  configuredLevel: RuntimeLogLevel;
  effectiveLevel: RuntimeLogLevel;
  startupOverride: RuntimeLogLevel | null;
};

/**
 * Requests a new effective and persisted preferred process-wide log level.
 */
export type SetRuntimeLogLevelRequest = { level: RuntimeLogLevel };
