// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one model an agent offers before any session exists.
 *
 * This is separate from the session config options an agent sends after `session/new`: the agent
 * and model pickers must render before any session has been created. Agents that expose models
 * only through session config options contribute nothing here.
 */
export type AgentModel = {
  id: string;
  displayName: string;
  /**
   * Whether the agent would select this model when the user expresses no preference.
   */
  default: boolean;
};

/**
 * Pairs one agent identity with its current runtime detection status.
 */
export type AgentRuntimeStatus = { agentRef: string; status: AgentStatus };

/**
 * Describes the live ACP handshake state of one application-scoped agent runtime.
 */
export type AgentStatus = "ready" | "starting" | "unavailable" | "failing";

/**
 * Binds one warm session to its owning Task and persists the Ora record.
 */
export type AttachSessionRequest = { sessionId: string; taskId: string };

/**
 * Returns the newly persisted session payload.
 */
export type AttachSessionResponse = {
  session: Session;
  availableCommands: Array<import("@agentclientprotocol/sdk").AvailableCommand>;
};

/**
 * Identifies which Ora session record to remove.
 */
export type DeleteSessionRequest = { sessionId: string };

/**
 * Returns the removed Ora session identifier without deleting provider history.
 */
export type DeleteSessionResponse = { sessionId: string };

/**
 * Requests the live detection status of every application-scoped agent runtime.
 */
export type GetAgentRuntimeStatusRequest = Record<symbol, never>;

/**
 * Returns the live detection status of every application-scoped agent runtime.
 */
export type GetAgentRuntimeStatusResponse = {
  statuses: Array<AgentRuntimeStatus>;
};

/**
 * Identifies which session to fetch.
 */
export type GetSessionRequest = { sessionId: string };

/**
 * Returns one session payload after a successful fetch.
 */
export type GetSessionResponse = { session: Session };

/**
 * Requests the pre-session model list of one application-scoped agent runtime.
 */
export type ListAgentModelsRequest = { agentRef: string };

/**
 * Returns the models one agent advertises outside any session.
 */
export type ListAgentModelsResponse = { models: Array<AgentModel> };

/**
 * Requests the full visible session list.
 */
export type ListSessionsRequest = Record<symbol, never>;

/**
 * Returns the visible session list.
 */
export type ListSessionsResponse = { sessions: Array<Session> };

/**
 * Replays Ora's recorded history while keeping JSON-RPC framing private to the backend.
 *
 * The stream carries assembled updates read back from Ora's own record, not the
 * provider's replay. `TurnEnded` has no ACP equivalent and exists because a
 * cancelled turn would otherwise be indistinguishable from a completed one —
 * information provider replay never carried.
 */
export type LoadSessionEvent =
  | {
    "type": "session_update";
    update: import("@agentclientprotocol/sdk").SessionUpdate;
  }
  | { "type": "permission_request" } & SessionPermissionRequest
  | {
    "type": "turn_ended";
    stopReason: import("@agentclientprotocol/sdk").StopReason;
  }
  | { "type": "history_notice"; notice: SessionHistoryNotice }
  | { "type": "completed" };

/**
 * Identifies a stopped session whose provider history should be replayed.
 */
export type LoadSessionRequest = { sessionId: string };

/**
 * Streams one prompt turn and ends with the provider's typed stop reason.
 */
export type PromptSessionEvent =
  | {
    "type": "session_update";
    update: import("@agentclientprotocol/sdk").SessionUpdate;
  }
  | { "type": "permission_request" } & SessionPermissionRequest
  | {
    "type": "completed";
    stopReason: import("@agentclientprotocol/sdk").StopReason;
  };

/**
 * Carries one or more ACP content blocks to the provider session.
 */
export type PromptSessionRequest = {
  sessionId: string;
  prompt: Array<import("@agentclientprotocol/sdk").ContentBlock>;
};

/**
 * Renames one persisted session with a user-supplied display title.
 */
export type RenameSessionRequest = { sessionId: string; title: string };

/**
 * Returns the session after its display title was replaced.
 */
export type RenameSessionResponse = { session: Session };

/**
 * Selects one option for a still-pending permission request.
 */
export type RespondToPermissionRequest = {
  sessionId: string;
  permissionRequestId: string;
  optionId: string;
};

/**
 * Confirms that a permission response was delivered to the agent.
 */
export type RespondToPermissionResponse = Record<symbol, never>;

/**
 * Returns a session whose history writes failed to a writable state.
 *
 * Resuming appends a record of what went missing before accepting new content,
 * so the conversation never contains a gap that cannot be seen.
 */
export type ResumeSessionHistoryRequest = { sessionId: string };

/**
 * Returns the session after its history became writable again.
 */
export type ResumeSessionHistoryResponse = { session: Session };

/**
 * Describes the public session payload without exposing the provider session identifier.
 */
export type Session = {
  id: string;
  taskId: string;
  /**
   * The persisted display title, or `null` until the first acquisition succeeds.
   */
  title: string | null;
  /**
   * The agent this conversation currently runs on, which switching replaces.
   */
  agentRef: string;
  status: SessionStatus;
  historyState: SessionHistoryState;
};

/**
 * Describes durable conversation content that Ora knows is missing.
 */
export type SessionHistoryNotice = {
  "type": "unreadable_records";
  count: number;
} | { "type": "unrecorded_content"; reason: string };

/**
 * Reports whether Ora can still extend this session's recorded history.
 *
 * Separate from [`SessionStatus`] on purpose: that says whether the conversation
 * is registered on a CLI connection, this says whether the record of it can
 * still grow. A running session whose disk filled is both at once, and the user
 * has to be told which one broke.
 */
export type SessionHistoryState = { "type": "writable" } | {
  "type": "degraded";
  reason: string;
};

/**
 * Exposes an opaque permission request while preserving the agent's typed option payload.
 */
export type SessionPermissionRequest = {
  permissionRequestId: string;
  toolCall: import("@agentclientprotocol/sdk").ToolCallUpdate;
  options: Array<import("@agentclientprotocol/sdk").PermissionOption>;
};

/**
 * Describes whether a persisted session is registered on its shared CLI connection.
 */
export type SessionStatus = "running" | "stopped";

/**
 * Sets one selectable configuration option on a warm or persisted session.
 *
 * `value` is the chosen option's value id. Only id-valued options are
 * expressible because Ora does not advertise the boolean config-option client
 * capability, so an agent never offers a value this request cannot carry.
 */
export type SetSessionConfigRequest = {
  sessionId: string;
  configId: string;
  value: string;
};

/**
 * Returns the full option set after the agent applies the change.
 */
export type SetSessionConfigResponse = {
  configOptions: Array<import("@agentclientprotocol/sdk").SessionConfigOption>;
};

/**
 * Identifies a running session whose child process should be stopped.
 */
export type StopSessionRequest = { sessionId: string };

/**
 * Returns the stopped public session snapshot.
 */
export type StopSessionResponse = { session: Session };

/**
 * Moves one existing conversation onto a different agent.
 *
 * Only the binding changes: the session keeps its identifier, its task, and the
 * history it has accumulated. The new agent starts with no context, so Ora's
 * recorded transcript is prepended to the next prompt sent into it.
 */
export type SwitchSessionAgentRequest = { sessionId: string; agentRef: string };

/**
 * Returns the session rebound to its new agent.
 *
 * The new agent reports its own commands and configuration during the handshake
 * that the switch performs, so both travel back with the rebound session. A
 * client that only heard about the session would otherwise keep offering the
 * previous agent's models, which the new one cannot honour.
 */
export type SwitchSessionAgentResponse = {
  session: Session;
  availableCommands: Array<import("@agentclientprotocol/sdk").AvailableCommand>;
  configOptions: Array<import("@agentclientprotocol/sdk").SessionConfigOption>;
};

/**
 * Requests the reusable warm provider session backing one chat surface.
 *
 * The request carries no cwd: the backend derives it from `target` on every
 * call, so a worktree that moved or was recreated invalidates the warm entry
 * instead of silently addressing a stale directory.
 */
export type WarmSessionRequest = {
  target: WarmSessionTarget;
  agentRef: string;
};

/**
 * Returns the warm session identifier together with the agent's current configuration.
 */
export type WarmSessionResponse = {
  /**
   * The final Ora session id. It is not persisted until `attachSession`
   * succeeds, so `getSession` and `listSessions` do not report it yet.
   */
  sessionId: string;
  configOptions: Array<import("@agentclientprotocol/sdk").SessionConfigOption>;
};

/**
 * Selects the working directory one warm session is created against.
 *
 * The two variants mirror how Ora resolves a cwd: an existing Task owns either
 * a linked worktree or the project root, while a chat whose Task does not exist
 * yet can only target the project root. Modelling this as an enum keeps callers
 * from having to pass two optional identifiers and guess which one wins.
 */
export type WarmSessionTarget = { "type": "task"; taskId: string } | {
  "type": "projectRoot";
  projectId: string;
};
