// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionOption } from "./acp/permission.js";
import type { StopReason } from "./acp/prompt.js";
import type { SessionUpdate } from "./acp/session.js";
import type { ToolCallUpdate } from "./acp/tool_call.js";

/**
 * Identifies the shared CLI runtime selected for a provider-backed session.
 */
export type AgentCli = "open_code" | "nga" | "code_agent_cli";

/**
 * Groups the model identifiers reported by one currently available CLI.
 */
export type AgentCliModels = { agentCli: AgentCli; models: Array<string> };

/**
 * Creates a provider-backed session on one selected application-scoped CLI.
 */
export type CreateSessionRequest = { taskId: string; agentCli: AgentCli };

/**
 * Returns the created session after the ACP `session/new` handshake succeeds.
 */
export type CreateSessionResponse = { session: Session };

/**
 * Identifies which Ora session record to remove.
 */
export type DeleteSessionRequest = { sessionId: string };

/**
 * Returns the removed Ora session identifier without deleting provider history.
 */
export type DeleteSessionResponse = { sessionId: string };

/**
 * Identifies which session to fetch.
 */
export type GetSessionRequest = { sessionId: string };

/**
 * Returns one session payload after a successful fetch.
 */
export type GetSessionResponse = { session: Session };

/**
 * Requests model catalogs from every CLI without failing on unavailable runtimes.
 */
export type ListAgentModelsRequest = Record<symbol, never>;

/**
 * Returns only CLI groups whose model command completed successfully.
 */
export type ListAgentModelsResponse = { groups: Array<AgentCliModels> };

/**
 * Requests the full visible session list.
 */
export type ListSessionsRequest = Record<symbol, never>;

/**
 * Returns the visible session list.
 */
export type ListSessionsResponse = { sessions: Array<Session> };

/**
 * Streams provider history while keeping JSON-RPC framing private to the backend.
 */
export type LoadSessionEvent =
  | { "type": "session_update"; update: SessionUpdate }
  | { "type": "permission_request" } & SessionPermissionRequest
  | { "type": "completed" };

/**
 * Identifies a stopped session whose provider history should be replayed.
 */
export type LoadSessionRequest = { sessionId: string };

/**
 * Streams one prompt turn and ends with the provider's typed stop reason.
 */
export type PromptSessionEvent =
  | { "type": "session_update"; update: SessionUpdate }
  | { "type": "permission_request" } & SessionPermissionRequest
  | { "type": "completed"; stopReason: StopReason };

/**
 * Carries the text-only prompt supported by the demo surface.
 */
export type PromptSessionRequest = { sessionId: string; text: string };

/**
 * Selects one option for a still-pending permission request.
 */
export type RespondToPermissionRequest = {
  sessionId: string;
  permissionRequestId: string;
  optionId: string;
};

/**
 * Confirms that a permission response was delivered to the agent.
 */
export type RespondToPermissionResponse = Record<symbol, never>;

/**
 * Describes the public session payload without exposing the provider session identifier.
 */
export type Session = {
  id: string;
  taskId: string;
  agentCli: AgentCli;
  status: SessionStatus;
};

/**
 * Exposes an opaque permission request while preserving the agent's typed option payload.
 */
export type SessionPermissionRequest = {
  permissionRequestId: string;
  toolCall: ToolCallUpdate;
  options: Array<PermissionOption>;
};

/**
 * Describes whether a persisted session is registered on its shared CLI connection.
 */
export type SessionStatus = "running" | "stopped";

/**
 * Identifies a running session whose child process should be stopped.
 */
export type StopSessionRequest = { sessionId: string };

/**
 * Returns the stopped public session snapshot.
 */
export type StopSessionResponse = { session: Session };
