// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the shared CLI runtime selected for a provider-backed session.
 */
export type AgentCli =
  | "open_code"
  | "nga"
  | "code_agent_cli"
  | "claude"
  | "codex";

/**
 * Pairs one CLI identity with its current runtime detection status.
 */
export type AgentCliRuntimeStatus = {
  agentCli: AgentCli;
  status: AgentCliStatus;
};

/**
 * Describes the live ACP handshake state of one application-scoped CLI runtime.
 */
export type AgentCliStatus = "ready" | "starting" | "unavailable";

/**
 * Binds one warm session to its owning Task and persists the Ora record.
 */
export type AttachSessionRequest = { sessionId: string; taskId: string };

/**
 * Returns the newly persisted session payload.
 */
export type AttachSessionResponse = {
  session: Session;
  availableCommands: Array<import("@agentclientprotocol/sdk").AvailableCommand>;
};

/**
 * Identifies which Ora session record to remove.
 */
export type DeleteSessionRequest = { sessionId: string };

/**
 * Returns the removed Ora session identifier without deleting provider history.
 */
export type DeleteSessionResponse = { sessionId: string };

/**
 * Requests the live detection status of every application-scoped CLI runtime.
 */
export type GetAgentRuntimeStatusRequest = Record<symbol, never>;

/**
 * Returns the live detection status of every application-scoped CLI runtime.
 */
export type GetAgentRuntimeStatusResponse = {
  statuses: Array<AgentCliRuntimeStatus>;
};

/**
 * Identifies which session to fetch.
 */
export type GetSessionRequest = { sessionId: string };

/**
 * Returns one session payload after a successful fetch.
 */
export type GetSessionResponse = { session: Session };

/**
 * Requests the full visible session list.
 */
export type ListSessionsRequest = Record<symbol, never>;

/**
 * Returns the visible session list.
 */
export type ListSessionsResponse = { sessions: Array<Session> };

/**
 * Replays Ora's recorded history while keeping JSON-RPC framing private to the backend.
 *
 * The stream carries assembled updates read back from Ora's own record, not the
 * provider's replay. `TurnEnded` has no ACP equivalent and exists because a
 * cancelled turn would otherwise be indistinguishable from a completed one —
 * information provider replay never carried.
 */
export type LoadSessionEvent =
  | {
    "type": "session_update";
    update: import("@agentclientprotocol/sdk").SessionUpdate;
  }
  | { "type": "permission_request" } & SessionPermissionRequest
  | {
    "type": "turn_ended";
    stopReason: import("@agentclientprotocol/sdk").StopReason;
  }
  | { "type": "completed" };

/**
 * Identifies a stopped session whose provider history should be replayed.
 */
export type LoadSessionRequest = { sessionId: string };

/**
 * Streams one prompt turn and ends with the provider's typed stop reason.
 */
export type PromptSessionEvent =
  | {
    "type": "session_update";
    update: import("@agentclientprotocol/sdk").SessionUpdate;
  }
  | { "type": "permission_request" } & SessionPermissionRequest
  | {
    "type": "completed";
    stopReason: import("@agentclientprotocol/sdk").StopReason;
  };

/**
 * Carries one or more ACP content blocks to the provider session.
 */
export type PromptSessionRequest = {
  sessionId: string;
  prompt: Array<import("@agentclientprotocol/sdk").ContentBlock>;
};

/**
 * Selects one option for a still-pending permission request.
 */
export type RespondToPermissionRequest = {
  sessionId: string;
  permissionRequestId: string;
  optionId: string;
};

/**
 * Confirms that a permission response was delivered to the agent.
 */
export type RespondToPermissionResponse = Record<symbol, never>;

/**
 * Returns a session whose history writes failed to a writable state.
 *
 * Resuming appends a record of what went missing before accepting new content,
 * so the conversation never contains a gap that cannot be seen.
 */
export type ResumeSessionHistoryRequest = { sessionId: string };

/**
 * Returns the session after its history became writable again.
 */
export type ResumeSessionHistoryResponse = { session: Session };

/**
 * Describes the public session payload without exposing the provider session identifier.
 */
export type Session = {
  id: string;
  taskId: string;
  /**
   * The persisted display title, or `null` until the first acquisition succeeds.
   */
  title: string | null;
  /**
   * The CLI this conversation currently runs on, which switching replaces.
   */
  agentCli: AgentCli;
  status: SessionStatus;
  historyState: SessionHistoryState;
};

/**
 * Reports whether Ora can still extend this session's recorded history.
 *
 * Separate from [`SessionStatus`] on purpose: that says whether the conversation
 * is registered on a CLI connection, this says whether the record of it can
 * still grow. A running session whose disk filled is both at once, and the user
 * has to be told which one broke.
 */
export type SessionHistoryState = { "type": "writable" } | {
  "type": "degraded";
  reason: string;
};

/**
 * Exposes an opaque permission request while preserving the agent's typed option payload.
 */
export type SessionPermissionRequest = {
  permissionRequestId: string;
  toolCall: import("@agentclientprotocol/sdk").ToolCallUpdate;
  options: Array<import("@agentclientprotocol/sdk").PermissionOption>;
};

/**
 * Describes whether a persisted session is registered on its shared CLI connection.
 */
export type SessionStatus = "running" | "stopped";

/**
 * Sets one selectable configuration option on a warm or persisted session.
 *
 * `value` is the chosen option's value id. Only id-valued options are
 * expressible because Ora does not advertise the boolean config-option client
 * capability, so an agent never offers a value this request cannot carry.
 */
export type SetSessionConfigRequest = {
  sessionId: string;
  configId: string;
  value: string;
};

/**
 * Returns the full option set after the agent applies the change.
 */
export type SetSessionConfigResponse = {
  configOptions: Array<import("@agentclientprotocol/sdk").SessionConfigOption>;
};

/**
 * Identifies a running session whose child process should be stopped.
 */
export type StopSessionRequest = { sessionId: string };

/**
 * Returns the stopped public session snapshot.
 */
export type StopSessionResponse = { session: Session };

/**
 * Moves one existing conversation onto a different agent CLI.
 *
 * Only the binding changes: the session keeps its identifier, its task, and the
 * history it has accumulated. The new CLI starts with no context, so Ora's
 * recorded transcript is prepended to the next prompt sent into it.
 */
export type SwitchSessionAgentRequest = {
  sessionId: string;
  agentCli: AgentCli;
  /**
   * Identifies the client surface whose warm session this switch claims.
   *
   * The provider session the new CLI runs on is the one this client already
   * warmed while its picker was showing that CLI's models, and warm entries
   * are keyed by client. Carrying the same value here is what makes the
   * switch claim that entry — including any model chosen on it — rather than
   * build a second session the user never configured.
   */
  clientId: string;
};

/**
 * Returns the session rebound to its new CLI.
 *
 * The new CLI reports its own commands and configuration during the handshake
 * that the switch performs, so both travel back with the rebound session. A
 * client that only heard about the session would otherwise keep offering the
 * previous CLI's models, which the new one cannot honour.
 */
export type SwitchSessionAgentResponse = {
  session: Session;
  availableCommands: Array<import("@agentclientprotocol/sdk").AvailableCommand>;
  configOptions: Array<import("@agentclientprotocol/sdk").SessionConfigOption>;
};

/**
 * Requests the reusable warm provider session backing one chat surface.
 *
 * The request carries no cwd: the backend derives it from `target` on every
 * call, so a worktree that moved or was recreated invalidates the warm entry
 * instead of silently addressing a stale directory.
 */
export type WarmSessionRequest = {
  target: WarmSessionTarget;
  agentCli: AgentCli;
  /**
   * Identifies the client surface that will own the returned session.
   *
   * Warm entries are keyed by this value because one backend can serve
   * several clients (browser tabs against the Web server). Without it two
   * tabs showing the same selection would share one provider session, and
   * whichever attached first would take the other tab's conversation.
   */
  clientId: string;
};

/**
 * Returns the warm session identifier together with the agent's current configuration.
 */
export type WarmSessionResponse = {
  /**
   * The final Ora session id. It is not persisted until `attachSession`
   * succeeds, so `getSession` and `listSessions` do not report it yet.
   */
  sessionId: string;
  configOptions: Array<import("@agentclientprotocol/sdk").SessionConfigOption>;
};

/**
 * Selects the working directory one warm session is created against.
 *
 * The two variants mirror how Ora resolves a cwd: an existing Task owns either
 * a linked worktree or the project root, while a chat whose Task does not exist
 * yet can only target the project root. Modelling this as an enum keeps callers
 * from having to pass two optional identifiers and guess which one wins.
 */
export type WarmSessionTarget = { "type": "task"; taskId: string } | {
  "type": "projectRoot";
  projectId: string;
};
