// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cancels a prepared import session before any commit has been accepted.
 */
export type CancelSkillImportRequest = { sessionId: string };

/**
 * Reports whether a prepared session was cancelled.
 */
export type CancelSkillImportResponse = {
  sessionId: string;
  cancelled: boolean;
};

/**
 * Submits explicit decisions for every conflict candidate and freezes the commit.
 */
export type CommitSkillImportRequest = {
  sessionId: string;
  decisions: Array<SkillImportConflictDecision>;
};

/**
 * Confirms the commit was accepted and is running as a background task.
 */
export type CommitSkillImportResponse = {
  sessionId: string;
  status: SkillImportSessionStatus;
  progress: SkillImportProgress;
};

/**
 * Identifies one prepared import session by its opaque identifier.
 */
export type GetSkillImportSessionRequest = { sessionId: string };

/**
 * Returns one import session with its current status and progress.
 */
export type GetSkillImportSessionResponse = { session: SkillImportSession };

/**
 * Requests the two-phase preparation of one skill import source.
 */
export type PrepareSkillImportRequest = { source: SkillImportSource };

/**
 * Returns the prepared session with its full preview after successful preparation.
 */
export type PrepareSkillImportResponse = { session: SkillImportSession };

/**
 * Describes the existing visible skill a `conflict` candidate would overwrite.
 */
export type SkillConflictInfo = {
  skillId: string;
  updatedAt: bigint;
  description: string;
};

/**
 * One previewed skill candidate discovered in the source.
 */
export type SkillImportCandidate = {
  candidateId: string;
  name: string;
  description: string;
  /**
   * Safe, validated relative path of the candidate's `SKILL.md` within the source.
   */
  sourcePath: string;
  fileCount: number;
  totalSize: bigint;
  status: SkillImportCandidateStatus;
  /**
   * Stable machine-readable reason for `invalid` candidates.
   */
  errorCode: string | null;
  /**
   * Present only for `conflict` candidates.
   */
  existingSkill: SkillConflictInfo | null;
};

/**
 * Classifies one candidate's readiness for commit.
 */
export type SkillImportCandidateStatus = "ready" | "conflict" | "invalid";

/**
 * Carries the explicit decision for one conflict candidate.
 */
export type SkillImportConflictDecision = {
  candidateId: string;
  decision: SkillImportDecision;
};

/**
 * The user-selected handling for one conflict candidate.
 */
export type SkillImportDecision = "skip" | "overwrite";

/**
 * Reports the running progress and completed per-item results of a commit.
 */
export type SkillImportProgress = {
  total: number;
  processed: number;
  results: Array<SkillImportResult>;
};

/**
 * One per-candidate outcome after the commit task processes it.
 */
export type SkillImportResult = {
  candidateId: string;
  name: string;
  status: SkillImportResultStatus;
  /**
   * Stable machine-readable failure reason for `failed` results.
   */
  errorCode: string | null;
};

/**
 * The final outcome of one committed candidate.
 */
export type SkillImportResultStatus =
  | "imported"
  | "overwritten"
  | "skipped"
  | "failed"
  | "staleconflict";

/**
 * One live import session projection shared by every transport.
 */
export type SkillImportSession = {
  sessionId: string;
  status: SkillImportSessionStatus;
  createdAt: bigint;
  candidates: Array<SkillImportCandidate>;
  progress: SkillImportProgress;
};

/**
 * Tracks the lifecycle phase of one import session.
 */
export type SkillImportSessionStatus =
  | "prepared"
  | "committing"
  | "completed"
  | "cancelled";

/**
 * Names the physical source of one import session.
 *
 * Adapters materialize the raw source into OS temporary storage before handing paths here;
 * the paths are never treated as untrusted names for storage.
 */
export type SkillImportSource = { "kind": "folder"; path: string } | {
  "kind": "archive";
  path: string;
  fileName: string;
};
