// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the public fields required to create a skill.
 */
export type CreateSkillRequest = {
  name: string;
  description: string;
  content?: string;
};

/**
 * Returns one created skill.
 */
export type CreateSkillResponse = { skill: Skill };

/**
 * Identifies the visible skill to soft-delete by identifier.
 */
export type DeleteSkillRequest = { skillId: string };

/**
 * Returns the identifier of the skill that was soft-deleted.
 */
export type DeleteSkillResponse = { skillId: string };

/**
 * Identifies the visible skill requested by identifier.
 */
export type GetSkillRequest = { skillId: string };

/**
 * Returns one visible skill.
 */
export type GetSkillResponse = { skill: SkillDetails };

/**
 * Requests every visible skill in stable storage order.
 */
export type ListSkillsRequest = Record<symbol, never>;

/**
 * Returns every visible skill.
 */
export type ListSkillsResponse = { skills: Array<Skill> };

/**
 * Describes a public skill payload without persistence audit metadata.
 */
export type Skill = { id: string; name: string; description: string };

/**
 * Describes one skill together with the Markdown body from its SKILL.md.
 */
export type SkillDetails = {
  id: string;
  name: string;
  description: string;
  content: string;
};

/**
 * Replaces one skill located by its stable identifier.
 */
export type UpdateSkillRequest = {
  skillId: string;
  name: string;
  description: string;
  content?: string;
};

/**
 * Returns the replacement skill.
 */
export type UpdateSkillResponse = { skill: Skill };
