// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects the workspace whose specs should be listed.
 *
 * Omitting `task_id` targets the project root. Supplying it targets that task's
 * workspace, which for worktree-backed tasks is a different branch with a different set
 * of spec files.
 */
export type ListSpecsRequest = { projectId: string; taskId?: string };

/**
 * Returns the resolved workspace, its configured sources, and every discovered document.
 *
 * Sources are returned in configuration order so the catalog can group without inventing
 * its own ordering, and are returned even when empty so the chat view can match paths
 * against their globs.
 */
export type ListSpecsResponse = {
  workspaceRoot: string;
  sources: Array<SpecSource>;
  specs: Array<SpecDocument>;
};

/**
 * Selects one spec document by its workspace-relative path.
 */
export type ReadSpecRequest = {
  projectId: string;
  taskId?: string;
  path: string;
};

/**
 * Returns one spec document together with its raw markdown body.
 */
export type ReadSpecResponse = { spec: SpecDocument; content: string };

/**
 * Describes one spec document surfaced in the catalog.
 */
export type SpecDocument = {
  id: string;
  sourceName: string;
  path: string;
  title: string;
};

/**
 * Declares one discovery rule that groups spec documents under a display name.
 *
 * The glob is part of the public payload because the chat view has to recognize a spec
 * the moment an agent writes one, before the backend index has observed the change.
 */
export type SpecSource = { name: string; glob: string };
