// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests the bounded catalog for one project or task context.
 */
export type GetSpecCatalogRequest = { target: SpecTarget };

/**
 * Carries one project-level source override in an atomic replacement request.
 */
export type ProjectSpecSourceOverride = {
  relativePath: string;
  workflow: SpecWorkflow;
  visibility: SpecSourceVisibility;
};

/**
 * Requests one catalog-authorized Markdown document.
 */
export type ReadSpecRequest = { target: SpecTarget; relativePath: string };

/**
 * Returns the raw, read-only Markdown payload and its exact size.
 */
export type ReadSpecResponse = {
  relativePath: string;
  content: string;
  byteSize: number;
};

/**
 * Validates an absolute directory selected by the existing platform picker.
 */
export type ResolveSpecSourceRequest = {
  target: SpecTarget;
  absolutePath: string;
};

/**
 * Returns the normalized source path and workflow inferred from its segments.
 */
export type ResolveSpecSourceResponse = {
  relativePath: string;
  workflow: SpecWorkflow;
};

/**
 * Returns source state plus the bounded Markdown document index.
 */
export type SpecCatalogResponse = {
  sources: Array<SpecSource>;
  documents: Array<SpecDocument>;
  truncated: boolean;
};

/**
 * Describes one Markdown document assigned to an enabled source.
 */
export type SpecDocument = {
  relativePath: string;
  sourceRelativePath: string;
  workflow: SpecWorkflow;
  byteSize: number;
};

/**
 * Describes one effective or disabled specification source in the selected context.
 */
export type SpecSource = {
  relativePath: string;
  workflow: SpecWorkflow;
  origin: SpecSourceOrigin;
  visibility: SpecSourceVisibility;
  availability: SpecSourceAvailability;
};

/**
 * Records whether a configured source exists in the selected checkout.
 */
export type SpecSourceAvailability = "available" | "missing";

/**
 * Records whether a source came from Ora defaults, discovery, or an explicit user choice.
 */
export type SpecSourceOrigin = "default" | "discovered" | "manual";

/**
 * Records whether a source participates in the effective catalog.
 */
export type SpecSourceVisibility = "enabled" | "disabled";

/**
 * Selects the project checkout or task workspace whose specification documents are managed.
 */
export type SpecTarget = { "kind": "project"; projectId: string } | {
  "kind": "task";
  taskId: string;
};

/**
 * Identifies the workflow that owns a specification source.
 */
export type SpecWorkflow =
  | { "kind": "open_spec" }
  | { "kind": "superpowers" }
  | { "kind": "custom"; name: string };

/**
 * Atomically replaces all source overrides owned by one project.
 */
export type UpdateProjectSpecSourcesRequest = {
  projectId: string;
  sources: Array<ProjectSpecSourceOverride>;
};

/**
 * Returns the persisted replacement so adapters share one authoritative representation.
 */
export type UpdateProjectSpecSourcesResponse = {
  sources: Array<ProjectSpecSourceOverride>;
};

/**
 * Starts specification-aware workspace file monitoring for one target.
 */
export type WatchSpecsRequest = { target: SpecTarget };
