// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the app-facing payload for task creation requests.
 */
export type CreateTaskRequest = {
  projectId: string;
  title: string;
  status: TaskStatus;
  workspaceMode?: TaskWorkspaceMode;
};

/**
 * Returns the created task after a successful create request.
 */
export type CreateTaskResponse = { task: Task };

/**
 * Identifies which task to delete.
 */
export type DeleteTaskRequest = { taskId: string };

/**
 * Returns the deleted task identifier after a successful delete request.
 */
export type DeleteTaskResponse = { taskId: string };

/**
 * Identifies which task to fetch.
 */
export type GetTaskRequest = { taskId: string };

/**
 * Returns one task payload after a successful fetch.
 */
export type GetTaskResponse = { task: Task };

/**
 * Requests the full visible task list.
 */
export type ListTasksRequest = Record<symbol, never>;

/**
 * Returns the visible task list.
 */
export type ListTasksResponse = { tasks: Array<Task> };

/**
 * Describes the public task payload shared across adapter responses.
 */
export type Task = {
  id: string;
  projectId: string;
  title: string;
  status: TaskStatus;
  workspaceMode: TaskWorkspaceMode;
};

/**
 * Describes the public task status shared across adapter boundaries.
 */
export type TaskStatus = "todo" | "doing" | "done";

/**
 * Selects the filesystem context used when a task starts an agent session.
 */
export type TaskWorkspaceMode = "worktree" | "project_root";

/**
 * Carries the full replacement payload for task updates in the first slice.
 */
export type UpdateTaskRequest = {
  taskId: string;
  title: string;
  status: TaskStatus;
};

/**
 * Returns the updated task after a successful update request.
 */
export type UpdateTaskResponse = { task: Task };
