// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Commits every current change in one task-owned worktree.
 */
export type CommitTaskChangesRequest = { taskId: string; message: string };

/**
 * Returns the commit created from the task worktree.
 */
export type CommitTaskChangesResponse = { commitId: string; summary: string };

/**
 * Creates one line-anchored root discussion for the current task diff.
 */
export type CreateTaskDiffCommentRequest = {
  taskId: string;
  scope: TaskDiffScope;
  anchor: TaskDiffCommentAnchor;
  body: string;
};

/**
 * Returns the newly persisted root discussion.
 */
export type CreateTaskDiffCommentResponse = { comment: TaskDiffComment };

/**
 * Identifies which task diff should be computed.
 */
export type GetTaskDiffRequest = { taskId: string; scope: TaskDiffScope };

/**
 * Returns one standard unified patch and the revisions needed to anchor review state.
 */
export type GetTaskDiffResponse = {
  baseCommitId: string;
  headCommitId: string;
  diffId: string;
  patch: string;
};

/**
 * Identifies which task discussion messages should be listed.
 */
export type ListTaskDiffCommentsRequest = { taskId: string };

/**
 * Returns every visible root discussion and reply for one task.
 */
export type ListTaskDiffCommentsResponse = { comments: Array<TaskDiffComment> };

/**
 * Pushes the current task branch to its default remote.
 */
export type PushTaskBranchRequest = { taskId: string };

/**
 * Returns the branch and remote updated by a successful push.
 */
export type PushTaskBranchResponse = { branchName: string; remoteName: string };

/**
 * Adds a reply beneath an existing discussion message in the same task.
 */
export type ReplyTaskDiffCommentRequest = {
  taskId: string;
  commentId: string;
  body: string;
};

/**
 * Returns the newly persisted reply message.
 */
export type ReplyTaskDiffCommentResponse = { comment: TaskDiffComment };

/**
 * Replaces the open/resolved status of one root diff discussion.
 */
export type SetTaskDiffCommentStatusRequest = {
  taskId: string;
  commentId: string;
  status: TaskDiffThreadStatus;
};

/**
 * Returns the root discussion after its status changes.
 */
export type SetTaskDiffCommentStatusResponse = { comment: TaskDiffComment };

/**
 * Represents one task diff discussion message returned to the frontend.
 */
export type TaskDiffComment = {
  id: string;
  taskId: string;
  kind: TaskDiffCommentKind;
  body: string;
  createdAt: number;
  updatedAt: number;
};

/**
 * Anchors a root discussion to one line range in a stable diff snapshot.
 */
export type TaskDiffCommentAnchor = {
  diffId: string;
  /**
   * Uses the old path on the old side and the new path on the new side for renamed files.
   */
  path: string;
  side: TaskDiffSide;
  startLine: number;
  endLine: number;
  hunkHeader: string;
  lineContent: string;
};

/**
 * Distinguishes anchored root discussions from reply messages in public responses.
 */
export type TaskDiffCommentKind = {
  "kind": "thread";
  anchor: TaskDiffCommentAnchor;
  status: TaskDiffThreadStatus;
} | { "kind": "reply"; parentCommentId: string };

/**
 * Selects which Git layer should be rendered in the task review surface.
 */
export type TaskDiffScope = "branch" | "unstaged" | "staged" | "committed";

/**
 * Selects the old or new side of a two-way task diff for comment anchoring.
 */
export type TaskDiffSide = "old" | "new";

/**
 * Captures whether a diff discussion still requires attention.
 */
export type TaskDiffThreadStatus = "open" | "resolved";
