// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Commits every current change in one workspace's checkout.
 */
export type CommitWorkspaceChangesRequest = {
  workspaceId: string;
  message: string;
};

/**
 * Returns the commit created from the workspace checkout.
 */
export type CommitWorkspaceChangesResponse = {
  commitId: string;
  summary: string;
};

/**
 * Identifies which workspace diff should be computed.
 */
export type GetWorkspaceDiffRequest = {
  workspaceId: string;
  scope: WorkspaceDiffScope;
};

/**
 * Returns one standard unified patch and the revisions needed to render it.
 *
 * `base_commit_id` is absent when the workspace has no recorded baseline (a
 * project's main checkout, or a historical worktree whose creation commit was
 * never recorded) — only meaningful for the `Branch`/`Committed` scopes.
 */
export type GetWorkspaceDiffResponse = {
  baseCommitId: string | null;
  headCommitId: string;
  patch: string;
};

/**
 * Pushes the current workspace branch to its default remote.
 */
export type PushWorkspaceBranchRequest = { workspaceId: string };

/**
 * Returns the branch and remote updated by a successful push.
 */
export type PushWorkspaceBranchResponse = {
  branchName: string;
  remoteName: string;
};

/**
 * Selects which Git layer should be rendered in the workspace review surface.
 */
export type WorkspaceDiffScope = "branch" | "unstaged" | "staged" | "committed";
