// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Switches the published version pointer and syncs the draft.
 */
export type ActivateWorkflowRequest = {
  workflowId: string;
  snapshotId: string;
};

/**
 * Returns the updated draft snapshot after activation.
 */
export type ActivateWorkflowResponse = { snapshot: WorkflowSnapshot };

/**
 * Carries the fields required to create a workflow with an optional initial graph.
 */
export type CreateWorkflowRequest = { name: string; graph: string | null };

/**
 * Returns the created workflow and its initial draft snapshot.
 */
export type CreateWorkflowResponse = {
  workflow: Workflow;
  draft: WorkflowSnapshot;
};

/**
 * Identifies the workflow and version to soft-delete.
 */
export type DeleteSnapshotRequest = { workflowId: string; version: string };

/**
 * Returns the identifiers of the soft-deleted snapshot.
 */
export type DeleteSnapshotResponse = { snapshotId: string; version: string };

/**
 * Identifies the workflow to soft-delete by its stable identifier.
 */
export type DeleteWorkflowRequest = { workflowId: string };

/**
 * Returns the identifier of the workflow that was soft-deleted.
 */
export type DeleteWorkflowResponse = { workflowId: string };

/**
 * Identifies the workflow whose draft snapshot to retrieve.
 */
export type GetDraftRequest = { workflowId: string };

/**
 * Returns the draft snapshot including its full graph.
 */
export type GetDraftResponse = { snapshot: WorkflowSnapshot };

/**
 * Identifies the workflow and version to retrieve.
 */
export type GetVersionRequest = { workflowId: string; version: string };

/**
 * Returns the snapshot for the specified version including its full graph.
 */
export type GetVersionResponse = { snapshot: WorkflowSnapshot };

/**
 * Identifies the workflow to retrieve by its stable identifier.
 */
export type GetWorkflowRequest = { workflowId: string };

/**
 * Returns the full workflow detail including draft and published snapshot.
 */
export type GetWorkflowResponse = {
  workflow: Workflow;
  draft: WorkflowSnapshot;
  published: WorkflowSnapshot | null;
};

/**
 * Identifies a snapshot by its stable identifier, independent of its workflow or version key.
 */
export type GetWorkflowSnapshotRequest = { snapshotId: string };

/**
 * Returns the snapshot including its full frozen graph.
 */
export type GetWorkflowSnapshotResponse = { snapshot: WorkflowSnapshot };

/**
 * Identifies the workflow whose version history to retrieve.
 */
export type ListVersionsRequest = { workflowId: string };

/**
 * Returns the list of published (non-draft, non-deleted) version summaries.
 */
export type ListVersionsResponse = { versions: Array<WorkflowVersion> };

/**
 * Requests every visible workflow, newest created first.
 */
export type ListWorkflowsRequest = Record<symbol, never>;

/**
 * Returns every visible workflow summary.
 */
export type ListWorkflowsResponse = { workflows: Array<WorkflowSummary> };

/**
 * Publishes the current draft as an immutable snapshot, with an optional user-provided version.
 */
export type PublishWorkflowRequest = {
  workflowId: string;
  version: string | null;
};

/**
 * Returns the newly created published snapshot.
 */
export type PublishWorkflowResponse = { snapshot: WorkflowSnapshot };

/**
 * Copies the graph from a historical snapshot into the draft.
 */
export type RollbackWorkflowRequest = {
  workflowId: string;
  snapshotId: string;
};

/**
 * Returns the updated draft snapshot after rollback.
 */
export type RollbackWorkflowResponse = { snapshot: WorkflowSnapshot };

/**
 * Replaces the graph of the draft snapshot.
 */
export type UpdateDraftRequest = { workflowId: string; graph: string };

/**
 * Returns the updated draft snapshot.
 */
export type UpdateDraftResponse = { snapshot: WorkflowSnapshot };

/**
 * Replaces the name of an existing workflow.
 */
export type UpdateWorkflowRequest = { workflowId: string; name: string };

/**
 * Returns the updated workflow.
 */
export type UpdateWorkflowResponse = { workflow: Workflow };

/**
 * Public workflow summary without persistence audit metadata.
 */
export type Workflow = {
  id: string;
  namespace: string;
  name: string;
  publishedSnapshotId: string | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Public snapshot payload including the full graph.
 */
export type WorkflowSnapshot = {
  id: string;
  workflowId: string;
  version: string;
  graph: string;
  createdAt: bigint;
  updatedAt: bigint | null;
};

/**
 * Lightweight workflow summary for list views — no graph data.
 */
export type WorkflowSummary = {
  id: string;
  namespace: string;
  name: string;
  publishedVersion: string | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Version metadata without graph content.
 */
export type WorkflowVersion = {
  id: string;
  version: string;
  createdAt: bigint;
};
