// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the running run whose node sessions should be stopped and run cancelled.
 */
export type CancelWorkflowRunRequest = { runId: string };

/**
 * Returns the cancelled run.
 */
export type CancelWorkflowRunResponse = { run: WorkflowRun };

/**
 * Carries the fields required to create a workflow run against a published snapshot.
 *
 * The project is required because the run-task owns a `tasks.project_id`; workflows themselves
 * are not project-scoped.
 */
export type CreateWorkflowRunRequest = {
  projectId: string;
  workflowId: string;
  snapshotId?: string;
  kickoffInput?: string;
  name?: string;
  /**
   * Git reference the run-task's worktree is created from; defaults to the main branch.
   */
  baseBranch?: string;
};

/**
 * Returns the created run and its associated run-task identifier.
 */
export type CreateWorkflowRunResponse = { run: WorkflowRun; taskId: string };

/**
 * Identifies the workflow run to soft-delete.
 */
export type DeleteWorkflowRunRequest = { runId: string };

/**
 * Returns the identifier of the soft-deleted run.
 */
export type DeleteWorkflowRunResponse = { runId: string };

/**
 * Identifies the workflow run to retrieve by its stable identifier.
 */
export type GetWorkflowRunRequest = { runId: string };

/**
 * Returns the full run detail including its display name and node runs.
 */
export type GetWorkflowRunResponse = {
  run: WorkflowRun;
  name: string;
  projectId: string;
  taskId: string;
  nodes: Array<WorkflowNodeRun>;
};

/**
 * Identifies the run whose node-run history to retrieve.
 */
export type ListWorkflowNodeRunsRequest = { runId: string };

/**
 * Returns the node-run records of one run.
 */
export type ListWorkflowNodeRunsResponse = { nodes: Array<WorkflowNodeRun> };

/**
 * Requests the workflow run summaries for one workflow.
 */
export type ListWorkflowRunsByWorkflowRequest = { workflowId: string };

/**
 * Returns the visible run summaries for the workflow.
 */
export type ListWorkflowRunsByWorkflowResponse = {
  runs: Array<WorkflowRunSummary>;
};

/**
 * Requests the workflow run summaries for one project.
 */
export type ListWorkflowRunsRequest = { projectId: string };

/**
 * Returns the visible run summaries for the project.
 */
export type ListWorkflowRunsResponse = { runs: Array<WorkflowRunSummary> };

/**
 * Identifies the non-running run to reset and re-run from its start node.
 */
export type RestartWorkflowRunRequest = { runId: string };

/**
 * Returns the reset and re-running run.
 */
export type RestartWorkflowRunResponse = { run: WorkflowRun };

/**
 * Identifies the run to start executing against its frozen snapshot graph.
 */
export type StartWorkflowRunRequest = { runId: string };

/**
 * Returns the run after starting (or idempotently its current state).
 */
export type StartWorkflowRunResponse = { run: WorkflowRun };

/**
 * Sets the kickoff input of a pending run, used as the start node's input on start.
 */
export type UpdateWorkflowRunInputRequest = {
  runId: string;
  input: string | null;
};

/**
 * Returns the run with its updated input.
 */
export type UpdateWorkflowRunInputResponse = { run: WorkflowRun };

/**
 * Public node-run payload without persistence audit metadata.
 */
export type WorkflowNodeRun = {
  id: string;
  runId: string;
  nodeId: string;
  nodeType: string;
  sessionId: string | null;
  status: WorkflowNodeStatus;
  input: string | null;
  output: string | null;
  error: string | null;
  payload: string | null;
  startedAt: bigint | null;
  finishedAt: bigint | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Describes the lifecycle state of one node execution in the public contract.
 */
export type WorkflowNodeStatus =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled";

/**
 * Public workflow run payload without persistence audit metadata.
 */
export type WorkflowRun = {
  id: string;
  workflowId: string;
  snapshotId: string;
  status: WorkflowRunStatus;
  state: string | null;
  input: string | null;
  output: string | null;
  error: string | null;
  payload: string | null;
  startedAt: bigint | null;
  finishedAt: bigint | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Describes the lifecycle state of a workflow run in the public contract.
 */
export type WorkflowRunStatus =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled";

/**
 * Lightweight run summary for list views — name is the associated task title.
 */
export type WorkflowRunSummary = {
  id: string;
  name: string;
  projectId: string;
  workflowId: string;
  status: WorkflowRunStatus;
  startedAt: bigint | null;
  finishedAt: bigint | null;
  createdAt: bigint;
};
