[package]
name = "ora-surface"
version.workspace = true
edition.workspace = true

[lib]
name = "ora_surface"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
ora-domain = { workspace = true }
ora-logging = { workspace = true }
ora-plugin-manager = { workspace = true }
ora-plugin-manifest = { workspace = true }
ora-utils = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
time = { workspace = true }
url = { workspace = true }

[dev-dependencies]
ora-plugin-config = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
