[package]
name = "ora-fs"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
notify = { workspace = true }
ora-process = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "time"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
