[package]
name = "ora-utils"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["validation"]
archive = ["dep:zip", "dep:tar", "dep:flate2"]
http = ["dep:url", "dep:sha2"]
http-reqwest = ["http", "dep:reqwest", "dep:tokio"]
validation = ["dep:sha2", "dep:quick-xml"]

[dependencies]
flate2 = { workspace = true, optional = true }
quick-xml = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
serde = { workspace = true }
sha2 = { workspace = true, optional = true }
tar = { workspace = true, optional = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true, features = ["time"] }
unicode-normalization = { workspace = true }
url = { workspace = true, optional = true }
zip = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[dev-dependencies]
flate2 = { workspace = true }
futures = { workspace = true }
pretty_assertions = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "io-util"] }
zip = { workspace = true }
