import type { ComponentType } from "react";
import {
  IconBook2,
  IconBrandChrome,
  IconBrandDocker,
  IconBrandFigma,
  IconBrandGithub,
  IconBrandNotion,
  IconBrandSlack,
  IconBug,
  IconChartBar,
  IconDatabase,
  IconLayoutKanban,
  IconPalette,
  IconRocket,
  IconTestPipe,
  IconTicket,
} from "@tabler/icons-react";
import { OpenAiLogo } from "../chat/provider-logos";
import { ClaudeMark, OpenCodeMark } from "./plugin-marks";

/** A plugin's brand mark. Tabler icons and the hand-drawn marks both satisfy this. */
export type PluginMark = ComponentType<{ className?: string }>;

/** Whether a plugin comes from the shared marketplace or the signed-in user's own space. */
export type PluginCollection = "public" | "personal";

export interface PluginEntry {
  id: string;
  /** Product names are proper nouns, so they stay untranslated. */
  name: string;
  publisher: string;
  /** Reverse-DNS id shown verbatim in the detail pane's info table. */
  identifier: string;
  version: string;
  /** ISO date formatted with the active locale, which keeps it out of the translation catalog. */
  updated: string;
  size: string;
  collection: PluginCollection;
  /** Featured plugins lead the browse grid before the rest of the collection. */
  featured: boolean;
  categoryKey: string;
  capabilityKeys: string[];
  mark: PluginMark;
  /** Tailwind text colour for the mark, which is drawn bare so brands read at 24px. */
  tone: string;
  summaryKey: string;
  /** Skill names surfaced in the detail pane; only the first three plugins ship more than one. */
  skills: string[];
}

/** Plugins wired into the prototype. Everything else in the catalog is a browse-only placeholder. */
export const DEFAULT_INSTALLED_PLUGIN_IDS = ["opencode", "claude", "codex"];

/**
 * The hard-coded plugin marketplace. No backend contract exposes plugins yet, so the
 * settings pane reads this catalog directly and keeps install state in component state.
 */
export const PLUGIN_CATALOG: PluginEntry[] = [
  {
    id: "opencode",
    name: "OpenCode",
    publisher: "SST",
    identifier: "sst.opencode",
    version: "0.4.12",
    updated: "2026-07-16",
    size: "18.4 MB",
    collection: "public",
    featured: true,
    categoryKey: "settings.plugins.category.coding",
    capabilityKeys: ["settings.plugins.capability.interactive", "settings.plugins.capability.write", "settings.plugins.capability.terminal"],
    mark: OpenCodeMark,
    tone: "text-neutral-900 dark:text-neutral-100",
    summaryKey: "settings.plugins.catalog.opencode",
    skills: ["OpenCode", "Terminal"],
  },
  {
    id: "claude",
    name: "Claude Code",
    publisher: "Anthropic",
    identifier: "anthropic.claude-code",
    version: "2.1.8",
    updated: "2026-07-21",
    size: "42.6 MB",
    collection: "public",
    featured: true,
    categoryKey: "settings.plugins.category.coding",
    capabilityKeys: ["settings.plugins.capability.interactive", "settings.plugins.capability.write", "settings.plugins.capability.terminal"],
    mark: ClaudeMark,
    tone: "text-[#D97757]",
    summaryKey: "settings.plugins.catalog.claude",
    skills: ["Claude Code", "Subagents", "Skills"],
  },
  {
    id: "codex",
    name: "Codex",
    publisher: "OpenAI",
    identifier: "openai.codex",
    version: "1.6.0",
    updated: "2026-07-19",
    size: "31.2 MB",
    collection: "public",
    featured: true,
    categoryKey: "settings.plugins.category.coding",
    capabilityKeys: ["settings.plugins.capability.interactive", "settings.plugins.capability.write"],
    mark: OpenAiLogo,
    tone: "text-emerald-600 dark:text-emerald-400",
    summaryKey: "settings.plugins.catalog.codex",
    skills: ["Codex", "Code Review"],
  },
  {
    id: "github",
    name: "GitHub",
    publisher: "GitHub",
    identifier: "github.github",
    version: "3.2.1",
    updated: "2026-07-09",
    size: "6.8 MB",
    collection: "public",
    featured: true,
    categoryKey: "settings.plugins.category.devtools",
    capabilityKeys: ["settings.plugins.capability.read", "settings.plugins.capability.network"],
    mark: IconBrandGithub,
    tone: "text-zinc-700 dark:text-zinc-300",
    summaryKey: "settings.plugins.catalog.github",
    skills: ["GitHub"],
  },
  {
    id: "devtools",
    name: "Chrome DevTools",
    publisher: "Google",
    identifier: "google.chrome-devtools",
    version: "1.1.9",
    updated: "2026-07-17",
    size: "9.6 MB",
    collection: "public",
    featured: true,
    categoryKey: "settings.plugins.category.devtools",
    capabilityKeys: ["settings.plugins.capability.interactive", "settings.plugins.capability.read"],
    mark: IconBrandChrome,
    tone: "text-amber-600 dark:text-amber-400",
    summaryKey: "settings.plugins.catalog.devtools",
    skills: ["Chrome DevTools"],
  },
  {
    id: "analytics",
    name: "Data Analytics",
    publisher: "Ora Labs",
    identifier: "ora.data-analytics",
    version: "0.7.2",
    updated: "2026-07-11",
    size: "7.4 MB",
    collection: "public",
    featured: true,
    categoryKey: "settings.plugins.category.data",
    capabilityKeys: ["settings.plugins.capability.read", "settings.plugins.capability.write"],
    mark: IconChartBar,
    tone: "text-teal-600 dark:text-teal-400",
    summaryKey: "settings.plugins.catalog.analytics",
    skills: ["Data Analytics"],
  },
  {
    id: "figma",
    name: "Figma",
    publisher: "Figma",
    identifier: "figma.figma",
    version: "2.0.4",
    updated: "2026-06-28",
    size: "4.1 MB",
    collection: "public",
    featured: false,
    categoryKey: "settings.plugins.category.design",
    capabilityKeys: ["settings.plugins.capability.read", "settings.plugins.capability.network"],
    mark: IconBrandFigma,
    tone: "text-violet-600 dark:text-violet-400",
    summaryKey: "settings.plugins.catalog.figma",
    skills: ["Figma"],
  },
  {
    id: "linear",
    name: "Linear",
    publisher: "Linear",
    identifier: "linear.linear",
    version: "1.9.0",
    updated: "2026-07-12",
    size: "2.7 MB",
    collection: "public",
    featured: false,
    categoryKey: "settings.plugins.category.productivity",
    capabilityKeys: ["settings.plugins.capability.read", "settings.plugins.capability.write", "settings.plugins.capability.network"],
    mark: IconLayoutKanban,
    tone: "text-indigo-600 dark:text-indigo-400",
    summaryKey: "settings.plugins.catalog.linear",
    skills: ["Linear"],
  },
  {
    id: "notion",
    name: "Notion",
    publisher: "Notion Labs",
    identifier: "notion.notion",
    version: "4.3.2",
    updated: "2026-07-02",
    size: "5.5 MB",
    collection: "public",
    featured: false,
    categoryKey: "settings.plugins.category.productivity",
    capabilityKeys: ["settings.plugins.capability.read", "settings.plugins.capability.write", "settings.plugins.capability.network"],
    mark: IconBrandNotion,
    tone: "text-slate-700 dark:text-slate-300",
    summaryKey: "settings.plugins.catalog.notion",
    skills: ["Notion"],
  },
  {
    id: "slack",
    name: "Slack",
    publisher: "Slack",
    identifier: "slack.slack",
    version: "2.6.1",
    updated: "2026-06-21",
    size: "3.9 MB",
    collection: "public",
    featured: false,
    categoryKey: "settings.plugins.category.productivity",
    capabilityKeys: ["settings.plugins.capability.read", "settings.plugins.capability.write", "settings.plugins.capability.network"],
    mark: IconBrandSlack,
    tone: "text-rose-600 dark:text-rose-400",
    summaryKey: "settings.plugins.catalog.slack",
    skills: ["Slack"],
  },
  {
    id: "postgres",
    name: "Postgres",
    publisher: "Ora Labs",
    identifier: "ora.postgres",
    version: "0.9.7",
    updated: "2026-07-05",
    size: "8.2 MB",
    collection: "public",
    featured: false,
    categoryKey: "settings.plugins.category.data",
    capabilityKeys: ["settings.plugins.capability.read", "settings.plugins.capability.write"],
    mark: IconDatabase,
    tone: "text-blue-600 dark:text-blue-400",
    summaryKey: "settings.plugins.catalog.postgres",
    skills: ["Postgres"],
  },
  {
    id: "docker",
    name: "Docker",
    publisher: "Docker",
    identifier: "docker.docker",
    version: "1.4.0",
    updated: "2026-06-30",
    size: "12.1 MB",
    collection: "public",
    featured: false,
    categoryKey: "settings.plugins.category.devtools",
    capabilityKeys: ["settings.plugins.capability.interactive", "settings.plugins.capability.terminal"],
    mark: IconBrandDocker,
    tone: "text-cyan-600 dark:text-cyan-400",
    summaryKey: "settings.plugins.catalog.docker",
    skills: ["Docker"],
  },
  {
    id: "sentry",
    name: "Sentry",
    publisher: "Sentry",
    identifier: "sentry.sentry",
    version: "2.2.5",
    updated: "2026-07-14",
    size: "3.3 MB",
    collection: "public",
    featured: false,
    categoryKey: "settings.plugins.category.devtools",
    capabilityKeys: ["settings.plugins.capability.read", "settings.plugins.capability.network"],
    mark: IconBug,
    tone: "text-purple-600 dark:text-purple-400",
    summaryKey: "settings.plugins.catalog.sentry",
    skills: ["Sentry"],
  },
  {
    id: "playwright",
    name: "Playwright",
    publisher: "Microsoft",
    identifier: "microsoft.playwright",
    version: "1.52.0",
    updated: "2026-07-08",
    size: "22.4 MB",
    collection: "public",
    featured: false,
    categoryKey: "settings.plugins.category.devtools",
    capabilityKeys: ["settings.plugins.capability.interactive", "settings.plugins.capability.terminal"],
    mark: IconTestPipe,
    tone: "text-green-600 dark:text-green-400",
    summaryKey: "settings.plugins.catalog.playwright",
    skills: ["Playwright"],
  },
  {
    id: "jira",
    name: "Jira",
    publisher: "Atlassian",
    identifier: "atlassian.jira",
    version: "5.1.3",
    updated: "2026-06-24",
    size: "4.7 MB",
    collection: "public",
    featured: false,
    categoryKey: "settings.plugins.category.productivity",
    capabilityKeys: ["settings.plugins.capability.read", "settings.plugins.capability.write", "settings.plugins.capability.network"],
    mark: IconTicket,
    tone: "text-blue-700 dark:text-blue-400",
    summaryKey: "settings.plugins.catalog.jira",
    skills: ["Jira"],
  },
  {
    id: "runbooks",
    name: "Team Runbooks",
    publisher: "Internal",
    identifier: "internal.team-runbooks",
    version: "0.3.0",
    updated: "2026-07-20",
    size: "1.2 MB",
    collection: "personal",
    featured: true,
    categoryKey: "settings.plugins.category.productivity",
    capabilityKeys: ["settings.plugins.capability.read"],
    mark: IconBook2,
    tone: "text-stone-700 dark:text-stone-300",
    summaryKey: "settings.plugins.catalog.runbooks",
    skills: ["Team Runbooks"],
  },
  {
    id: "deploybot",
    name: "Deploy Bot",
    publisher: "Internal",
    identifier: "internal.deploy-bot",
    version: "1.0.4",
    updated: "2026-07-18",
    size: "2.1 MB",
    collection: "personal",
    featured: true,
    categoryKey: "settings.plugins.category.devtools",
    capabilityKeys: ["settings.plugins.capability.interactive", "settings.plugins.capability.terminal"],
    mark: IconRocket,
    tone: "text-orange-700 dark:text-orange-400",
    summaryKey: "settings.plugins.catalog.deploybot",
    skills: ["Deploy Bot"],
  },
  {
    id: "tokens",
    name: "Design Tokens",
    publisher: "Internal",
    identifier: "internal.design-tokens",
    version: "0.5.6",
    updated: "2026-07-06",
    size: "0.9 MB",
    collection: "personal",
    featured: false,
    categoryKey: "settings.plugins.category.design",
    capabilityKeys: ["settings.plugins.capability.read", "settings.plugins.capability.write"],
    mark: IconPalette,
    tone: "text-pink-600 dark:text-pink-400",
    summaryKey: "settings.plugins.catalog.tokens",
    skills: ["Design Tokens"],
  },
];

/** Looks a plugin up by id; browse and detail views both address plugins by id alone. */
export function findPlugin(id: string): PluginEntry | undefined {
  return PLUGIN_CATALOG.find((plugin) => plugin.id === id);
}
