// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `$/activate` request params (§12.8).
 */
export type ActivateParams = { reason: ActivateReason };

/**
 * Why the Host is activating the plugin (§12.8).
 */
export type ActivateReason = "lazyInvocation" | "manualStart";

/**
 * `$/activate` response (§12.8).
 *
 * `providers` must be deep-equal to the manifest `contributes.agents` (canonical id sort); extra,
 * missing, duplicate or version-mismatched providers are `ActivationFailed`.
 */
export type ActivateResult = { providers: Array<ActivatedProvider> };

/**
 * One provider descriptor returned by `$/activate`.
 */
export type ActivatedProvider = {
  id: AgentProviderId;
  contractVersion: number;
};

/**
 * Availability of one installation.
 */
export type AgentAvailability = { "type": "available" } | {
  "type": "unavailable";
  reason: string;
};

/**
 * The `data` object for an `-32000` agent business failure (§16.1, §13.2).
 *
 * Deserialized from [`JsonRpcError::data`] when `code` is `agent::AGENT_BUSINESS_ERROR_CODE`.
 * Authors cannot create `ProviderFailure`; the bootstrap synthesizes it for raw throws/rejects.
 */
export type AgentBusinessErrorData = {
  kind: AgentBusinessFailureKind;
  retryable: boolean;
  details?: JsonObject;
};

/**
 * Closed set of agent business failure kinds carried in `-32000` error `data.kind`.
 *
 * `ProviderFailure` is bootstrap-reserved: plugin authors cannot create it; the bootstrap
 * synthesizes it for raw throws/rejects/generator failures.
 */
export type AgentBusinessFailureKind =
  | "agentUnavailable"
  | "authenticationRequired"
  | "invalidAgentConfiguration"
  | "installationNotFound"
  | "conversationNotFound"
  | "unsupportedAgentCapability"
  | "invalidState"
  | "permissionDenied"
  | "cursorExpired"
  | "agentProcessFailed"
  | "providerFailure";

/**
 * One configuration item. Secrets can only be represented as `redacted` (no raw value variant).
 */
export type AgentConfigurationItem = {
  key: AgentConfigurationKey;
  displayName: string;
  source: AgentResourceSource;
  value: AgentConfigurationValue;
};

/**
 * A configuration key surfaced by an agent provider, with its own 512-byte ASCII grammar.
 */
export type AgentConfigurationKey = string;

/**
 * The (possibly redacted/unset) value of one configuration item.
 */
export type AgentConfigurationValue =
  | { "type": "unset" }
  | { "type": "redacted" }
  | { "type": "boolean"; value: boolean }
  | { "type": "number"; value: FiniteJsonNumber }
  | { "type": "string"; value: string }
  | { "type": "stringList"; value: Array<string> };

/**
 * One agent contribution declared in the manifest.
 */
export type AgentContribution = {
  id: AgentProviderId;
  displayName: string;
  contractVersion: number;
};

/**
 * All agent contributions of one agent-kind manifest.
 */
export type AgentContributions = { agents: Array<AgentContribution> };

/**
 * Plugin-issued conversation identity, scoped to its producing installation and generation.
 */
export type AgentConversationId = string;

/**
 * A conversation summary.
 */
export type AgentConversationSummary = {
  conversationId: AgentConversationId;
  title?: string;
  updatedAt?: Rfc3339Timestamp;
};

/**
 * Opaque pagination cursor bound to `(provider, generation)`; never crosses a generation.
 */
export type AgentCursor = string;

/**
 * A discovery diagnostic emitted alongside installations.
 */
export type AgentDiscoveryDiagnostic = {
  kind: AgentDiscoveryDiagnosticKind;
  message: string;
};

/**
 * Stable classification of a discovery diagnostic.
 */
export type AgentDiscoveryDiagnosticKind =
  | "notFound"
  | "permissionDenied"
  | "probeFailed";

/**
 * One streaming event from `agent.startConversation` / `agent.sendMessage`.
 */
export type AgentEvent =
  | { "kind": "conversationStarted"; conversationId: AgentConversationId }
  | { "kind": "textDelta"; channel: AgentOutputChannel; text: string }
  | { "kind": "status"; phase: string; message?: string }
  | {
    "kind": "toolCall";
    callId: AgentToolCallId;
    name: string;
    summary?: string;
  }
  | {
    "kind": "toolResult";
    callId: AgentToolCallId;
    isError: boolean;
    summary?: string;
  }
  | { "kind": "usage"; usage: AgentUsage };

/**
 * Why a turn ended.
 */
export type AgentFinishReason = "completed" | "cancelled" | "limit";

/**
 * One discovered agent installation.
 */
export type AgentInstallation = {
  installationId: AgentInstallationId;
  displayName: string;
  version?: string;
  locationDisplay?: string;
  availability: AgentAvailability;
};

/**
 * Plugin-issued installation identity, scoped to `(plugin content owner, provider, generation)`.
 *
 * Must not be routed across plugin content owner, provider, generation or session boundaries.
 */
export type AgentInstallationId = string;

/**
 * A safe MCP server summary (no command/env/token).
 */
export type AgentMcpServerSummary = {
  id: AgentResourceId;
  displayName: string;
  transport: AgentMcpTransport;
  enabled: boolean;
  source: AgentResourceSource;
};

/**
 * MCP transport kind.
 */
export type AgentMcpTransport = "stdio" | "http" | "sse" | "unknown";

/**
 * Output channel for a text delta.
 */
export type AgentOutputChannel = "assistant" | "reasoning" | "tool";

/**
 * A bounded page limit for paginated agent requests (§13.1: integer `1..=100`).
 */
export type AgentPageLimit = number;

/**
 * An agent prompt: 1..=1 MiB UTF-8 with whitespace and newlines preserved (no trim/normalization).
 */
export type AgentPrompt = string;

/**
 * Local agent provider identity within one manifest (`claude-code`).
 *
 * Distinct from the dotted [`PluginId`]; the global provider key is the structured pair
 * `(PluginId, AgentProviderId)`. Wire only carries the local id, and the activate descriptor must
 * equal the manifest contribution id exactly.
 */
export type AgentProviderId = string;

/**
 * Opaque resource identity (skill, MCP server, etc.) within one provider.
 */
export type AgentResourceId = string;

/**
 * Origin of a resource surfaced by the provider.
 */
export type AgentResourceSource =
  | { "type": "user" }
  | { "type": "project" }
  | { "type": "worktree" }
  | { "type": "builtIn" }
  | { "type": "unknown"; display?: string };

/**
 * Call context for one Agent request, carrying Host-issued opaque handles and a resolved cwd.
 */
export type AgentScope = { "type": "global" } | {
  "type": "project";
  projectHandle: ProjectHandle;
  workingDirectory: HostResolvedAbsolutePath;
} | {
  "type": "worktree";
  projectHandle: ProjectHandle;
  worktreeHandle: WorktreeHandle;
  workingDirectory: HostResolvedAbsolutePath;
};

/**
 * A safe skill summary.
 */
export type AgentSkillSummary = {
  id: AgentResourceId;
  displayName: string;
  description?: string;
  source: AgentResourceSource;
};

/**
 * Identity of one tool call within a turn.
 */
export type AgentToolCallId = string;

/**
 * Plugin-issued turn identity for one completed agent turn.
 */
export type AgentTurnId = string;

/**
 * Terminal result of a turn.
 */
export type AgentTurnResult = {
  conversationId: AgentConversationId;
  turnId?: AgentTurnId;
  finishReason: AgentFinishReason;
  usage?: AgentUsage;
};

/**
 * Token/cost usage for one turn.
 */
export type AgentUsage = {
  inputTokens?: JsonSafeU64;
  outputTokens?: JsonSafeU64;
  costMicros?: JsonSafeU64;
};

/**
 * Parameters for `agent.cancelConversation`.
 */
export type CancelConversationRequest = {
  providerId: AgentProviderId;
  installationId: AgentInstallationId;
  conversationId: AgentConversationId;
  scope: AgentScope;
};

/**
 * Result of `agent.cancelConversation`.
 */
export type CancelConversationResponse = { disposition: CancelDisposition };

/**
 * Outcome of cancelling an active turn.
 */
export type CancelDisposition = "accepted" | "alreadyStopped";

/**
 * `$/cancelRequest` notification params: cancels one in-flight request id (§12.6).
 */
export type CancelRequestParams = { id: RequestId };

/**
 * Host-issued canonical lowercase UUID correlation id, used for end-to-end logging only.
 *
 * Does not grant idempotency or automatic retry semantics.
 */
export type ClientRequestId = string;

/**
 * A content-owner identity using the Windows-path-safe form `sha256-<64 lowercase hex>` (§6.1).
 *
 * Display digests may be written as `sha256:<hex>`, but the colon form must never be used as a
 * directory name; this newtype is the path-safe form.
 */
export type ContentOwnerId = string;

/**
 * `$/deactivate` request params (§12.8).
 */
export type DeactivateParams = { reason: DeactivateReason };

/**
 * Why the Host is deactivating the plugin (§12.8).
 */
export type DeactivateReason =
  | "manualStop"
  | "disable"
  | "uninstall"
  | "shutdown"
  | "grantChanged";

/**
 * `$/deactivate` response (§12.8: `result` is `null`).
 */
export type DeactivateResult = null;

/**
 * One agent contribution declared in the manifest, echoed in `$/initialize`.
 */
export type DeclaredAgent = { id: AgentProviderId; contractVersion: number };

/**
 * Parameters for `agent.discoverInstallations`.
 */
export type DiscoverInstallationsRequest = {
  providerId: AgentProviderId;
  scope: AgentScope;
};

/**
 * Result of `agent.discoverInstallations`.
 */
export type DiscoverInstallationsResponse = {
  installations: Array<AgentInstallation>;
  diagnostics: Array<AgentDiscoveryDiagnostic>;
};

/**
 * A finite JSON number; NaN and ±Infinity are rejected (§13.1).
 */
export type FiniteJsonNumber = number;

/**
 * Parameters for `agent.getConfigurationSummary`.
 */
export type GetConfigurationSummaryRequest = {
  providerId: AgentProviderId;
  installationId: AgentInstallationId;
  scope: AgentScope;
};

/**
 * Result of `agent.getConfigurationSummary`.
 */
export type GetConfigurationSummaryResponse = {
  items: Array<AgentConfigurationItem>;
};

/**
 * A Host-canonicalized absolute Windows path issued with a request.
 *
 * The Host resolves and canonicalizes the working directory per request so plugins never need a
 * Plugin→Host path API. This is a call-context and audit fact, not a filesystem sandbox.
 */
export type HostResolvedAbsolutePath = string;

/**
 * The seven exact `$/initialize` `limits` (§12.8, §13.1).
 *
 * `maxFrameBytes` must equal the wire v1 constant; the other six are per-generation caps the Host
 * may tighten but not raise above the v1 hard caps. The plugin has no `limits` response.
 */
export type InitializeLimits = {
  maxFrameBytes: number;
  maxPendingRequests: number;
  maxAgentEventBytes: number;
  maxAgentResultBytes: number;
  maxAgentPromptBytes: number;
  maxActiveTurns: number;
  maxPageItems: number;
};

/**
 * `$/initialize` request params (§12.8).
 */
export type InitializeParams = {
  wireVersion: number;
  hostVersion: string;
  runtimeVersion: string;
  sessionId: SessionId;
  plugin: InitializePlugin;
  paths: InitializePaths;
  declaredAgents: Array<DeclaredAgent>;
  limits: InitializeLimits;
};

/**
 * Host-derived managed paths sent in `$/initialize` (§12.8).
 *
 * `entryPath` is for the private bootstrap to import during `$/activate`; it is not exposed to the
 * author `ExtensionContext`. None of these is selectable by the plugin or the client.
 */
export type InitializePaths = {
  extensionPath: HostResolvedAbsolutePath;
  entryPath: HostResolvedAbsolutePath;
  storagePath: HostResolvedAbsolutePath;
};

/**
 * The plugin descriptor sent in `$/initialize`.
 */
export type InitializePlugin = {
  id: PluginId;
  version: PluginVersion;
  kind: PluginKindTag;
  pluginApi: number;
  contentOwner: ContentOwnerId;
};

/**
 * `$/initialize` response (§12.8).
 */
export type InitializeResult = {
  wireVersion: number;
  runtimeVersion: string;
  sessionId: SessionId;
  plugin: InitializeResultPlugin;
};

/**
 * The plugin identity echoed in `$/initialize` result.
 */
export type InitializeResultPlugin = { id: PluginId; version: PluginVersion };

/**
 * Invocation semantics for an Agent method (§12.6). Host never auto-replays either kind.
 */
export type InvocationSemantics = "Idempotent" | "NonIdempotent";

/**
 * A raw JSON object (`Record<string, JsonValue>`), used for business-error `details`.
 */
export type JsonObject = Record<string, JsonValue>;

/**
 * A JSON-RPC error object carried in a Response frame (§12.5, §16.1).
 *
 * `code` is an i32 in the JSON-RPC 2.0 / Ora extension range; `data`, when present, is always a
 * JSON object (e.g. the `-32000` business error payload `{ kind, retryable, details? }`).
 */
export type JsonRpcError = {
  code: number;
  message: string;
  data?: Record<string, unknown>;
};

/**
 * A JSON-RPC error Response envelope (§12.5): `jsonrpc`, `id`, `error`.
 *
 * `id` echoes the in-flight request id exactly (always a non-empty string here). The `id: null`
 * sentinel diagnostics for unparseable requests are emitted as raw JSON by the runtime, not
 * through this typed envelope.
 */
export type JsonRpcErrorResponse = {
  jsonrpc: JsonRpcVersion;
  id: RequestId;
  error: JsonRpcError;
};

/**
 * A JSON-RPC Notification envelope (§12.5): `jsonrpc`, `method`, optional `params`, no `id`.
 */
export type JsonRpcNotification = {
  jsonrpc: JsonRpcVersion;
  method: string;
  params?: unknown;
};

/**
 * A JSON-RPC Request envelope (§12.5): `jsonrpc`, `id`, `method`, optional `params`.
 *
 * `params` carries the raw payload; the router deserializes it into the method's typed DTO
 * (lifecycle §12.8 or Agent §13.1) and applies its strict validation separately.
 */
export type JsonRpcRequest = {
  jsonrpc: JsonRpcVersion;
  id: RequestId;
  method: string;
  params?: unknown;
};

/**
 * A JSON-RPC success Response envelope (§12.5): `jsonrpc`, `id`, `result`.
 */
export type JsonRpcSuccessResponse = {
  jsonrpc: JsonRpcVersion;
  id: RequestId;
  result: unknown;
};

/**
 * The JSON-RPC version marker, fixed to `"2.0"` (§12.5).
 *
 * Serializes as the literal `"2.0"` and rejects any other value on deserialize, so a frame whose
 * `jsonrpc` field is absent, `null`, `"1.0"` or any other shape fails envelope validation.
 */
export type JsonRpcVersion = "2.0";

/**
 * A JSON integer constrained to `0..=2^53-1` to avoid JavaScript precision loss (§13.1).
 */
export type JsonSafeU64 = number;

/**
 * A recursive JSON value type for the SDK, exported as the TS `JsonValue` union (§13.2).
 */
export type JsonValue = null | boolean | number | string | JsonValue[] | {
  [key: string]: JsonValue;
};

/**
 * Parameters for `agent.listConversations`.
 */
export type ListConversationsRequest = {
  providerId: AgentProviderId;
  installationId: AgentInstallationId;
  scope: AgentScope;
  cursor?: AgentCursor;
  limit: AgentPageLimit;
};

/**
 * Result of `agent.listConversations`.
 */
export type ListConversationsResponse = {
  items: Array<AgentConversationSummary>;
  nextCursor?: AgentCursor;
};

/**
 * Parameters for `agent.listMcpServers`.
 */
export type ListMcpServersRequest = {
  providerId: AgentProviderId;
  installationId: AgentInstallationId;
  scope: AgentScope;
  cursor?: AgentCursor;
  limit: AgentPageLimit;
};

/**
 * Result of `agent.listMcpServers`.
 */
export type ListMcpServersResponse = {
  items: Array<AgentMcpServerSummary>;
  nextCursor?: AgentCursor;
};

/**
 * Parameters for `agent.listSkills`.
 */
export type ListSkillsRequest = {
  providerId: AgentProviderId;
  installationId: AgentInstallationId;
  scope: AgentScope;
  cursor?: AgentCursor;
  limit: AgentPageLimit;
};

/**
 * Result of `agent.listSkills`.
 */
export type ListSkillsResponse = {
  items: Array<AgentSkillSummary>;
  nextCursor?: AgentCursor;
};

/**
 * Engine compatibility declarations (§5.1).
 *
 * `ora` is the Ora app version range; `pluginApi` is the exact bootstrap↔plugin ABI version
 * (agent v1 must declare `1`); `bun` is the Bun runtime range (agent only).
 */
export type PluginEngines = {
  ora: SemverRange;
  pluginApi?: number;
  bun?: SemverRange;
};

/**
 * Canonical, immutable plugin identity used for directory names, state keys and registry keys.
 *
 * Identity comparison, directory names, state keys and registry keys all use the same canonical
 * value (§3.4). There is at most one installed instance per canonical id in the MVP.
 */
export type PluginId = string;

/**
 * Discriminated manifest kind (§5.3).
 */
export type PluginKindManifest = {
  "kind": "agent";
  main: PluginRelativePath;
  contributes: AgentContributions;
} | { "kind": "workbench"; contributes: WorkbenchContributions };

/**
 * The standalone manifest kind tag carried in lifecycle DTOs (§5.3, §12.8).
 *
 * [`PluginKindManifest`] carries this tag together with its variant data; lifecycle DTOs such as
 * `$/initialize` need only the tag string, so this enum mirrors the `kind` discriminant without
 * the contribution payload.
 */
export type PluginKindTag = "agent" | "workbench";

/**
 * A parsed plugin manifest (the `ora` object of `package.json`).
 *
 * Deserialization is performed by [`PluginManifest::parse_from_ora_bytes`] with manual kind routing
 * and strict unknown-field rejection, so this type derives only `Serialize`/`TS` (not
 * `Deserialize`, which would conflict `#[serde(flatten)]` with `deny_unknown_fields`).
 */
export type PluginManifest =
  & {
    manifestVersion: number;
    id: PluginId;
    displayName: string;
    engines: PluginEngines;
  }
  & ({
    "kind": "agent";
    main: PluginRelativePath;
    contributes: AgentContributions;
  } | { "kind": "workbench"; contributes: WorkbenchContributions });

/**
 * A relative path inside the plugin root, validated against escape attempts.
 */
export type PluginRelativePath = string;

/**
 * A strict SemVer plugin version (the top-level `package.json` `version`, §5.1).
 *
 * Stored as the canonical text so it round-trips transparently; validated at construction via the
 * `semver` crate. The manifest `ora` object does not carry the version; it comes from the
 * package.json top level and is fed into `$/initialize` as `plugin.version`.
 */
export type PluginVersion = string;

/**
 * Host-issued, session-bound opaque project handle.
 */
export type ProjectHandle = string;

/**
 * A non-empty envelope `id` of at most 128 UTF-8 bytes (§12.5).
 *
 * Response frames echo the request id exactly. The canonical Host outbound form is `h:<n>`
 * (see [`RequestId::host`]); the generic envelope also admits a plugin's echoed id so the Host
 * can reply to a direction-violating Plugin Request before terminating the generation.
 */
export type RequestId = string;

/**
 * A display timestamp validated as structural RFC 3339 with a `Z` or numeric offset.
 */
export type Rfc3339Timestamp = string;

/**
 * A SemVer requirement range string (e.g. `>=0.1.0 <0.2.0`), parsed and stored as text.
 *
 * Stored as the canonical text so it round-trips and serializes transparently; validation happens
 * at construction via the `semver` crate.
 */
export type SemverRange = string;

/**
 * Parameters for `agent.sendMessage`.
 */
export type SendMessageRequest = {
  providerId: AgentProviderId;
  installationId: AgentInstallationId;
  conversationId: AgentConversationId;
  scope: AgentScope;
  clientRequestId: ClientRequestId;
  prompt: AgentPrompt;
};

/**
 * Host-issued, per-generation CSPRNG session identity (§12.8).
 *
 * Generated by the Host once per runtime generation and never reused; the bootstrap must echo it
 * exactly in the `$/initialize` result. It binds the pipe to a generation, not a publisher
 * identity.
 */
export type SessionId = string;

/**
 * Parameters for `agent.startConversation`.
 */
export type StartConversationRequest = {
  providerId: AgentProviderId;
  installationId: AgentInstallationId;
  scope: AgentScope;
  clientRequestId: ClientRequestId;
  prompt: AgentPrompt;
};

/**
 * `$/stream` notification params: one event for a Host-initiated streaming request (§12.7).
 */
export type StreamNotificationParams = {
  id: RequestId;
  seq: JsonSafeU64;
  value: AgentEvent;
};

/**
 * Workbench v1 contribution placeholder (§5.4).
 */
export type WorkbenchContributions = { schemaVersion: number };

/**
 * Host-issued, session-bound opaque worktree handle.
 */
export type WorktreeHandle = string;
