// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the named parameters for the first plugin `add` capability.
 */
export type PluginAddParams = { a: number; b: number };

/**
 * Carries JSON-RPC error details emitted by the plugin SDK.
 */
export type PluginJsonRpcError = { code: number; message: string };

/**
 * Carries one failed JSON-RPC response emitted by the plugin SDK.
 */
export type PluginJsonRpcErrorResponse = {
  jsonrpc: string;
  id: string;
  error: PluginJsonRpcError;
};

/**
 * Carries one JSON-RPC request sent from the plugin manager to the plugin SDK.
 */
export type PluginJsonRpcRequest = {
  jsonrpc: string;
  id: string;
  method: string;
  params: PluginAddParams;
};

/**
 * Carries one successful JSON-RPC response emitted by the plugin SDK.
 */
export type PluginJsonRpcSuccessResponse = {
  jsonrpc: string;
  id: string;
  result: number;
};
