use ora_plugin_protocol::{
    export_protocol_fixtures_to, export_public_typescript_bindings_to,
    export_runtime_typescript_bindings_to,
};
use std::fs;
use std::path::Path;

const GENERATED_FILE_HEADER: &str = "// This file was generated by `cargo xtask export-plugin-sdk`. Do not edit this file manually.\n";

/// Exports plugin protocol DTOs into the plugin SDK type surface.
pub fn run_export_plugin_sdk(workspace_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let plugin_sdk_types_directory = workspace_root.join("packages/plugin-sdk/src/types");
    let plugin_runtime_types_directory =
        workspace_root.join("packages/plugin-runtime/src/generated");

    export_public_typescript_bindings_to(&plugin_sdk_types_directory)?;
    write_generated_file(
        &plugin_sdk_types_directory.join("index.ts"),
        &render_index_module(),
    )?;
    export_protocol_fixtures_to(workspace_root.join("crates/plugin-protocol/fixtures/v1"))?;
    export_runtime_typescript_bindings_to(&plugin_runtime_types_directory)?;
    write_generated_file(
        &plugin_runtime_types_directory.join("index.ts"),
        &render_index_module(),
    )?;

    Ok(())
}

/// Writes one generated plugin SDK file to disk, creating its parent directory when needed.
fn write_generated_file(
    output_path: &Path,
    contents: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(parent_directory) = output_path.parent() {
        fs::create_dir_all(parent_directory)?;
    }

    fs::write(output_path, contents)?;

    Ok(())
}

/// Renders the plugin SDK type barrel so consumers can import from one stable path.
fn render_index_module() -> String {
    let mut source = String::from(GENERATED_FILE_HEADER);

    source.push_str("export * from \"./plugin-protocol.js\";\n");

    source
}

#[cfg(test)]
mod tests {
    use super::{render_index_module, run_export_plugin_sdk};
    use pretty_assertions::assert_eq;
    use std::fs;
    use tempfile::TempDir;

    /// Verifies the plugin SDK export workflow writes protocol DTOs and the type barrel.
    #[test]
    fn writes_plugin_sdk_type_files() {
        let workspace_root = TempDir::new().unwrap_or_else(|error| {
            panic!("failed to create workspace root: {error}");
        });
        let plugin_sdk_types_directory =
            workspace_root.path().join("packages/plugin-sdk/src/types");
        fs::create_dir_all(&plugin_sdk_types_directory).unwrap_or_else(|error| {
            panic!("failed to create plugin SDK types directory: {error}");
        });

        run_export_plugin_sdk(workspace_root.path()).unwrap_or_else(|error| {
            panic!("expected plugin SDK export workflow to succeed: {error}");
        });

        let protocol_module =
            fs::read_to_string(plugin_sdk_types_directory.join("plugin-protocol.ts"))
                .unwrap_or_else(|error| panic!("failed to read plugin protocol module: {error}"));
        let index_module = fs::read_to_string(plugin_sdk_types_directory.join("index.ts"))
            .unwrap_or_else(|error| panic!("failed to read plugin SDK type index: {error}"));

        assert!(protocol_module.contains("type AgentEvent"));
        assert!(protocol_module.contains("type PluginManifest"));
        assert_eq!(index_module, render_index_module());

        let runtime_protocol = fs::read_to_string(
            workspace_root
                .path()
                .join("packages/plugin-runtime/src/generated/plugin-protocol.ts"),
        )
        .unwrap_or_else(|error| panic!("failed to read runtime protocol module: {error}"));
        assert!(runtime_protocol.contains("type InitializeParams"));
    }
}
