use ora_contracts::{
    FrontendEndpoint, FrontendPathParam, FrontendQueryParam, FrontendResponseMode,
    export_typescript_bindings_to, frontend_endpoints,
};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

const GENERATED_FILE_HEADER: &str = "// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.\n";

/// Exports TypeScript DTOs and the generated endpoint manifest into `packages/contracts/src`.
///
/// Only `endpoints.ts` is generated; all runtime SDK modules (`transport.ts`,
/// `client.ts`, `fetch.ts`, `index.ts`) are hand-written TypeScript and must be
/// edited directly. The generator's job is to keep the endpoint manifest, which
/// mirrors the Rust-owned route table, in sync with the frontend.
pub fn run_export_contracts(workspace_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let contracts_source_directory = workspace_root.join("packages/contracts/src");

    remove_stale_typescript_bindings(&contracts_source_directory)?;
    export_typescript_bindings_to(&contracts_source_directory)?;
    append_js_extension_to_exported_imports(&contracts_source_directory)?;
    write_generated_file(
        &contracts_source_directory.join("endpoints.ts"),
        &render_endpoints_module(frontend_endpoints()),
    )?;

    Ok(())
}

/// Removes only ts-rs-owned files so repeated exports cannot append duplicate declarations.
fn remove_stale_typescript_bindings(directory: &Path) -> Result<(), Box<dyn std::error::Error>> {
    const TS_RS_HEADER: &str = "// This file was generated by [ts-rs]";

    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            remove_stale_typescript_bindings(&path)?;
            continue;
        }

        if path.extension().is_some_and(|extension| extension == "ts")
            && fs::read_to_string(&path)?.starts_with(TS_RS_HEADER)
        {
            fs::remove_file(path)?;
        }
    }

    Ok(())
}

/// Rewrites every ts-rs cross-file import so it resolves under the package `NodeNext` setting.
///
/// ts-rs emits extensionless specifiers, which `moduleResolution: "NodeNext"` rejects.
fn append_js_extension_to_exported_imports(
    contracts_source_directory: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(contracts_source_directory)? {
        let path = entry?.path();

        if path.is_dir() {
            append_js_extension_to_exported_imports(&path)?;
            continue;
        }

        if path.extension().is_some_and(|extension| extension == "ts") {
            let contents = fs::read_to_string(&path)?;
            let rewritten = append_js_extension_to_relative_specifiers(&contents);

            if rewritten != contents {
                fs::write(&path, rewritten)?;
            }
        }
    }

    Ok(())
}

/// Appends the `.js` extension to each relative module specifier that still lacks one.
fn append_js_extension_to_relative_specifiers(contents: &str) -> String {
    const SPECIFIER_PREFIX: &str = "from \"";

    let mut rewritten = String::with_capacity(contents.len());
    let mut remainder = contents;

    while let Some(prefix_start) = remainder.find(SPECIFIER_PREFIX) {
        let specifier_start = prefix_start + SPECIFIER_PREFIX.len();
        let Some(specifier_length) = remainder[specifier_start..].find('"') else {
            break;
        };
        let specifier_end = specifier_start + specifier_length;
        let specifier = &remainder[specifier_start..specifier_end];

        rewritten.push_str(&remainder[..specifier_end]);

        if (specifier.starts_with("./") || specifier.starts_with("../"))
            && !specifier.ends_with(".js")
        {
            rewritten.push_str(".js");
        }

        remainder = &remainder[specifier_end..];
    }

    rewritten.push_str(remainder);

    rewritten
}

/// Writes one generated file to disk, creating its parent directory when needed.
fn write_generated_file(
    output_path: &Path,
    contents: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(parent_directory) = output_path.parent() {
        fs::create_dir_all(parent_directory)?;
    }

    fs::write(output_path, contents)?;

    Ok(())
}

/// Renders the endpoint manifest and operation type maps consumed by the hand-written client.
///
/// The generated file mixes runtime data (`endpoints` const) with compile-time
/// type maps (`RequestByOperation`, `ResponseByOperation`). The const value is
/// emitted with `as const`-friendly literal metadata so the hand-written client
/// can narrow `method`/`pathTemplate`/etc. without casts.
fn render_endpoints_module(endpoints: &[FrontendEndpoint]) -> String {
    let mut source = String::from(GENERATED_FILE_HEADER);
    let imports = collect_contract_type_imports(endpoints);

    for (module_name, types) in imports {
        source.push_str("import type { ");
        source.push_str(&join_types(&types));
        source.push_str(" } from \"./");
        source.push_str(module_name);
        source.push_str(".js\";\n");
    }

    source.push_str("import type { HttpMethod } from \"./transport.js\";\n\n");
    source.push_str("export type EndpointPathParam = {\n");
    source.push_str("  rustFieldName: string;\n");
    source.push_str("  wireName: string;\n");
    source.push_str("};\n\n");
    source.push_str("export type EndpointQueryParam = {\n");
    source.push_str("  rustFieldName: string;\n");
    source.push_str("  wireName: string;\n");
    source.push_str("};\n\n");
    source.push_str("export type FrontendEndpointDefinition = {\n");
    source.push_str("  operationName: string;\n");
    source.push_str("  namespace: string;\n");
    source.push_str("  memberName: string;\n");
    source.push_str("  method: HttpMethod;\n");
    source.push_str("  pathTemplate: string;\n");
    source.push_str("  requestType: string;\n");
    source.push_str("  responseType: string;\n");
    source.push_str("  responseMode: \"unary\" | \"stream\";\n");
    source.push_str("  pathParams: readonly EndpointPathParam[];\n");
    source.push_str("  queryParams: readonly EndpointQueryParam[];\n");
    source.push_str("  hasJsonBody: boolean;\n");
    source.push_str("};\n\n");
    source.push_str("export type RequestByOperation = {\n");

    for endpoint in endpoints {
        source.push_str("  ");
        source.push_str(endpoint.operation_name);
        source.push_str(": ");
        source.push_str(endpoint.request_type);
        source.push_str(";\n");
    }

    source.push_str("};\n\n");
    source.push_str("export type ResponseByOperation = {\n");

    for endpoint in endpoints {
        source.push_str("  ");
        source.push_str(endpoint.operation_name);
        source.push_str(": ");
        source.push_str(endpoint.response_type);
        source.push_str(";\n");
    }

    source.push_str("};\n\n");
    source.push_str("export type EndpointOperation = keyof RequestByOperation;\n\n");

    // `as const` narrows every literal to its concrete value type, so the
    // hand-written client can rely on `endpoint.method` being `"POST"` rather
    // than the widened `HttpMethod` union. The `satisfies` clause keeps the
    // manifest structurally checked against the per-operation type maps at
    // compile time.
    source.push_str("export const endpoints = {\n");

    for endpoint in endpoints {
        source.push_str("  ");
        source.push_str(endpoint.operation_name);
        source.push_str(": {\n");
        source.push_str("    operationName: \"");
        source.push_str(endpoint.operation_name);
        source.push_str("\",\n");
        source.push_str("    namespace: \"");
        source.push_str(endpoint.namespace);
        source.push_str("\",\n");
        source.push_str("    memberName: \"");
        source.push_str(endpoint.member_name);
        source.push_str("\",\n");
        source.push_str("    method: \"");
        source.push_str(render_http_method(endpoint));
        source.push_str("\",\n");
        source.push_str("    pathTemplate: \"");
        source.push_str(endpoint.path_template);
        source.push_str("\",\n");
        source.push_str("    requestType: \"");
        source.push_str(endpoint.request_type);
        source.push_str("\",\n");
        source.push_str("    responseType: \"");
        source.push_str(endpoint.response_type);
        source.push_str("\",\n");
        source.push_str("    responseMode: \"");
        source.push_str(match endpoint.response_mode() {
            FrontendResponseMode::Unary => "unary",
            FrontendResponseMode::Stream => "stream",
        });
        source.push_str("\",\n");
        source.push_str("    pathParams: ");
        source.push_str(&render_path_params(endpoint.path_params));
        source.push_str(",\n");
        source.push_str("    queryParams: ");
        source.push_str(&render_query_params(endpoint.query_params()));
        source.push_str(",\n");
        source.push_str("    hasJsonBody: ");
        source.push_str(if endpoint.has_json_body {
            "true"
        } else {
            "false"
        });
        source.push_str(",\n");
        source.push_str("  },\n");
    }

    source
        .push_str("} as const satisfies Record<EndpointOperation, FrontendEndpointDefinition>;\n");

    source
}

/// Collects the TypeScript DTO imports needed by the generated endpoint manifest.
fn collect_contract_type_imports(
    endpoints: &[FrontendEndpoint],
) -> BTreeMap<&'static str, BTreeSet<&'static str>> {
    let mut imports = BTreeMap::new();

    for endpoint in endpoints {
        imports
            .entry(contract_module_for_type(endpoint.request_type))
            .or_insert_with(BTreeSet::new)
            .insert(endpoint.request_type);
        imports
            .entry(contract_module_for_type(endpoint.response_type))
            .or_insert_with(BTreeSet::new)
            .insert(endpoint.response_type);
    }

    imports
}

/// Maps one exported contract type name to the TypeScript module that contains it.
fn contract_module_for_type(type_name: &str) -> &'static str {
    match type_name {
        "CreateProjectRequest"
        | "CreateProjectResponse"
        | "DeleteProjectRequest"
        | "DeleteProjectResponse"
        | "GetProjectRequest"
        | "GetProjectResponse"
        | "ListProjectsRequest"
        | "ListProjectsResponse"
        | "UpdateProjectRequest"
        | "UpdateProjectResponse" => "project",
        "OpenProjectWorkContextRequest"
        | "OpenProjectWorkContextResponse"
        | "ProjectWorkContext"
        | "RenewProjectWorkContextRequest"
        | "RenewProjectWorkContextResponse" => "project-work-context",
        "CreateTaskRequest" | "CreateTaskResponse" | "DeleteTaskRequest" | "DeleteTaskResponse"
        | "GetTaskRequest" | "GetTaskResponse" | "ListTasksRequest" | "ListTasksResponse"
        | "UpdateTaskRequest" | "UpdateTaskResponse" => "task",
        "CreateSessionRequest"
        | "CreateSessionResponse"
        | "DeleteSessionRequest"
        | "DeleteSessionResponse"
        | "GetSessionRequest"
        | "GetSessionResponse"
        | "ListAgentModelsRequest"
        | "ListAgentModelsResponse"
        | "LoadSessionRequest"
        | "LoadSessionEvent"
        | "ListSessionsRequest"
        | "ListSessionsResponse"
        | "PromptSessionRequest"
        | "PromptSessionEvent"
        | "RespondToPermissionRequest"
        | "RespondToPermissionResponse"
        | "StopSessionRequest"
        | "StopSessionResponse" => "session",
        "CreateSkillRequest"
        | "CreateSkillResponse"
        | "DeleteSkillRequest"
        | "DeleteSkillResponse"
        | "GetSkillRequest"
        | "GetSkillResponse"
        | "ListSkillsRequest"
        | "ListSkillsResponse"
        | "UpdateSkillRequest"
        | "UpdateSkillResponse" => "skill",
        "CreateAgentRequest"
        | "CreateAgentResponse"
        | "DeleteAgentRequest"
        | "DeleteAgentResponse"
        | "GetAgentRequest"
        | "GetAgentResponse"
        | "ListAgentsRequest"
        | "ListAgentsResponse"
        | "UpdateAgentRequest"
        | "UpdateAgentResponse" => "agent",
        "ListDirectoryRequest" | "ListDirectoryResponse" => "file-system",
        "GetGitIdentityRequest" | "GitIdentityResponse" => "git",
        other => panic!("unknown contract type `{other}`"),
    }
}

/// Renders one HTTP method enum value as the wire-level string used by the SDK.
fn render_http_method(endpoint: &FrontendEndpoint) -> &'static str {
    match endpoint.method {
        ora_contracts::FrontendHttpMethod::Get => "GET",
        ora_contracts::FrontendHttpMethod::Post => "POST",
        ora_contracts::FrontendHttpMethod::Put => "PUT",
        ora_contracts::FrontendHttpMethod::Delete => "DELETE",
    }
}

/// Renders the endpoint path parameter metadata into a TypeScript array literal.
fn render_path_params(path_params: &[FrontendPathParam]) -> String {
    if path_params.is_empty() {
        return "[]".to_string();
    }

    let mut rendered = String::from("[");

    for (index, path_param) in path_params.iter().enumerate() {
        if index > 0 {
            rendered.push_str(", ");
        }

        rendered.push_str("{ ");
        rendered.push_str("rustFieldName: \"");
        rendered.push_str(path_param.rust_field_name);
        rendered.push_str("\", ");
        rendered.push_str("wireName: \"");
        rendered.push_str(path_param.wire_name);
        rendered.push_str("\" }");
    }

    rendered.push(']');
    rendered
}

/// Renders optional query parameter metadata into a TypeScript array literal.
fn render_query_params(query_params: &[FrontendQueryParam]) -> String {
    if query_params.is_empty() {
        return "[]".to_string();
    }

    let mut rendered = String::from("[");

    for (index, query_param) in query_params.iter().enumerate() {
        if index > 0 {
            rendered.push_str(", ");
        }

        rendered.push_str("{ ");
        rendered.push_str("rustFieldName: \"");
        rendered.push_str(query_param.rust_field_name);
        rendered.push_str("\", ");
        rendered.push_str("wireName: \"");
        rendered.push_str(query_param.wire_name);
        rendered.push_str("\" }");
    }

    rendered.push(']');
    rendered
}

/// Renders a sorted import set into a comma-separated type list.
fn join_types(types: &BTreeSet<&'static str>) -> String {
    types.iter().copied().collect::<Vec<_>>().join(", ")
}

#[cfg(test)]
mod tests {
    use super::{
        append_js_extension_to_relative_specifiers, render_endpoints_module, run_export_contracts,
    };
    use ora_contracts::frontend_endpoints;
    use std::fs;
    use tempfile::TempDir;

    /// Verifies ts-rs cross-file imports gain the extension `NodeNext` resolution requires.
    #[test]
    fn appends_js_extension_to_extensionless_relative_imports() {
        let rewritten = append_js_extension_to_relative_specifiers(
            "import type { Plan } from \"./acp/plan\";\nimport type { Task } from \"../task\";\n",
        );

        assert_eq!(
            rewritten,
            "import type { Plan } from \"./acp/plan.js\";\nimport type { Task } from \"../task.js\";\n"
        );
    }

    /// Verifies already-suffixed and bare package specifiers survive the rewrite untouched.
    #[test]
    fn preserves_specifiers_that_need_no_extension() {
        let source = "import type { Task } from \"./task.js\";\nimport { z } from \"zod\";\nexport type A = { from: \"./x\" };\n";

        assert_eq!(append_js_extension_to_relative_specifiers(source), source);
    }

    /// Verifies the generated endpoint manifest preserves update-route path metadata.
    #[test]
    fn renders_endpoint_manifest_with_update_path_params() {
        let module = render_endpoints_module(frontend_endpoints());

        assert!(module.contains("updateTask"));
        assert!(module.contains("pathTemplate: \"/api/tasks/{taskId}\""));
        assert!(module.contains("wireName: \"taskId\""));
    }

    /// Verifies the generated manifest narrows literal values with `as const`
    /// so the hand-written client can rely on literal method/path types.
    #[test]
    fn emits_as_const_satisfies_clauses() {
        let module = render_endpoints_module(frontend_endpoints());

        assert!(module.contains(
            "} as const satisfies Record<EndpointOperation, FrontendEndpointDefinition>;\n"
        ));
    }

    /// Verifies the export workflow writes DTOs and the generated endpoint manifest.
    #[test]
    fn writes_contract_package_files() {
        let workspace_root = TempDir::new().unwrap_or_else(|error| {
            panic!("failed to create workspace root: {error}");
        });
        let package_source_directory = workspace_root.path().join("packages/contracts/src");
        fs::create_dir_all(&package_source_directory).unwrap_or_else(|error| {
            panic!("failed to create package source directory: {error}");
        });

        run_export_contracts(workspace_root.path()).unwrap_or_else(|error| {
            panic!("expected export workflow to succeed: {error}");
        });

        let generated_files = [
            "agent.ts",
            "endpoints.ts",
            "file-system.ts",
            "project.ts",
            "project-work-context.ts",
            "session.ts",
            "skill.ts",
            "task.ts",
        ];

        for generated_file in generated_files {
            let output_path = package_source_directory.join(generated_file);
            assert!(
                output_path.exists(),
                "missing generated file {:?}",
                output_path
            );
        }
    }
}
