//! Ownership-aware publication and drift checks for Rust-generated frontend artifacts.
//!
//! A generated header authorizes replacing or removing that file only inside the declared output
//! roots. Unknown files survive exports, and collisions fail before any output is changed.

use ora_utils::path::{CanonicalPathRoot, canonicalize_longest_existing_prefix};
use ora_utils::text::normalize_newlines;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

type Artifacts = BTreeMap<PathBuf, String>;

/// Collects generated files independently of Git, including stale and untracked artifacts.
fn snapshot(workspace: &Path) -> Result<Artifacts, Box<dyn std::error::Error>> {
    let workspace = CanonicalPathRoot::new(workspace)?;
    let mut files = BTreeMap::new();
    for root in [
        Path::new("packages").join("contracts").join("src"),
        Path::new("packages")
            .join("plugin-sdk")
            .join("src")
            .join("protocol"),
        Path::new("apps").join("desktop").join("web"),
        Path::new("apps")
            .join("desktop")
            .join("src-tauri")
            .join("src"),
        Path::new("apps")
            .join("desktop")
            .join("src-tauri")
            .join("permissions"),
    ] {
        collect(&workspace, &root, &mut files)?;
    }
    Ok(files)
}

/// Walks only real directories; symbolic links never expand the generator's ownership.
fn collect(
    workspace: &CanonicalPathRoot,
    relative: &Path,
    files: &mut Artifacts,
) -> Result<(), Box<dyn std::error::Error>> {
    let directory = workspace.as_path().join(relative);
    match fs::symlink_metadata(&directory) {
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error.into()),
        Ok(metadata) if !metadata.is_dir() => {
            return Err(format!(
                "generated output directory is not a real directory: {}",
                directory.display()
            )
            .into());
        }
        Ok(_) => {}
    }
    workspace.resolve_existing_absolute(&directory)?;
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let relative = relative.join(entry.file_name());
        let kind = entry.file_type()?;
        if kind.is_dir() {
            collect(workspace, &relative, files)?;
        } else if kind.is_file()
            && relative.extension().is_some_and(|extension| {
                extension == "ts" || extension == "rs" || extension == "toml"
            })
        {
            let source = fs::read_to_string(entry.path())?;
            if source.starts_with("// This file was generated by [ts-rs]")
                || source
                    .starts_with("// This file was generated by `cargo xtask export-contracts`.")
                || source
                    .starts_with("# This file was generated by `cargo xtask export-contracts`.")
            {
                files.insert(relative, source);
            }
        }
    }
    Ok(())
}

/// Reports missing, changed, and retired artifacts without repairing away evidence of drift.
pub(crate) fn check(workspace: &Path, staging: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let current = snapshot(workspace)?;
    let expected = snapshot(staging)?;
    let mut differences = Vec::new();
    for (path, content) in &expected {
        if current
            .get(path)
            .is_none_or(|current| normalize_newlines(current) != normalize_newlines(content))
        {
            differences.push(format!("missing or changed: {}", path.display()));
        }
    }
    for path in current.keys().filter(|path| !expected.contains_key(*path)) {
        differences.push(format!("stale: {}", path.display()));
    }
    if differences.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "generated artifacts differ; run task export-contracts:\n{}",
            differences.join("\n")
        )
        .into())
    }
}

/// Publishes only owned artifacts after validating all collisions, preserving hand-written files.
pub(crate) fn publish(workspace: &Path, staging: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let current = snapshot(workspace)?;
    let expected = snapshot(staging)?;
    let root = CanonicalPathRoot::new(workspace)?;
    for relative in expected.keys() {
        let destination = root.as_path().join(relative);
        // Shared path containment also covers missing outputs under existing linked parents.
        root.relative_path(&canonicalize_longest_existing_prefix(&destination))?;
        match fs::symlink_metadata(&destination) {
            Ok(_) if !current.contains_key(relative) => {
                return Err(format!(
                    "generated output collides with an unowned file or link: {}",
                    destination.display()
                )
                .into());
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error.into()),
        }
    }
    for (relative, source) in &expected {
        if current
            .get(relative)
            .is_none_or(|current| normalize_newlines(current) != normalize_newlines(source))
        {
            let output = workspace.join(relative);
            if let Some(parent) = output.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(output, source)?;
        }
    }
    for relative in current.keys().filter(|path| !expected.contains_key(*path)) {
        fs::remove_file(workspace.join(relative))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{check, publish, snapshot};
    use pretty_assertions::assert_eq;
    use std::fs;
    use std::path::{Path, PathBuf};

    /// Seeds a generated DTO without relying on repository files or Git tracking state.
    fn fixture(workspace: &Path, name: &str, body: &str) -> PathBuf {
        let directory = workspace.join("packages").join("contracts").join("src");
        fs::create_dir_all(&directory)
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        let path = directory.join(name);
        fs::write(
            &path,
            format!("// This file was generated by [ts-rs].\n{body}"),
        )
        .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        path
    }

    /// Inventory changes and byte changes are detected without rewriting the observed checkout.
    #[test]
    fn detects_missing_changed_and_stale_outputs_without_git() {
        let workspace =
            tempfile::tempdir().unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        let staging =
            tempfile::tempdir().unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        fixture(
            staging.path(),
            "current.ts",
            "export type Current = string;\n",
        );
        assert!(check(workspace.path(), staging.path()).is_err());
        publish(workspace.path(), staging.path())
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        check(workspace.path(), staging.path())
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        fixture(workspace.path(), "current.ts", "changed");
        fixture(workspace.path(), "retired.ts", "retired");
        let before = snapshot(workspace.path())
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        let error = match check(workspace.path(), staging.path()) {
            Ok(()) => panic!("changed and retired artifacts must fail verification"),
            Err(error) => error.to_string(),
        };
        assert!(error.contains("missing or changed:"));
        assert!(error.contains("stale:"));
        assert_eq!(
            snapshot(workspace.path())
                .unwrap_or_else(|error| panic!("fixture operation failed: {error}")),
            before
        );
        publish(workspace.path(), staging.path())
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        assert_eq!(
            snapshot(workspace.path())
                .unwrap_or_else(|error| panic!("fixture operation failed: {error}")),
            snapshot(staging.path())
                .unwrap_or_else(|error| panic!("fixture operation failed: {error}"))
        );
    }

    /// Platform line endings do not make otherwise identical generated output stale.
    #[test]
    fn accepts_and_preserves_equivalent_lf_and_crlf_outputs() {
        let workspace =
            tempfile::tempdir().unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        let staging =
            tempfile::tempdir().unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        let current = fixture(
            workspace.path(),
            "current.ts",
            "export type Current = string;\n",
        );
        let source = fs::read_to_string(&current)
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        fs::write(&current, source.replace('\n', "\r\n"))
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        fixture(
            staging.path(),
            "current.ts",
            "export type Current = string;\n",
        );

        check(workspace.path(), staging.path())
            .unwrap_or_else(|error| panic!("equivalent line endings must pass: {error}"));
        let before =
            fs::read(&current).unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        publish(workspace.path(), staging.path())
            .unwrap_or_else(|error| panic!("equivalent line endings must publish: {error}"));
        assert_eq!(
            fs::read(&current).unwrap_or_else(|error| panic!("fixture operation failed: {error}")),
            before
        );
    }

    /// An output name collision cannot silently overwrite user code or delete older artifacts.
    #[test]
    fn preserves_unowned_files_and_rejects_collisions_before_publication() {
        let workspace =
            tempfile::tempdir().unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        let staging =
            tempfile::tempdir().unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        let old = fixture(workspace.path(), "retired.ts", "retired");
        let user = old.with_file_name("new.ts");
        fs::write(&user, "// hand-written\nexport const value = 42;\n")
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        fixture(staging.path(), "new.ts", "replacement");
        let before = snapshot(workspace.path())
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        assert!(publish(workspace.path(), staging.path()).is_err());
        assert_eq!(
            snapshot(workspace.path())
                .unwrap_or_else(|error| panic!("fixture operation failed: {error}")),
            before
        );
        assert_eq!(
            fs::read_to_string(&user)
                .unwrap_or_else(|error| panic!("fixture operation failed: {error}")),
            "// hand-written\nexport const value = 42;\n"
        );
        fs::rename(&user, old.with_file_name("custom.ts"))
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        publish(workspace.path(), staging.path())
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        assert!(!old.exists());
        assert_eq!(
            fs::read_to_string(old.with_file_name("custom.ts"))
                .unwrap_or_else(|error| panic!("fixture operation failed: {error}")),
            "// hand-written\nexport const value = 42;\n"
        );
    }
}
